### ISSUE TITLE
ScalaMock fails in Scala.js due to wrong number of super classes

### ISSUE THREAD

**Issue by ochrons** [scala-js/scala-js#2952] opened 2017-05-15 13:43 UTC
Original issue at ScalaMock repo https://github.com/paulbutcher/ScalaMock/issues/185

After some investigation, @barkhorn could not point out a problem in ScalaMock, so this might be an issue in Scala.js itself.

A simplified test case can be found in branch https://github.com/suzaku-io/suzaku/tree/scalamock185

Running `coreJS/test` runs just this single test that exposes the problem.

**Comment by sjrd** [comment] 2017-05-15 13:45
Not sure when I'll have time to look at this, but eventually I'll manage.

**Comment by gzm0** [comment] 2017-05-15 17:52
Looks like it could be an outer pointer collision.

**Comment by sjrd** [comment] 2017-05-15 17:54
No, according to the original report, it also fails on 2.12.2. And 2.12.x is not affected by the outer pointer collision bug.

**Comment by sjrd** [comment] 2017-06-02 11:05
There's something wrong happening before the end of the `typer` phase, so I don't think Scala.js is to blame. It seems to be a problem in one of ScalaMock's macros.

After `typer`, I see the following for `UIManagerSpec.scala`:
```scala
  class MockUIChannel extends arteria.core.MessageChannel[suzaku.ui.UIProtocol.type] {
    def <init>(): suzaku.ui.MockUIChannel = {
      MockUIChannel.super.<init>(UIProtocol)(0, 0, null, new MockUIHandler(), null);
      ()
    };
    <empty>
  };
  class UIManagerSpec extends suzaku.UnitSpec with org.scalamock.scalatest.MockFactory {
    def <init>(): suzaku.ui.UIManagerSpec = {
      UIManagerSpec.super.<init>();
      ()
    };
    class TestUIManager extends UIManager {
      def <init>(): UIManagerSpec.this.TestUIManager = {
        TestUIManager.super.<init>(suzaku.TestLogger, ((x$2: suzaku.ui.UIProtocol.UIChannel) => ()), (() => ()));
        ()
      };
      TestUIManager.this.uiChannel_=(({
  final class $anon extends suzaku.ui.MockUIChannel {
    def <init>(): <$anon: suzaku.ui.MockUIChannel> = {
      $anon.super.<init>();
      ()
    };
    private[this] val mock$special$mockName: String = UIManagerSpec.this._factory.generateMockDefaultName("mock").name;
    <stable> <accessor> def mock$special$mockName: String = $anon.this.mock$special$mockName;
    override def createChannel[MaterializeChild, CP <: arteria.core.Protocol](protocol: CP)(handler: arteria.core.MessageChannelHandler[CP], context: CP#ChannelContext, materializeChild: MaterializeChild)(implicit materializeChildPickler: boopickle.Pickler[MaterializeChild]): arteria.core.MessageChannel[CP] = $anon.this.mock$createChannel$0.apply(protocol, handler, context, materializeChild, materializeChildPickler);
    override def send[A <: arteria.core.Message](message: A)(implicit ev: arteria.core.MessageWitness[A,suzaku.ui.UIProtocol.type]): Unit = $anon.this.mock$send$0.apply(message, ev);
    override def close(): Unit = $anon.this.mock$close$0.apply();
    override def receiveDrop(channelReader: arteria.core.ChannelReader): Unit = $anon.this.mock$receiveDrop$0.apply(channelReader);
    override def receive(channelReader: arteria.core.ChannelReader): Unit = $anon.this.mock$receive$0.apply(channelReader);
    override def closeChannel(channel: arteria.core.MessageChannelBase): Unit = $anon.this.mock$closeChannel$0.apply(channel);
    private[this] val mock$createChannel$0: org.scalamock.function.MockFunction5[CP,arteria.core.MessageChannelHandler[CP],CP#ChannelContext,MaterializeChild,boopickle.Pickler[MaterializeChild],arteria.core.MessageChannel[CP]] = new org.scalamock.function.MockFunction5[CP,arteria.core.MessageChannelHandler[CP],CP#ChannelContext,MaterializeChild,boopickle.Pickler[MaterializeChild],arteria.core.MessageChannel[CP]](UIManagerSpec.this._factory, scala.Symbol.apply(scala.Predef.augmentString("<%s> %s%s.%s%s").format($anon.this.mock$special$mockName, "MockUIChannel", "", "createChannel", "[MaterializeChild,CP]")))(util.this.Defaultable.default[arteria.core.MessageChannel[CP]]);
    <stable> <accessor> def mock$createChannel$0: org.scalamock.function.MockFunction5[CP,arteria.core.MessageChannelHandler[CP],CP#ChannelContext,MaterializeChild,boopickle.Pickler[MaterializeChild],arteria.core.MessageChannel[CP]] = $anon.this.mock$createChannel$0;
    private[this] val mock$send$0: org.scalamock.function.MockFunction2[A,arteria.core.MessageWitness[A,suzaku.ui.UIProtocol.type],Unit] = new org.scalamock.function.MockFunction2[A,arteria.core.MessageWitness[A,suzaku.ui.UIProtocol.type],Unit](UIManagerSpec.this._factory, scala.Symbol.apply(scala.Predef.augmentString("<%s> %s%s.%s%s").format($anon.this.mock$special$mockName, "MockUIChannel", "", "send", "[A]")))(util.this.Defaultable.defaultUnit);
    <stable> <accessor> def mock$send$0: org.scalamock.function.MockFunction2[A,arteria.core.MessageWitness[A,suzaku.ui.UIProtocol.type],Unit] = $anon.this.mock$send$0;
    private[this] val mock$close$0: org.scalamock.function.MockFunction0[Unit] = new org.scalamock.function.MockFunction0[Unit](UIManagerSpec.this._factory, scala.Symbol.apply(scala.Predef.augmentString("<%s> %s%s.%s%s").format($anon.this.mock$special$mockName, "MockUIChannel", "", "close", "")))(util.this.Defaultable.defaultUnit);
    <stable> <accessor> def mock$close$0: org.scalamock.function.MockFunction0[Unit] = $anon.this.mock$close$0;
    private[this] val mock$receiveDrop$0: org.scalamock.function.MockFunction1[arteria.core.ChannelReader,Unit] = new org.scalamock.function.MockFunction1[arteria.core.ChannelReader,Unit](UIManagerSpec.this._factory, scala.Symbol.apply(scala.Predef.augmentString("<%s> %s%s.%s%s").format($anon.this.mock$special$mockName, "MockUIChannel", "", "receiveDrop", "")))(util.this.Defaultable.defaultUnit);
    <stable> <accessor> def mock$receiveDrop$0: org.scalamock.function.MockFunction1[arteria.core.ChannelReader,Unit] = $anon.this.mock$receiveDrop$0;
    private[this] val mock$receive$0: org.scalamock.function.MockFunction1[arteria.core.ChannelReader,Unit] = new org.scalamock.function.MockFunction1[arteria.core.ChannelReader,Unit](UIManagerSpec.this._factory, scala.Symbol.apply(scala.Predef.augmentString("<%s> %s%s.%s%s").format($anon.this.mock$special$mockName, "MockUIChannel", "", "receive", "")))(util.this.Defaultable.defaultUnit);
    <stable> <accessor> def mock$receive$0: org.scalamock.function.MockFunction1[arteria.core.ChannelReader,Unit] = $anon.this.mock$receive$0;
    private[this] val mock$closeChannel$0: org.scalamock.function.MockFunction1[arteria.core.MessageChannelBase,Unit] = new org.scalamock.function.MockFunction1[arteria.core.MessageChannelBase,Unit](UIManagerSpec.this._factory, scala.Symbol.apply(scala.Predef.augmentString("<%s> %s%s.%s%s").format($anon.this.mock$special$mockName, "MockUIChannel", "", "closeChannel", "")))(util.this.Defaultable.defaultUnit);
    <stable> <accessor> def mock$closeChannel$0: org.scalamock.function.MockFunction1[arteria.core.MessageChannelBase,Unit] = $anon.this.mock$closeChannel$0
  };
  new $anon()
}.asInstanceOf[suzaku.ui.MockUIChannel]: suzaku.ui.MockUIChannel));
      ({
  import scala.scalajs.js;
  val fld$macro$1: scala.scalajs.js.PropertyDescriptor = scala.scalajs.js.Object.getOwnPropertyDescriptor(TestUIManager.this.uiChannel.asInstanceOf[scala.scalajs.js.Object], "mock$createChannel$0$2");
  if (scala.scalajs.js.`package`.isUndefined(fld$macro$1))
    throw new scala.`package`.IllegalArgumentException("Property \'mock$createChannel$0$2\' is not defined in \'".+(TestUIManager.this.uiChannel).+("\'. Available properties: ").+(js.this.Any.jsArrayOps[String](scala.scalajs.js.Object.getOwnPropertyNames(TestUIManager.this.uiChannel.asInstanceOf[scala.scalajs.js.Object])).mkString(",")))
  else
    ();
  fld$macro$1.value.asInstanceOf[org.scalamock.function.MockFunction5[suzaku.ui.TestProtocol.type,arteria.core.MessageChannelHandler[suzaku.ui.TestProtocol.type],suzaku.ui.TestProtocol.ChannelContext,Any,boopickle.Default.Pickler[Any],arteria.core.MessageChannel[suzaku.ui.TestProtocol.type]]]
}: org.scalamock.function.MockFunction5[suzaku.ui.TestProtocol.type,arteria.core.MessageChannelHandler[suzaku.ui.TestProtocol.type],suzaku.ui.TestProtocol.ChannelContext,Any,boopickle.Default.Pickler[Any],arteria.core.MessageChannel[suzaku.ui.TestProtocol.type]]).expects(UIManagerSpec.this.matcherBaseToMockParameter[suzaku.ui.TestProtocol.type](UIManagerSpec.this.*), UIManagerSpec.this.matcherBaseToMockParameter[arteria.core.MessageChannelHandler[suzaku.ui.TestProtocol.type]](UIManagerSpec.this.*), UIManagerSpec.this.matcherBaseToMockParameter[suzaku.ui.TestProtocol.ChannelContext](UIManagerSpec.this.*), UIManagerSpec.this.matcherBaseToMockParameter[Any](UIManagerSpec.this.*), UIManagerSpec.this.matcherBaseToMockParameter[boopickle.Default.Pickler[Any]](UIManagerSpec.this.*));
      def uic: arteria.core.MessageChannel[TestUIManager.this.ChannelProtocol] = TestUIManager.this.uiChannel
    };
    UIManagerSpec.this.convertToStringShouldWrapper("View manager child update")(org.scalactic.source.Position.apply("UIManagerSpec.scala", "Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at compile time to enable this feature.", 38), scalactic.this.Prettifier.default).should(UIManagerSpec.this.convertToWordSpecStringWrapper("update nothing").in({
      val vm: UIManagerSpec.this.TestUIManager = new UIManagerSpec.this.TestUIManager();
      val uiChannel: arteria.core.MessageChannel[vm.ChannelProtocol] = vm.uic;
      UIManagerSpec.this.convertToAnyShouldWrapper[arteria.core.MessageChannel[vm.ChannelProtocol]](uiChannel)(org.scalactic.source.Position.apply("UIManagerSpec.scala", "Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at compile time to enable this feature.", 43), scalactic.this.Prettifier.default).shouldNot(UIManagerSpec.this.be.apply(null))
    })(org.scalactic.source.Position.apply("UIManagerSpec.scala", "Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at compile time to enable this feature.", 39)))(UIManagerSpec.this.subjectRegistrationFunction)
  }
}
```
Note in particular:

* The macro-generated call that tries to access to `mock$createChannel$0$2`

```scala
val fld$macro$1: scala.scalajs.js.PropertyDescriptor = scala.scalajs.js.Object.getOwnPropertyDescriptor(TestUIManager.this.uiChannel.asInstanceOf[scala.scalajs.js.Object], "mock$createChannel$0$2");
```

* The definition of `mock$createChannel$0` in the class `$anon`
* The fact that `$anon` extends `suzaku.ui.MockUIChannel`, which extends `arteria.core.MessageChannel[suzaku.ui.UIProtocol.type]`, which ([from its source](https://github.com/suzaku-io/arteria/blob/17c442462ebbfc6063613954252c761b0efaa206/arteria-core/shared/src/main/scala/arteria/core/MessageChannel.scala#L109)) extends `Object` (`MessageChannelBase` being a trait, doesn't count).

Therefore, the class `$anon` is at level 3 (`Object` is 0, `MessageChannel` is 1, `MockUIChannel` is 2 and `$anon` is 3). Access to `mock$createChannel$0` should therefore be done as mock$createChannel$0$3` with a trailing `$3`.

I suspect the macro that derives the string `"mock$createChannel$0$2"` to erroneously count the number of superclasses of `$anon`. It may be that it fails to count `$anon` itself, precisely because it is anonymous?

Anyway, there's nothing Scala.js can do here. It needs to be fixed in ScalaMock.

**Comment by barkhorn** [comment] 2017-06-02 16:31
Thanks @sjrd , good detective work!

If I read it right, some of the contributed code for this was from the guts of Scala.JS, so maybe you are familiar with it.

I have commented out the second half of the line in `hasValueTypeArgs` and the count increases to 3, which makes the particular test in suzaku work.
Do you have a suggestion how to do this better, or is there a name mangling function of Scala.JS that we could reuse in ScalaMock?

```
  def mockedFunctionGetter[M: c.WeakTypeTag](c: Context)
                                            (obj: c.Tree, name: c.Name, targs: List[c.Type], actuals: List[c.universe.Type]): c.Expr[M] = {
    import c.universe._
    val utils = new MacroUtils[c.type](c)
    import utils._

    def hasValueTypeArgs(baseSymbol: Symbol, owner: Type): Boolean = {
      val baseType = owner.baseType(baseSymbol)
      baseType.typeArgs.nonEmpty // && baseType.typeArgs.forall(_ <:< typeOf[AnyVal])
    }

    // this somehow replicates postfix logic from scala-js, there have to be a better way
    def privateSuffix(owner: Tree): String = {
      val objectSymbol = c.typeOf[Object].typeSymbol

      val tpe = owner.tpe

      val baseNonInterfaceParentCount = tpe.baseClasses.count( symbol =>
        symbol != objectSymbol && (symbol.isClass && !symbol.asClass.isTrait)
      )

      // this was found in experiments and should be considered as magical cosmological constant
      val haveBaseClassWithValTypeArgs = tpe.typeSymbol.owner != null && tpe.typeSymbol.owner.isPackage &&
        tpe.baseClasses.exists(hasValueTypeArgs(_, owner.tpe))

      val idx = baseNonInterfaceParentCount + (if (haveBaseClassWithValTypeArgs) 1 else 0)
      "$" + idx.toString
    }
```

**Comment by sjrd** [comment] 2017-06-03 13:16
Wow, that looks like black magic.

What should be reproduced is the effect of [`encodeFieldSym`](https://github.com/scala-js/scala-js/blob/v0.6.17/compiler/src/main/scala/org/scalajs/core/compiler/JSEncoding.scala#L89) in the Scala.js compiler back-end. Note though that in Scala.js, this method is called after `mixin`, whereas macros are executed during `typer`, a long time before `mixin`. That means symbols might not (and will not) always be in the same shape. However, maybe for named fields that can be accessed through ScalaMock, it will always do the same thing. I don't think any scalac phase introduces new parent classes, so it should be fairly similar.

**Comment by barkhorn** [comment] 2017-06-04 13:50
Given that doc comment on `idSuffix` that seems to have its own quirks.
I might go with the quick fix which seems to solve the issue in the suzaku tests at least, but given the actual logic of that method i'm not sure if it will break something else in the process.
(I.e. why are AnyVal treated specially)

@sjrd  is there anything you could recommend for reading up on the compiler phases? I am a bit familiar with them but haven't looked at it in detail.

**Comment by sjrd** [comment] 2017-06-04 14:03
Ah, `AnyVal` is a good point. It would be relevant because `AnyVal` will be erased to `Object` during `erasure`, given
```scala
class Foo(val x: Int) extends AnyVal
```
at `typer`, you observe `Foo extends AnyVal extends Any`. And somehow at `typer`, `AnyVal` and `Any` both have `isTrait = false` (although we might expect `Any` to have `isTrait = true`). So at `typer`, `Foo` appears to be at level 2 (`Any` is 0, `AnyVal` is 1, so `Foo` is 2). However, after `erasure`, we see `Foo extends Object`, period. That means that eventually `Foo` is in fact at level 1.

So yes, `AnyVal` *itself* should be excluded from the count, because of the peculiarity of its erasure.

I'm not sure what a good quick-ish resource would be to read on the phases. You could try the Appendix of [my master's thesis](https://www.info.ucl.ac.be/~pvr/MemoireSebastienDoeraene.pdf), which gives a quick overview of each phase as well as pointers to further documentation. It's a bit old, though (2011).

**Comment by barkhorn** [comment] 2017-06-04 14:07
Ah the joys of erasure. It's a recurring pinch point with macros :)

Thanks for the links, will have a browse through them.

**Comment by sjrd** [comment] 2017-06-10 04:48
Closing here since [a fix](https://github.com/paulbutcher/ScalaMock/commit/1e84ffe8551dbdb97ed8584d93e960eb1668fca4) seems to have been merged into ScalaMock.

**Closed by sjrd** 2017-06-10 04:48 UTC
