### ISSUE TITLE
Export classpath dependencies as modules

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2833] opened 2017-03-25 00:17 UTC
#### Problem summary:
1) `fastOptJS` (esp. from an incremental compilation perspective) is very slow for large projects.
2) Bundlers like webpack are unacceptable slow at handling huge `-fastopt.js` files. For example, ignoring other processing, it takes webpack 46 seconds on a 3.40GHz i7 just to parse a 17.7MB file which is just one of a number of Scala.JS modules in my multi-module project.
3) When bundling a multi-module Scala.JS app, lots of duplicate code goes into each bundle. Each bundle becomes needlessly large.

#### Solution Idea:
When emitting modules, instead of emitting a single JS file/module, Scala.JS could emit separate modules for each classpath dependency and one just for the source that requires the rest.

For example, if a project depends on Scalaz and nothing else, the output could look like this:
```
.../target/scala-2.12/whatever:

- scala-2.12.1-fastopt.js

- scalaz-core-7.2.9-fastopt.js // require('./scala-2.12.1-fastopt.js')

- myproject-fastopt.js         // require('./scala-2.12.1-fastopt.js')
                               // require('./scalaz-core-7.2.9-fastopt.js')
```

This would...
* reduce incremental `fastOptJS` time because the classpath dependency modules would only need be generated once after a `clean`, and the scope of data that need be processed on each incremental compilation would be considerably lessened.
* speed up bundlers like webpack because most have per-module caching. Lots of modules is the problem the JS world optimises for, not few modules of enormous size.
* in a multi-module project, the SJS modules would `require` the same dependency modules which allows webpack to extract and generate a new module with all code shared between each SJS project. For example, if both SJS modules use `Set` and `List` from Scala stdlib that's already a (probably considerably sized) chunk of code that could be made reusable by webpack.
* close out #2681

Related: #2175, #1787

**Comment by japgolly** [comment] 2017-03-25 00:32
Oh and the same would go for shared SBT modules. If SBT module `B` depends on SBT module `B` then I would imagine it working like this:

```
a/target/scala-2.12/a-fastopt.js

b/target/scala-2.12/b-fastopt.js // require('../../../../a/target/scala-2.12/a-fastopt.js')
```

**Comment by ramnivas** [comment] 2017-03-25 02:52
As mentioned in #2681, our experience matches that of @japgolly.

I wonder, though, if the "one classpath-dependency to one module" idea is taken to its logical extreme, it will lead to a "one class to one module" scheme. Would it be possible to:
1. Output one .js file per class.
2. Automatically add require statements for each referred class' .js file.

Now when a scala source file is touched, only file corresponding to the classes/object in it will be touched and make the bundlers job really easy.

Furthermore, this will make using code splitting to fetch/parse only the absolutely needed file during the initial loading really easy (basically making it as capable as that in the JS world).

**Comment by sjrd** [comment] 2017-03-25 09:46
Why is this issue not a discussion *on* #2681?

Anyway, I agree that we need something like this (i.e., splitting the .js produced by Scala.js in several modules), but I do not think restricting it to classpath dependencies is needed/desirable. It should be up to some link-time option to decide on a strategy.

And then anyway, we still need to *link* the whole classpath as one unit, even though it can be split afterwards (after optimizations and such). But then again we're back to square #2681, so ...

> Output one .js file per class.

You would kill yourself with the sheer *number* of such .js files. File systems (especially on Windows) are not good at dealing with zillions of small files. We were there in Scala.js 0.x for some small value of x, and it was a nightmare.

> Now when a scala source file is touched, only file corresponding to the classes/object in it will be touched and make the bundlers job really easy.

That's not even true. Due to whole-program linking, changes in one source file can affect the .js produced for any other arbitrary class.

**Comment by japgolly** [comment] 2017-03-25 10:18
> we still need to link the whole classpath as one unit ...  Due to whole-program linking, changes in one source file can affect the .js produced for any other arbitrary class.

When you're exporting modules then why is whole-program linking needed or even desired? You're generating something to import somewhere else; it's known to not be the final step nor have a view of the whole-program. That's the responsibility of whichever bundler-like tool a user chooses to use, (and it has to exist cos *something* needs to convert it all to IIFE).

It would be a change to Scala.JS to be sure, but wouldn't it make sense to just export everything according to its FQCN? Eg. the Scala module would export `scala_collection_immutable_List`, `scala_collection_immutable_Nil`, etc. and then downstream modules would simply have
```js
import {scala_collection_immutable_Nil /* ... */ } from './scala-2.12.1.js'
```
I don't know the complications that Scala.JS deals with internally make it all possible but my point is, if there is some way to make it possible to make it more modular like this and get rid of whole-program-anything when exporting modules, then that will be a huge win.

> It should be up to some link-time option to decide on a strategy.

Sure but one the biggest problems and goals here is speed. The less the linker has to do incrementally, the better; and the more previously created modules that are left untouched after incrementally linking, the better.

> Why is this issue not a discussion on #2681?

My thinking was that this pertains to, and solves more issues than just that issue.

**Comment by sjrd** [comment] 2017-03-25 10:42
> I don't know the complications that Scala.JS deals with internally make it all possible

Well that's the problem, right? It doesn't. Scala.js' linking requires to see the whole program. And no, I'm not even talking about optimizations.

**Comment by sjrd** [comment] 2017-03-25 10:45
> Sure but one the biggest problems and goals here is speed. The less the linker has to do incrementally, the better; and the more previously created modules that are left untouched after incrementally linking, the better.

This is not an issue for what I'm proposing. The linker itself is already incremental, mostly. The most time-consuming part on an incremental run is the Emitter, which actually writes down the .js file. With link-time, post-optimizations code splitting, the Emitter can only re-emit the .js files for which something in their content has changed. This brings all the benefits you are asking for, and is actually compatible with the whole-program linking of Scala.js.

**Comment by ramnivas** [comment] 2017-03-25 19:00
> You would kill yourself with the sheer number of such .js files. File systems (especially on Windows) are not good at dealing with zillions of small files. We were there in Scala.js 0.x for some small value of x, and it was a nightmare.

I guess a good compromise could be one module per external classpath entry and one module per type for the current project or something along these lines (assuming the next point can be addressed in the first place).

> That's not even true. Due to whole-program linking, changes in one source file can affect the .js produced for any other arbitrary class.

To what extent a change in one source file affects the other .js produced? What governs how the .js code for other types is affected (inheritance relationship? contains relationship? reference?). If it is truly arbitrary (generated names for example), could it be made less so by making type->js mapping more stable (during development)?

Basically, if a source code change could be limited to a smaller set of js changes, then it will help this issue. If not, it is unlikely that any solution will work (producing one giant -fastopt.js or many small .js files will not help Webpack's parser).

> The linker itself is already incremental, mostly. The most time-consuming part on an incremental run is the Emitter, which actually writes down the .js file. 

Just to be sure: I don't think the slowness of producing -fastopt.js is really a big issue. While any improvement is most welcome, in our project producing -fastopt.js takes about 4-5 seconds (on a fairly decent Macbook Pro) then followed by about 45 seconds of Webpack. These 45 seconds is a real productivity killer. When we switched to use the commonjs support in scala.js, the only thing that helped was to configure Webpack to not parse -fastopt.js (https://webpack.github.io/docs/configuration.html#module-noparse), but that also means we cannot use any `JSImport` from Scala sources.

**Comment by sjrd** [comment] 2017-03-25 19:22
> To what extent a change in one source file affects the other .js produced?

Because of (transitive) inlining, it is impossible to *predict*: virtually anything can be affected. It is possible to *track*, though, which is what the incremental optimizer and emitter do. It is therefore possible for the emitter to track which portions need to be re-emitted, should we decompose the output in various .js files. In practice, a change to a source file will not affect the entire world; it will only affect a limited amount of callers to the function that are inlined (and a few other things, sometimes).

> Just to be sure: I don't think the slowness of producing -fastopt.js is really a big issue.

I understand. My point is: if the emitter decides not to re-emit certain files, Webpack won't have to re-parse them.

**Comment by ramnivas** [comment] 2017-03-25 19:33
Thanks for the clarification.

> Because of (transitive) inlining, it is impossible to predict

Is the (transitive) inlining a core requirement or could it be turned off (say with a flag). Of course, if the set of output files could be limited through tracking, that may be sufficient to alleviate the current problem is using the commonjs support.

**Comment by sjrd** [comment] 2017-03-25 19:42
> Is the (transitive) inlining a core requirement or could it be turned off (say with a flag).

```scala
scalaJSOptimizerOptions ~= { _.withDisableOptimizer(true) }
```
but you shouldn't need to do that to get reasonable incremental emitting.

Focusing on dumbing down the linker/optimizer is really the wrong strategy, here. Let it do its job, it does it well, and incrementally. The *only* issue is that we need to split the .js files at the very end, and not touch anything else in the pipeline.

**Comment by gzm0** [comment] 2017-03-25 19:52
> Output one .js file per class.
> You would kill yourself with the sheer number of such .js files. 

Doesn't JVM land do exactly that and not blow up? Maybe Webpack specifically is unhappy about that, but that's another story.

**Comment by sjrd** [comment] 2017-03-25 19:53
> Doesn't JVM land do exactly that and not blow up?

No it bundles zillions of .class files in one .jar file. From the fs point of view, it's one big file, not zillions of small files.

**Comment by ramnivas** [comment] 2017-03-25 20:04
> No it bundles zillions of .class files in one .jar file.

So I guess one .js per jar and suitable numbers of .js files per .scala will mirror the JVM world and might work fine from the filesystem's point of view.

**Comment by japgolly** [comment] 2017-03-25 20:55
> The linker itself is already incremental, mostly. The most time-consuming part on an incremental run is the Emitter

That doesn't seem to be the case with my code. I ran `fastOptJS` once, added a newline to a file and re-ran `fastOptJS`. In my case Linker > Emitter.

```
[debug] Linker: Compute reachability: 1313952 us
[debug] Linker: Assemble LinkedClasses: 145043 us
[debug] Basic Linking: 1468947 us
[debug] Inc. optimizer: Batch mode: false
[debug] Inc. optimizer: Incremental part: 162886 us
[debug] Inc. optimizer: Optimizing 526 methods.
[debug] Inc. optimizer: Optimizer part: 52644 us
[debug] Inc. optimizer: 262365 us
[debug] Refiner: Compute reachability: 365210 us
[debug] Refiner: Assemble LinkedClasses: 26046 us
[debug] Refiner: 391385 us
[debug] Emitter: Class tree cache stats: reused: 3846 -- invalidated: 62
[debug] Emitter: Method tree cache stats: resued: 22952 -- invalidated: 294
[debug] Emitter (write output): 467787 us
[debug] Global IR cache stats: reused: 3734 -- invalidated: 84 -- trees read: 66
```

> we need to split the .js files at the very end, and not touch anything else in the pipeline.

If by "pipeline" you mean previously emitted JS files, then awesome, that's the gist of the goal here. 

There's still another problem which my proposal would address, that we're not talking about so much. That is: reuse in the multi-module view. When I proposed that SJS emit JS modules for classpath dependencies one of the hopes was that the classpath modules emitted by each module (like `scala-2.12.1.js`) would be exactly the same and reusable, just like `.jar` files. Then when I run webpack over the output of all of my SJS top-level modules, they'd all point to the identical `scala-2.12.1.js` files (which I'd unify), just different imports, which would allow webpack to perform whole-webapp optimisation and provide smarter shared bundles (eg. 40% of `scala-2.12.1.js` might be shared by all apps/entrypoints and could be extracted and cached separately). In your vision, @sjrd, where we can instruct the linker to emit multiple modules, will it be able to produce dependency modules that we can trust to be identical across multiple SBT modules? `scala-2.12.1.js` should never change, `scalaz-7.2.9_2.12.js` should never change. They should only ever need be emitted once and from then on should be reusable.

**Comment by sjrd** [comment] 2017-03-25 21:11
> If by "pipeline" you mean previously emitted JS files, then awesome, that's the gist of the goal here.

I actually meant the linking pipeline in that sentence: reachability analysis, optimizer, refiner, and IR->JS AST. But elsewhere when I talk about "the Emitter can only re-emit the .js files for which something in their content has changed", that's what I mean.

> In your vision, @sjrd, where we can instruct the linker to emit multiple modules, will it be able to produce dependency modules that we can trust to be identical across multiple SBT modules?

No, it won't be possible. But you shouldn't have to. You should have only one leaf sbt project that gathers everything Scala.js. Then, specifying how to split that into ES modules, you have the opportunity to put the various conceptual leaf modules in separate ES modules. Finally, selecting those as separate entry points for Webpack will do what you want.

> scala-2.12.1.js should never change, scalaz-7.2.9_2.12.js should never change. They should only ever need be emitted once and from then on should be reusable.

I've seen this argument many times (in other discussions with other people), and answered many times as well: that won't happen. The link-time behavior *needs the whole-program*, and that means that scala-2.12.1.js will not be same for two Scala.js applications.

This is a fundamental design choice that was made years ago, and which will not change. It is a trade-off. Other compile-to-JS languages make a different choice (e.g., BuckleScript). Both designs have their advantages and disadvantages. In Scala.js we chose the whole-program approach.

**Comment by japgolly** [comment] 2017-04-30 00:31
> that won't happen. …  scala-2.12.1.js will not be same for two Scala.js applications.
> This is a fundamental design choice that was made years ago, and which will not change. It is a trade-off. 

Fair enough. I understand the pain of trade-offs and while I don't know the details of this particular situation, Scala.JS has been consistently awesome and eclipsed competitors in the early days and it seems that whatever you purchased with your trade-off choices has been highly advantageous. I'll stop barking up that tree then. It was a nice vision but oh well.

> You should have only one leaf sbt project that gathers everything Scala.js. Then, specifying how to split that into ES modules, you have the opportunity to put the various conceptual leaf modules in separate ES modules. Finally, selecting those as separate entry points for Webpack will do what you want.

I didn't think of that. Conceptually that would be fine, solve all the problems and support all the things. My only concern with that is performance. Performance is a really big deal when we're talking about processing between saving a source file, and tests running or the browser refreshing. I worry that:
1) Scala.JS already takes a long time to Scala→<magic>→JS for large projects. Will this get even slower?
2) An umbrella project would mean that in order to produce or compile a single module, all other modules would need to be compiled and processed.

**Comment by ubolonton** [comment] 2017-07-03 17:03
What are the gains/losses involved in the "link-time behavior needs the whole program" trade-off? Perhaps there are some existing notes/discussions around that from which we can learn more?

**Comment by ngbinh** [comment] 2017-08-12 20:18
@sjrd 
> No, it won't be possible. But you shouldn't have to. You should have only one leaf sbt project that gathers everything Scala.js. Then, specifying how to split that into ES modules, you have the opportunity to put the various conceptual leaf modules in separate ES modules. Finally, selecting those as separate entry points for Webpack will do what you want.

Is it something possible now?

**Comment by sjrd** [comment] 2017-08-12 22:50
No. Has there been any new development that suggests it would?

**Comment by Mark-L6n** [comment] 2017-09-24 19:00
Don't know if this will solve your problem, but in a recent project, extremely slow webpack behavior was caused by `babel-loader` automatically processing everything not explicitly excluded.  With that fixed there was no delay.  We put the scala.js files in a `\static` directory (outside the `\src` tree), and in the webpack configuration `babel-loader` section, configured `\static` to not be transpiled. 


``` js
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: projectRoot,
        exclude: /(node_modules|static)/
      },
```

**Comment by ramnivas** [comment] 2017-09-24 19:25
@Mark-L6n I guess you were referring to the slowness I mentioned. We don't have `babel-loader` in this project. I isolated it to webpack parsing the `-fastopt.js`, so setting `noParse` helped, but at the cost of not able to use `@JSImport` in Scala files.

**Comment by gzm0** [comment] 2020-03-10 11:47
I'm going to close this as dupe of #2681 since they have the same end goal.

**Closed by gzm0** 2020-03-10 11:47 UTC
Labels: enhancement
