### ISSUE TITLE
Inherit static members of @ScalaJSDefined classes in ES5.1 output mode

### ISSUE THREAD

**Issue by chandu0101** [scala-js/scala-js#2771] opened 2017-02-12 01:04 UTC
```scala
@ScalaJSDefined
class BaseComponent extends js.Object 

object BaseComponent {
   @JSExportStatic
    var x: Int = 4
}

@ScalaJSDefined
class Component extends BaseComponent 

val ctor = js. constructorOf[Component] 

println(ctor.x)

```

**Comment by gzm0** [comment] 2017-02-13 11:49
Duplicate of #1900?

**Comment by chandu0101** [comment] 2017-02-13 14:47
>Duplicate of #1900?

yeah :) 

from #2702  

@sjrd - 

`When emitting in ES5.1 output mode, no. At least this proposal does not mention anything in favor or against it. We might have to adjust our ES5.1 output so that it sets the prototype of class values, but it is actually quite orthogonal to this proposal.`

I have a use case for this one in my app, is it possible copy superclass static fields  ?

**Comment by sjrd** [comment] 2017-02-13 15:13
My concerns from https://github.com/scala-js/scala-js/issues/1900#issuecomment-139850893 still stand, though: how do we deal with the fact that ES5.1 simply does not have any mechanism to implement this?

**Comment by chandu0101** [comment] 2017-02-13 21:18
cool ok, I'll try different solution for my problem, thanks for discussion  :)

**Comment by sjrd** [comment] 2017-02-13 21:38
I mean, I'm open to discussion. I would like to get this to work. If someone comes up with a reasonable way to deal with this issue, I'm all for it.

**Comment by chandu0101** [comment] 2017-02-13 21:40
oh ok , i'll reopen this ...

**Closed** 2019-05-22 09:03 UTC
Labels: enhancement
