### ISSUE TITLE
@js.native cannot be applied to package objects

### ISSUE THREAD

**Issue by benjaminjackman** [scala-js/scala-js#1892] opened 2015-08-31 14:21 UTC

**Comment by sjrd** [comment] 2015-08-31 14:26
In general, scalac still prevents to apply annotations on package objects, unfortunately. We need to find a workaround for native package objects. Maybe a magic
```scala
@js.native
trait NativePackageObject extends js.Any
```
which is only allowed to be mixed in package objects, and which has the same meaning as `@js.native` in those cases.

Ugly, but we need *something*.

**Comment by lihaoyi** [comment] 2015-08-31 14:39
Could we make it `with js.native` instead?

**Comment by sjrd** [comment] 2015-08-31 14:52
No, that's technically impossible, because annotations need to be classes and they must `extends scala.annotation.StaticAnnotation`. That's at least two reasons why it cannot also be a supertrait of a native package object.

**Comment by lihaoyi** [comment] 2015-08-31 15:02
Oh I was more thinking having _everyone_ extend `js.native` instead of using `@js.native` as an annotation. So `js.native` wouldn't be an annotation any more, and be purely a marker trait like `js.Object` or `js.GlobalScope` already are. That means it won't be a class and won't need to extend StaticAnnotation.

**Comment by sjrd** [comment] 2015-08-31 15:04
That doesn't make any sense, because you would need to re-mixin `js.native` in a native class extending a native class (or a native trait, or whatever):
```scala
class HTMLElement extends js.Object with js.native { ... }

class HTMLImageElement extends HTMLElement with js.native { ... } // WAT?
```

`js.Object` is not a marker trait: it is the `Object` native JS class.
`js.GlobalScope` is a marker trait, but since it can only be mixed in an `object`, the multiple re-mixin along the inheritance chain doesn't pop up. It would be the same for `NativePackageObject`.

**Comment by benjaminjackman** [comment] 2015-08-31 15:06
Hmm I am wondering if maybe it would be easier / more straightforward if we had `js.NativeObject` or `js.FacadeObject` that get's mixed in instead of the song and dance with `js.native` + `extends js.Object`

**Comment by sjrd** [comment] 2015-08-31 15:07
No, same objection as with `with js.native` in my earlier comment.

**Comment by sjrd** [comment] 2015-08-31 15:09
Being native or not is *not* an inherited property! A native class can extend a non-native class and vice versa. So using marker traits for this property is fundamentally *wrong* and cannot make any sense whatsoever.

Annotations are the right tool for this. It's just that we have to work around a limitation about package objects.

**Comment by benjaminjackman** [comment] 2015-08-31 15:11
Is there an open bug for no annotations on package objects? because that is really the root of issue and something that should be fixed in scalac.

**Comment by lihaoyi** [comment] 2015-08-31 15:13
@benjaminjackman you probably want https://issues.scala-lang.org/browse/SI-3600. 5 years and still going strong!

**Comment by gzm0** [comment] 2015-09-03 16:35
I proposed some change for this quite a while ago... :(

**Comment by sjrd** [comment] 2015-09-13 09:04
Can't we just deprecate the fact that package objects can be js.Any's altogether? There are at least 2 reasons to do so. One is practical, the other is foundational.

On the practical side, [the experience with scala-js-dom](https://github.com/scala-js/scala-js-dom/issues/121) shows that the approach has practical problems. If your package object is a js.Any, you simply *cannot* add any Scala-defined stuff in it. Implicit pimp does not work for package objects. If, however, the package object is a Scala object, nothing prevents you from declaring forward `val`s (or `def`s or `lazy val`s) to (native or not) JS objects). We had [already switched](https://github.com/scala-js/scala-js/commit/e006ec941c9434532d9b732b548d592abb9dd214) the `js` package object from a native JS global scope object to a Scala object in 0.6.0 precisely for this reason.

On the foundational side, if we consider that all classes and objects in a package are logically owned by the package object, we have inconsistencies because we can declare a Scala class in the package, but not in the package object. Not cool. Of course, if the package object is a Scala object, we still can't declare a native JS class/object in the package object though we can declare it in the package. But that could be fixed at the spec level. (We can't "fix the spec" for the other case because of things like implicit classes, which desugar into having a def in the owning object.)

Does anyone actually use package objects extending js.Any?

**Comment by gzm0** [comment] 2015-09-13 10:15
The only valid use case that comes to mind is JS libraries that have top level methods. These would have to be implemented as forwarders which can be a lot of duplication.

**Comment by sjrd** [comment] 2016-01-09 11:28
I propose to close this as "as designed" / "won't fix".

JS libraries do not expose top-level stuff anymore, not really. They tend to expose one top-level object containing functions and classes instead. So in practice there should be very little duplication (just the definition of the top-level object, which is likely going to be an `object` anyway).

**Comment by mseddon** [comment] 2016-01-09 20:33
Agreed. It might even be worth saying 'don't do this' in the docs and emit a warning when someone tries this, since it's not immediately obvious this is going to cause pain later.

**Comment by sjrd** [comment] 2016-01-09 20:35
> It might even be worth saying 'don't do this' in the docs

Absolutely.

> and emit a warning when someone tries this

Well, it does. Although arguably the warning is unclear because it tells you to add `@js.native`, but then you try to add it and you receive a parse error ...

**Closed** 2016-01-11 17:50 UTC
Labels: bug
