### ISSUE TITLE
jsDependencies on windows not allowing a sub-directory JS dependency to be referenced

### ISSUE THREAD

**Issue by PhilAndrew** [scala-js/scala-js#1576] opened 2015-03-31 08:25 UTC
jsDependencies +=
  ProvidedJS / "moment-recur/moment-recur.min.js"

When I
```sbt publishLocal``` 

Then open the jar file to look at it at
C:\Users\philip\.ivy2\local\io.github.widok\scala-js-moment-recur_sjs0.6_2.11\0.1.0-SNAPSHOT\jars
 it has
{"libDeps":[{"resourceName":"moment-with-locales.min.js"},{"resourceName":"moment-recur\/moment-recur.min.js"}],"origin":{"configuration":"compile","moduleName":"root"}}

So I think the moment-recur\/moment-recur.min.js is a problem because of the \/

When I tried to import this with SBT it fails with an error message.

However, if I place the moment-recur.min.js in the resources directory NOT in a sub-directory then its fine and works.

**Comment by sjrd** [comment] 2015-03-31 08:27
Thanks.

**Comment by sjrd** [comment] 2015-04-26 14:53
Hi back,

The encoding with `\/` seems to be normal and expected, actually. It also deserializes correctly.

> When I tried to import this with SBT it fails with an error message.

Could you elaborate? I fail to trigger any kind of problem with this.

**Comment by sjrd** [comment] 2015-05-01 13:25
Ping @PhilAndrew

**Comment by sjrd** [comment] 2015-06-14 10:28
Closing because I cannot reproduce, and because of the lack of follow-up.

**Closed by sjrd** 2015-06-14 10:28 UTC
Labels: bug
