### ISSUE TITLE
Pattern.compile("\\p{L}") not working in Scala.js

### ISSUE THREAD

**Issue by paullepoulpe** [scala-js/scala-js#2082] opened 2015-12-02 15:09 UTC
```
/* True on the JVM but false in Scala.js */
java.util.regex.Pattern.compile("\\p{L}").matcher("M").matches()
```

**Comment by sjrd** [comment] 2015-12-02 15:12
Duplicate of #1201.

**Closed by sjrd** 2015-12-02 15:12 UTC
