### ISSUE TITLE
memory consumption with 0.6.1 makes builds to fail

### ISSUE THREAD

**Issue by betehess** [scala-js/scala-js#1525] opened 2015-03-10 02:51 UTC
[banana-rdf got switched to 0.6.1](https://github.com/w3c/banana-rdf/commit/a433553748f034710107e06e9911608a34f0b090) with @InTheNow's sbt-scalajs 0.6.1. All the subsequent builds using scala-js 0.6.1 failed.

Errors include:

* `java.lang.OutOfMemoryError: PermGen space`
* `org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed`
* ```
java.util.concurrent.TimeoutException: Timeout expired
	at org.scalajs.jsenv.rhino.RhinoJSEnv$Channel.recvJVM(RhinoJSEnv.scala:463)```
(local builds using the same memory constraints than for travis-ci)

Forcing banana-rdf to use sbt-scalajs 0.6.0 fixed the problem.

You can see the builds at https://travis-ci.org/w3c/banana-rdf/builds .

Note that we already had similar (but different (but probably related)) issues with travis-ci as we are not able to enable `FastOptStage` for the entire build (see https://github.com/w3c/banana-rdf/commit/f6a01302e1256d84f326aa78b97c24b48ec0058c). So I do not know if this is a regression or something else, but I really tried many options before getting that one to work.

**Comment by sjrd** [comment] 2015-03-10 14:00
I can't load the banana-rdf project. I get this, just running sbt:
```
[info] Compiling 3 Scala sources to /localhome/doeraene/projects/banana-rdf/project/target/scala-2.10/sbt-0.13/classes...
java.lang.ClassCastException: Cannot cast com.typesafe.sbt.SbtPgp$ to sbt.AutoPlugin
        at java.lang.Class.cast(Class.java:3176)
        at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
        at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
        at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream.foreach(Stream.scala:548)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
        at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
        at scala.collection.TraversableLike$class.to(TraversableLike.scala:629)
        at scala.collection.AbstractTraversable.to(Traversable.scala:105)
        at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257)
        at scala.collection.AbstractTraversable.toList(Traversable.scala:105)
        at scala.collection.immutable.List.$plus$plus(List.scala:193)
        at sbt.PluginDiscovery$.discoverAll(PluginDiscovery.scala:38)
        at sbt.Load$.loadPlugins(Load.scala:833)
        at sbt.Load$.loadPluginDefinition(Load.scala:790)
        at sbt.Load$.buildPlugins(Load.scala:785)
        at sbt.Load$.plugins(Load.scala:773)
        at sbt.Load$.loadUnit(Load.scala:431)
        at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
        at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
        at sbt.BuildLoader.apply(BuildLoader.scala:140)
        at sbt.Load$.loadAll(Load.scala:334)
        at sbt.Load$.loadURI(Load.scala:289)
        at sbt.Load$.load(Load.scala:285)
        at sbt.Load$.load(Load.scala:276)
        at sbt.Load$.apply(Load.scala:130)
        at sbt.Load$.defaultLoad(Load.scala:36)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$.process(Command.scala:92)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ClassCastException: Cannot cast com.typesafe.sbt.SbtPgp$ to sbt.AutoPlugin
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```
Do you think you could `git bisect` the commit in Scala.js that would have caused this additional memory consumption?

**Comment by betehess** [comment] 2015-03-10 14:45
> I can't load the banana-rdf project. I get this, just running sbt:

Looks like it's either a dependency issue with sbt (then wiping your .ivy2 folder might solve it), or you already have sbt-gpg defined globally.

> Do you think you could git bisect the commit in Scala.js that would have caused this additional memory consumption?

I won't have time in the near future (Scaladays then moving to California for a new job). Maybe I will see you at Scaladays?

**Comment by sjrd** [comment] 2015-03-10 14:46
I won't be at ScalaDays SF, but I'll be in Amsterdam.

**Comment by gzm0** [comment] 2015-03-13 23:23
@betehess: I'll be at Scaladays. Hope to see you there.

**Comment by gzm0** [comment] 2015-03-19 18:34
After investigations with @betehess, we found several issues:

- Rhino filling up PermGen space
- Node.js timeouts being too low (#1546)

The latter was most likely caused by the way we launch slaves in the test interface. Using CPU count to estimate the number of JS VMs does not work very well in a kernel-virtualized environment like docker, which Travis uses IIUC. It is unclear to me how and whether this needs addressing.

**Comment by gzm0** [comment] 2015-03-20 16:55
@betehess could you please try the workaround in #1556 and confirm this fixes your issues?

**Comment by gzm0** [comment] 2015-03-20 17:02
@InTheNow has just confirmed (on gitter) that the workaround in #1556 fixes this issue.

**Comment by gzm0** [comment] 2015-03-23 15:43
@betehess can we close this?

**Comment by betehess** [comment] 2015-03-23 16:26
I am still off the grid until tomorrow. I am happy to close this now if
@InTheNow is happy with his experiments.

**Comment by InTheNow** [comment] 2015-03-23 17:55
@gzm0  The workaround works, you have an issue for further ideas and I agree with your analysis.

:+1: from me to close this issue

**Closed** 2015-03-23 17:57 UTC

**Comment by antonkulaga** [comment] 2015-03-24 10:42
dependencyOverrides += "org.scala-js" %% "scalajs-sbt-test-adapter" % "0.6.0" workaround does not help me

**Comment by gzm0** [comment] 2015-03-24 17:54
Did you add it in `project/build.sbt`? (not in `project/Build.scala` or `build.sbt`)

**Comment by gzm0** [comment] 2015-03-24 17:54
It is an override for the sbt-plugin's dependencies, not your project's.

**Comment by antonkulaga** [comment] 2015-03-24 18:01
I added it to project/plugins.sbt

**Comment by gzm0** [comment] 2015-03-24 18:31
Ok. That should be fine. Could you give us some debug information? Apparently you are facing a different problem that banana-rdf, since they report that the dependency override works for them.

**Comment by antonkulaga** [comment] 2015-04-05 10:36
>? Apparently you are facing a different problem that banana-rdf, since they report that the dependency override works for them.

I have the same problem with b-rdf  I am really surprised that @InTheNow managed to successfully run tests with "org.scala-js" %% "scalajs-sbt-test-adapter" % "0.6.0" hack

**Comment by InTheNow** [comment] 2015-04-05 10:48
the tests were run on travis - see https://travis-ci.org/w3c/banana-rdf/builds/55200281 and related PR for code changes
