### ISSUE TITLE
Shared modules/progressive apps support

### ISSUE THREAD

**Issue by scf37** [scala-js/scala-js#2681] opened 2016-12-09 15:29 UTC
Currently ScalaJS is not that suitable for mobile development because of monolithic `xxx-opt.js`.
While loading hundreds Ks of javascript on typing site URL is perfectly appropriate for many situations (B2B, desktop), mobile users won't be such as happy given their slow connections.

Google Closure Compiler allows splitting codebase into multiple modules  via `--module` and `--js` arguments:
http://stackoverflow.com/questions/10395810/how-do-i-split-my-javascript-into-modules-using-googles-closure-compiler/10401030#10401030

It could be really great if ScalaJS allow to split generated javascript to multiple modules to avoid waiting for too long for first page to show. For example:
- common (scala.* and libraries)
- landing page
- main page
- settings
- etc etc etc.

Splitting could be done by packages, by subprojects, by deps etc.

**Comment by sjrd** [comment] 2016-12-12 13:25
I have the feeling that we already have this idea filed somewhere, but I can't find it. Does someone remember where we discussed this before?

**Comment by glmars** [comment] 2016-12-12 14:42
This one: #1787 ?

**Comment by sjrd** [comment] 2016-12-13 10:47
@scf37 Some part of that discussion was relevant, indeed, but not all of it. The present issue is a neat summary of one particular core feature, so I'll keep it. The other features necessary for #1787 turned out to be already implemented. So I closed #1787 in favor of the present issue + these other implemented features.

**Comment by ramnivas** [comment] 2017-03-11 20:09
One more concern (besides the desired quick loading of the first page) is that using Scala.js commonjs support with tools such as Webpack (which we use currently) is basically unusable during development. When implemented with typical settings (enable source maps, for example), each time (even with a tiny change), our development builds take 40-45 seconds (3-5 second for the scala.js part and the rest for the Webpack part). This is mostly due to Webpack parsing a huge -fastopt.js for every change. We got away, for now,  using the noParse option set for -fastopt.js, but that makes us lose the sourcemaps support. We could try scalajs-bundler, but I highly doubt if it is going to do any better, since at the end of the day, it too runs Webpack.

These tools are optimized for the situations where only few small source files (js, css, etc) change at a time during development. Scala.js in its current form doesn't meet this assumption (it spits out a large "source file").

This feature could the use of promote import/export of many small modules within an app. Then each change should touch only the relevant -fastopt.js file and lower the parsing load on Webpack and other bundler tools.

**Comment by cuzfrog** [comment] 2017-04-14 16:50
Agreed. @ramnivas  scalajs-bundler seems like a workaround, not a solution. 

Scala.js' is fast despite single large bundle file, nevertheless, it throws the problem to npm/webpack, which have no idea how to deal with the giant, and they won't.

Modules by `@JsImport` should not be bundled, at first, this is work for webpack alike.

Is it possible to split the `*opt.js` after it's been emitted, but before webpack intervenes? If yes, how?

**Comment by aappddeevv** [comment] 2017-04-21 13:09
I just hit this issue. I need to develop a library on top of many other node.js npm modules and other js libraries and have my library usable by potentially other js libraries (which we can do) as well as other scalajs libraries also 1) deployed through npm and then 2) bundled into clever bundles for web deployment. I think the current output model would replicate the scalajs standard libraries multiple times inside the module. If I could control scalajs output a bit more, without wrapping in the std lib, then I could use webpack and npm to manage all the other assembly parts.

**Comment by ubolonton** [comment] 2017-07-03 16:18
This would probably make it much easier to create a hot code patching tool similar to https://github.com/bhauman/lein-figwheel.

**Comment by sjrd** [comment] 2017-07-03 16:24
@ubolonton No it wouldn't. You still need to link the entire app at once, and a change in one part of the code can affect the other "modules". This issue is only about the possibility to decompose the one .js output file into several .js files that can be independently *loaded* (not *updated*).

**Comment by scf37** [comment] 2017-09-24 05:28
This feature should also decrease time of incremental compilation for large projects because only some bundles have to be reassembled.

**Comment by sjrd** [comment] 2017-09-24 06:18
@scf37 No it probably wouldn't. See my comment just above yours.

**Comment by scf37** [comment] 2017-09-24 06:39
@sjrd even for fastOptJS? I thought all names in fast opt mode are deterministic so why not?

**Comment by sjrd** [comment] 2017-09-24 06:55
Yes, even for `fastOptJS`. The same comment applies. There are core strategic design decisions in how Scala.js compiles to JavaScript that make this impossible. Deterministic names is not the end of the story. You can look at what the [`Emitter`](https://github.com/scala-js/scala-js/tree/master/tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/emitter) does if want more precise answers.

Let's not pollute this thread further with random speculation.

**Comment by ramnivas** [comment] 2018-01-14 21:42
Related FYI: We recently finished moving to scalajs-bundler. Using it in the [`LibraryOnly` mode](https://scalacenter.github.io/scalajs-bundler/reference.html#bundling-mode-library-only), we are able to use `@JSImport` to reference external JS modules as well as project's own assets **without** experiencing the ~45 second per build (now it is more like 10 second--high, but not as bad). So yay!

The bundle size is still pretty high (the fullOptjs file ~550 KB gzipped + other libraries and assets) with each class of users (admin, general public, student, teacher, content creator) needing only a small portion of functionality. So the rest of the issues raised here is still relevant to us.

**Comment by gbogard** [comment] 2018-11-19 08:54
I know this issue has been standing still for quite a few months now, but I'm also very interested in this. Not all of my users need all the features of the app, so being able to split the bundles by page would be a huge win

**Comment by gzm0** [comment] 2019-11-29 19:17
I am starting to look into this, now that 1.0 is mostly done.

**Comment by gzm0** [comment] 2019-11-29 19:57
From what I understand we need two large building blocks. Definitions of splitting taken from [[1]]. Comments on feasibility, unmet requirements, misconceptions are very welcome.

# Step 1: Split output

Split the SJS output in multiple modules that import each other. This would enable "Entry point splitting": For example, split a user facing app and an admin interface.

Random thoughts:
- Splitting by class seems most intuitive
- Can bundlers deal with this number of chunks?
- What to do with circular dependencies
- If we need to be smarter, incrementality might be an issue.
- Splitting by artifact (Java style module?) might be another alternative.

# Step 2: Dynamic loads

Load modules dynamically `import()` instead of `import` so that even single page apps can load partially.

Random thoughts:
- Will likely need language support because asynchronicity "leaks".
- Probably best driven by the developer anyways (and kept explicit).
- Making sure an intended separation stays separated might be a challenge.
- If splitting is by artifact / module, introduce "dynamic dependencies"?

[1]: https://developers.google.com/web/fundamentals/performance/optimizing-javascript/code-splitting

**Comment by sjrd** [comment] 2019-11-29 20:09
### Step 1

* At least Windows itself has serious issues with large number of files. Splitting every class is going to be completely prohibitive on that platform, regardless of the bundler.
* I think we can probably provide a more-or-less custom config to specify where to put the boundaries. The minimum would be to allow to specify a set of packages that should go together.


### Dynamic loads

* The minimum would be just provide it as is, relying on the developer to use `js.import(...)` where appropriate.
* We could provide some better language support in the form of a `js.dynamicConstructorOf[C]` and `js.dynamicLoad(Obj)` where `C` and `O` are `@JSImport` classes and objects. Those could return a better typed `Promise` than the bare `js.import`.
* We could go further with a `js.dynamicLoad { <expr> }` that would isolate in `<expr>` all the references to `@JSImport` classes and objects, and request them all via an underlying `js.import(...)` before proceeding with the evaluation of the `expr`. This should probably be done in a macro outside of the core.

**Comment by ramnivas** [comment] 2019-11-29 22:27
Very glad to this discussion getting restarted!

### Split output

* This, by itself, will be a huge productivity boost. In our application, for example, we can't use hot-loading with React due to how it treats [`Context`](https://reactjs.org/docs/context.html). Generally, context providers sit very high-up in the component tree and subtrees using consumers are updated whenever the provider changes the context. React uses reference equality in detecting if context is changed. With a single -fastOpt.js, with every change, all providers are recreated, and thus creating a new context, thus invalidating all consumers (which, almost always, means effectively every component).

* Custom config to define the unit of the split seems fine. Ideally, there are predefined options such as per-class, per-package, etc. Is per-source file a viable option? If so, that may be a fine default, since it mirrors the JS world (and Windows developer choose another option if the number of files becomes a problem).

### Dynamic loads
@sjrd By your references to `JSImport` classes/object, do you mean, dynamic loading will be limited to external javascript-defined code?

**Comment by sjrd** [comment] 2019-11-29 22:49
> By your references to JSImport classes/object, do you mean, dynamic loading will be limited to external javascript-defined code?

Ah! That's a good point. So we'll also need to support that for Scala classes and objects. Somehow ...

**Comment by gzm0** [comment] 2019-11-30 05:38
Ok, seems like manual config for splitting is a good starting point. Thoughts:

- Package prefix is probably the best starting point, no point in specifying `scala`, `scala,collection`, etc.
- We can simply disallow cyclic dependencies so we only need to detect them, not avoid them.

RE dynamic loads: @ramnivas you beat me to it. I think in practice this will be not as invasive as it seems, we might get away with defining an `Async` IR node and some compiler primitives. What I'm unsure about is how to make sure the splitting happens as expected by the developer even under complex conditions.

**Comment by japgolly** [comment] 2019-11-30 05:56
> Package prefix is probably the best starting point, no point in specifying scala, scala,collection, etc.

How about a regex over FQCNs?

**Comment by godenji** [comment] 2019-12-11 05:04
Great news! This has been the single biggest blocker wrt going all-in on Scala/Scala.js.

Massive :+1:

**Comment by gzm0** [comment] 2019-12-24 12:21
Thinking further about selectors. Requirements I can think of:

1. Concept of root module (Scala.js needs this for its runtime)
2. Fully qualified class name prefix based classification.
3. Check non-intersection of specifiers without a concrete list of classes (ensures a wrong config is caught early on).
4. Option to fail if unknown class is present (instead of putting it into a default module)
5. Option to put unknown classes in a default module.

Notes:

Requirement 3 rules out regexes over FQCNs (/cc @japgolly). Personally I find verifiability more important than flexibility but I'm willing to discuss this.

Requirement 4/5: Unclear what the default should be, especially in view of standard libraries and classes required by the SJS runtime itself (which must be in the root module).

If the default is to have the root module as default module, these things neatly go automatically. However, it exposes the user to the risk of additional classes creeping into the default module (that might not belong there).

Another option would be to have a "smart default" where some "well known" packages are classified into the root module automatically. The downside is that specifying how this default evolves and how one can interact with it (how to tweak parts of it) is more difficult.

Please LMK what you think.

**Comment by sjrd** [comment] 2019-12-24 15:46
I don't think we need the concept of "root module" per se. Instead I suggest that we systematically put the core JS lib with whatever module contains `java.lang.Object` (rather than forcing `java.lang.Object` to be in the "root module"). This will make it simpler from a user's perspective, I believe.

**Comment by japgolly** [comment] 2019-12-24 21:08
@gzm0 that's a smart consideration, don't worry about my regex suggestion. The scenarios that trade-off would affect are cases where you want to split packages into multiple modules and don't have control over the package structure, like 3rd party libs. In which case, prefixes over regex would be fine so long as:

1. The prefix is of fqcn, not just package name. In other words, one can specify exact classes.
2. There's some kind of rule prioritisation mechanism that allows overlap (like acls) so that you could say a.b.C (class) goes to module X, and the remaining a.b. descendants go to module Y. Actually that would probably be pretty useful just for packages too: eg. "java.time goes here, rest of java goes there". You wouldn't want to specify each and every java.xxx where xxx is everything except time. The typical way of doing this is just ordered list of include/exclude rules that allow overlap. Hmmmm maybe req 3 isn't desirable after all...

**Comment by gzm0** [comment] 2019-12-27 06:01
Thanks for the suggestions.

@sjrd using `java.lang.Object` as proxy for where the core JS lib goes is excellent. Definitely easier to understand and equally flexible.

@japgolly thanks for the comment. This made me think of another use case: classify certain classes automatically into the "minimal required" module. Probably not something that we'd support in the first version, but it's good to keep it in mind so I design the API to be extensible for that (my current draft isn't).

The prioritization you describe is quite easily done: Say we have two `Map[String, String]`s: `classToModule` and `packageToModule`. For every class, if it's exact name is in `classToModule`, we take that. Otherwise, we keep looking up it's packages from the deepest one in `packageToModule` and take the first we find.

This is:
- Always unambiguous (i.e. we never get two modules for a given class)
- Allows the partial selections you describe (e.g. `Map("java" -> "main", "java.time" -> "time")`).

So ATM I'm tending towards something like this:


```scala
val mappings =
  ModuleMappings.package("java", "main") ++
  ModuleMappings.package("java.time", "time") ++
  ModuleMappings.class("java.time.Foo", "main") ++
  ModuleMappings.default("main")
```

Note that `package` and `class` need to be different because `a.b.c` can be a package (prefix) and a full class name at the same time (at least in our IR).

**Comment by gzm0** [comment] 2019-12-27 06:06
@sjrd Other issue: How do I communicate SJS private symbols between modules? If module `A` needs a thing in module `B`, how does it access it without polluting module `B`'s "public namespace"? Best solutions I could come up with:

- Put everything on single object with a mangled name.
- Create "export modules" which contain exported symbols and are always leaves.

I like option 2 more because it is cleaner. Downside is that the config surface becomes more complicated.

**Comment by sjrd** [comment] 2019-12-27 07:13
I had option 2 in mind as well. I think it's the only bulletproof thing to do.

**Comment by gzm0** [comment] 2019-12-27 09:51
Yeah... Downside is that with this, having a single file is not a mere special case of the multi file output :-/

**Comment by gzm0** [comment] 2020-02-02 16:44
I have been thinking about how to build the interface to this for a while and I'm not sure the proposed mappings are really what we want.

Take the following config:

```scala
val mappings =
  ModuleMappings.package("myapp.core", "core") ++
  ModuleMappings.package("myapp.frontend", "frontend") ++
  ModuleMappings.package("myapp.backend", "backend") ++
  ModuleMappings.default("core")
```

There is (or might be) an implicit assumption in this configuration that `frontend` and `backend` depend on `core` but not on each other. Since this is implicit, it cannot be verified.

Therefore, if by happenstance, something in `backend` refers to `frontend`, the resulting module structure will be valid, but broken.

Hence, I'm toying with the idea of requiring this to be explicit. Something like:

```scala
val modules = Seq(
  Module("core")
    .withMappings(Mappings.default()),
  Module("frontend")
    .withMappings(Mappings.package("myapp.frontend"))
    .withDeps("core"),
  Module("backend")
    .withMappings(Mappings.package("myapp.backend"))
    .withDeps("core"),
)
```

This would both avoid this problem and make some of the implementation easier.

A potential downside is verbosity in configuration. A further caveat is how to deal with transitive dependencies (if we allow them, we can make a similar argument about undetected dependency creep, although it would only manifest later).

Opinions?

**Comment by godenji** [comment] 2020-02-07 02:59
I like it, looks similar to SBT's `aggregate` and `dependsOn`.

To avoid stringly typos would we be able to do something like:
```scala
val core = Module("core").withMappings(Mappings.default())
val modules = Seq(
  core,
  Module("frontend")
    .withMappings(Mappings.package("myapp.frontend"))
    .withDeps(core),
  Module("backend")
    .withMappings(Mappings.package("myapp.backend"))
    .withDeps(core),
)
```
?

**Comment by gzm0** [comment] 2020-02-18 20:43
#3965 contains an RFC for an interface specification.

**Comment by ramnivas** [comment] 2020-02-20 23:51
I am not so sure that this package-based modules idea is the best way to proceed. A few reasons:

* Package may not be the right level of separation. For example, we have a package `paya.ui` that has a bunch of generic UI components (`Button`, `Slider`, `Dialog`, etc.) defined. Not all parts of the code need not all the components.
* It will make it hard to deal with some of the expected functionality in the JS world. For example, as I mentioned in https://github.com/scala-js/scala-js/issues/2681#issuecomment-559888858, hot-loading in the presence of React Context with less granular JS files will not work well.
* It is significantly different than the JS way, requiring a different way of thinking, resulting in a higher barrier for newcomers considering ScalaJS. Working and keeping up-to-date with Webpack will require special ongoing effort, which our relatively small community may not be able to keep up with. And then there are new tools that exists or are being proposed in the JS world (for example, rollup, parcel, [ESBuild](https://github.com/evanw/esbuild/), [SWC](https://github.com/swc-project/swc)). We cannot possibly support each of these tools.

So what could be done? Please note that I am sure that I have gotten a few details off. But hopefully, this will serve as a basis for discussion. Also, I may be repeating a few things said by me/others in the past, but trying to put a more complete picture here.

The core idea is to mimic the JS world as closely as possible. Then Webpack et al will have their assumption met (specifically that only a few files change at a time during development). I also don’t think we will need scalajs-bundler if this is implemented. Letting Webpack parse only a few JS files will be very performant and will not need the `LibraryMode` workaround and then there is very little is left for scalajs-bundler to do.

Consider the following set of classes:
```scala
class A {
  def display(): String = {
    val b = new B()
    b.hello()
  }
}

class B {
  def hello(): String = {
    "hello"
  }
}
```
Should lead to the creation of the following files:
```js
// A.js
import {B} from './B';

export class A {
  display() {
    let b = new B()
    return b.hello();
  }
}

// B.js
export class B {
  hello() {
    return "hello"
  }
}
```

Basically, every type gets its own dedicated js file and includes an import for each referred type. One obvious objection is the sheer number of files produced. But a quick check in our real project reveals that we have 35770 js files (most of those coming from node_modules) and that doesn’t seem to be a problem (true, I am on a Mac; but Windows users, too, presumably have similar number of js files in their projects). Also cc @Shadaj who has an idea of dealing with this issue, should it become a problem.

This, by itself, solves a bunch of problems. For example, unless the `B` scala type is modified, B.js will remain the same (at least in the `fastOptJS` mode, I hope). This means the React Context problem (which relies on reference equality) will no longer be an issue. Webpack will have minimal work to do during iterative development. And scalajs-bundler will be no longer required (short of providing integrated experience from within SBT; but that is, IMO, not super critical).

Now onto dynamic imports. Consider the following modified version of `A`.

```scala
class AA {
  def display(): Future[String] = {
    dynamicImport {
      val b = new B()
      b.hello()
    }
  }
}
```

Assuming that we have defined `dynamicImport` as the following (in Scala.js alongside `JSImport` and such):

```scala
def dynamicImport[T](thunk: => T): Future[T] // a marker method 
```

Will lead to the creation of the following A.js (B.js unchanged):

```js
export class AA {
  display() {
    return import('./B').then(({B}) => {
      let b = new B()
      return b.hello();
    });
  }
}
```

Basically, each type referred inside a `dynamicImport` block will result in a corresponding import statement. With this generated code, Webpack will create a separate chunk for the code inside the `import` block.

Let’s also consider a case where static and dynamic imports share a type.

```scala
class AAA {
  def display(): Future[String] = {
    dynamicImport {
      val b = new B()
      b.hello()
    }
  }

  def display2(): String = {
    val b = new B()
    b.hello()
  }
}
```

Here, we could do nothing special and import B statically and then again dynamically and leave it up to Webpack to understand (which correctly handles the situation by not creating a separate chunk to load B). Or could do something special to avoid dynamically importing types that are already required in the static scope.

**Comment by gzm0** [comment] 2020-02-21 09:27
@ramnivas thank you for raising your concerns!

I have a couple of clarification questions:

> Package may not be the right level of separation. [...] Not all parts of the code need not all the components.

What I read between the lines is that you do not want to define a module per class (i.e. UI component) yourself here? (which with the current proposal is possible, but maybe cumbersome indeed).

> It will make it hard to deal with some of the expected functionality in the JS world. [...] hot-loading in the presence of React Context with less granular JS files will not work well.

Could you clarify how the context maps to files and reloads? I do not know how react contexts are typically set-up and how the hot-loading works. From what I have understood so far, wouldn't it be enough to simply put the context provider in a separate module?

> It is significantly different than the JS way, requiring a different way of thinking, resulting in a higher barrier for newcomers considering ScalaJS.

Could you clarify what the JS way is and *how* what we are doing is more different than necessary?

> RE your proposal of per-class splits

How does this deal with cyclical dependencies? E.g.

```scala
class A { def foo = new B }
class B { def foo = new A }
```

I have a feeling that having cyclical `import`s is a recipe for disaster.

**Comment by gzm0** [comment] 2020-02-21 15:33
@sjrd do you have numbers on how many files are too much for a windows system? Just so we actually have ballpark numbers to compare against each other.

**Comment by sjrd** [comment] 2020-02-21 15:37
Not really. I just remember that 1 per class was too much; it was unusably slow.

**Comment by ramnivas** [comment] 2020-02-21 16:52
> What I read between the lines is that you do not want to define a module per class (i.e. UI component) yourself here? (which with the current proposal is possible, but maybe cumbersome indeed).

Indeed. In a way, the real difference between the current proposal and what I desire is no separate dependency declarations; referring to a type normally should suffice.

**Comment by ramnivas** [comment] 2020-02-21 17:48
> Could you clarify how the context maps to files and reloads? I do not know how react contexts are typically set-up and how the hot-loading works. From what I have understood so far, wouldn't it be enough to simply put the context provider in a separate module?

Indeed, it would be sufficient to put the context provider in a separate module. Basically, as long as that module remains unchanged on the filesystem (thus not forcing the hot-loading mechanism to load that file), everything should work fine. The issue is that the provider and consumers often are a part of the same package (it feels natural that way). For example, in our case, for the composition editor, here is (an abbreviated and simplified) component hierarchy.

```
CompositionEditContext // has a state "currentComposition" 
  Context Provider // providing context around "currentComposition"
     CompositionEditor
         SectionsEditor
             SectionEditor[] // Use the context and effectively update "currentComposition"
                 LineEditor[] // ... same
                    ClusterEditor[] // ...same
```

The lower level components access the context provided up in the hierarchy (using `React.useContext()`). The way React works is if the `currentComposition` changes (in reference equality way), it will rerender all consumers of that context.

When I modifying, say, `ClusterEditor`, I want hot-loading to only load that code. However, if I put the provider in the same module as consumers, then modifying `ClusterEditor` will end up creating a referentially-unequal context and thus recreating the whole hierarchy.

We have many such prodivers (`Selection`, `Environment`, `Mode`, etc) and they all are modelling a part of composition editor functionality. Putting them in a separate package will require explicit thinking about how Scala.js works and that will be a deviation from the way JS developers think.

**Comment by ramnivas** [comment] 2020-02-21 17:53
> Could you clarify what the JS way is and how what we are doing is more different than necessary?

In the JS world, module dependency is a local concern: I need a module (often consisting of just a class or a handful of functions), I declare thus in the dependent module and that is it. The current proposal requires me to think about the system as a whole and that means for a newcomer to the team, there is one more thing to learn.

**Comment by ramnivas** [comment] 2020-02-21 18:01
> How does this deal with cyclical dependencies?

JS seems to allow this. For example, it allows:
```js
// A.js
import {B} from './B';

export class A {
  display() {
    let b = new B()
    return b.hello();
  }

  message() {
    return "A's message"
  }
}

// B.js
import {A} from './A'

export class B {
  hello() {
    return new A().message()
  }
}
```
So we may not have to do anything specific i.e. add imports for referred types and leave it to Webpack et al to deal with it.

**Comment by ramnivas** [comment] 2020-02-21 18:02
@gzm0 Thanks for asking questions that gives me an opportunity to express the application developers' point of view.

**Comment by ramnivas** [comment] 2020-02-21 18:15
> Not really. I just remember that 1 per class was too much; it was unusably slow.

From application developer's point of view, 1 js file per 1 scala source file would suffice. More specifically, there need not be a separate js file for each nested types/companion objects, for example. Looking at our system, for example, for AlankarRouting.scala, we see the following class files:
```
AlankarRouting$.class
AlankarRouting$AlankarRoute$.class
AlankarRouting$AlankarRoutingParams$.class
AlankarRouting$AlankarRoutingParams.class
AlankarRouting$Default$.class
AlankarRouting$View$$anonfun$$lessinit$greater$1.class
AlankarRouting$View$.class
AlankarRouting.class
```
It would suffice if all these led to a single `AlankarRouting.js`.

Looking at our app, we have .class/.scala ratio of about 5. So that would be some saving without any impact of developers.

**Comment by japgolly** [comment] 2020-02-21 22:31
> The current proposal requires me to think about the system as a whole and that means for a newcomer to the team, there is one more thing to learn.

It's important to note that this point of view is from the perspective of a JS programmer working on a Scala.JS project. To any Scala developer, a few SBT settings barely register on the learning curve, where as learning webpack and integrating it with SBT is a huge amount of learning, time and effort.

I'd be very happy if this solution were able to output exactly what tools like webpack, rollup, etc  need so that workflows like what @ramnivas suggests are possible. The part I don't agree with is that workflow being mandatory, or a JS "build tool" being mandatory in the Scala toolchain. I'd hope that a solution could accommodate both, so that a Scala dev can enter a few SBT settings and out pop some modularised JS files that can be used immediately. From a Scala devs point of view, that's the path that requires the least learning, and the path that most easily integrates into the Scala dev workflow.

**Comment by raquo** [comment] 2020-02-21 22:52
> a few SBT settings barely register on the learning curve

Maybe I misunderstand your point, but having worked with both sbt and webpack a lot, I think you're overestimating the usability of sbt for an average Scala developer and underestimating the amount of sbt settings needed to replicate a useful subset of webpack in sbt. The innate complexity of bundling functionality isn't going away just because it was translated into sbt.

Bundling Javascript apps is a solved problem in Javascript. Regardless of what I think of sbt or webpack, Scala.js is just too small of a world to be developing its own Javascript bundling tooling. Well, any more than is strictly necessary for effective interop with existing JS bundlers.

When I have an issue with webpack I can google it and easily find a quality answer because that's what millions of people in the world use for bundling. When I have an issue with scalajs-bundler, well, good luck to me trying to understand it, let alone solve it. It'll be gitter spelunking all day at best.

**Comment by japgolly** [comment] 2020-02-21 23:43
I've worked with lots of Scala devs (including some fresh converts with no prior experience) and I've never met one who couldn't copy a few lines of SBT config into their build. I don't know if @gzm0's  original idea above is the best way to go, seems good enough to me, but I'm positive that what was presented above could be understood by the average Scala team/dev with very minimal effort.

webpack is the complete opposite. I also have a lot of experience in it (unfortunately) and I've consistently had a very different experience that what you describe. "You can google it and find a quality answer"? What?? First of all there are so many answers all over the internet because there are so many questions because it's so confusing, unstable and flakey. Secondly the vast majority of answers don't work, nor does the official documentation of webpack itself nor the many, many webpack plugins' official documentation because webpack changes so often and so fast and breaks everything in its path, all the damn time. I've wasted so much of my life literally copying-and-pasting settings from the official webpack homepage that don't work anymore because they don't update their documentation enough. Supporting users who want to use webpack: great, go for it. **Requiring** that Scala developers learn, intergrate and use webpack is a terrible idea, and I think you only believe it's feasible because as you say yourself: you've worked a lot with it. A Scala dev who's never used it isn't going to feel that way.

And yes, comparing it to scalajs-bundler makes it look favourable but I don't recommend people use scalajs-bundler; that's not the alternative I'm proposing (although if it I were I would 100% agree with you).

No, what I'm proposing and apologies if I wasn't very clear, is that we should think of the **Scala** dev perspective, seeing as this is **Scala**.JS. Scala devs shouldn't have to learn JS tools (nor learn how to integrate them with their Scala tools). Scala.JS already generates usable JS directly from SBT (via `{fast,full}OptJS`). We're talking about adding a feature to Scala.JS in this ticket. Using this feature once implemented, shouldn't break the existing ability to generate usable JS directly from SBT. Whatever downstream effects or tradeoffs we make whilst maintaining that property is something we should discuss and consider, but the idea of leaving that core property behind is the one aspect I feel very strongly that we should not do.

**Comment by ramnivas** [comment] 2020-02-22 00:06
@japgolly Generating bundles is one part of the equation and not that easy in any case. In our app, I see about 50 "modules"--small and big--that is not needed by most users. Going the SBT way would mean hand-crafting those many modules and declaring dependencies for them.

Assuming that hurdle is somehow crossed, we need to make sure that the right modules are loaded before the corresponding functionality is handled. Who/how should this be done?

Let's say (a real use case from our app), where the "print composition" is a rarely used functionality and has considerable code for layout manager and such. I imagine with my proposal, I will write the following code:

```scala
def clickPrint() = {
  dymanicImport {
     PrintSupport.print(...)
  }
}
```

And I am done. Webpack will take care of creating a separate chunk for print-related functionality and make sure that it is loaded before "PrintSupport.print(...)".

How do you imagine managing the same through just SBT?

I am no fan of Webpack. For a long time (and to some extent still) don't understand what/how it does many things. But it works. I suspect that if one were to create an alternative tool, that will have to essentially duplicate what Webpack does.

**Comment by ramnivas** [comment] 2020-02-22 00:10
> Scala.JS already generates usable JS directly from SBT (via {fast,full}OptJS)....Using this feature once implemented, shouldn't break the existing ability to generate usable JS directly from SBT.

I imagine a mode setting that dumps the code into one js file or into many js files.

**Comment by ramnivas** [comment] 2020-02-22 03:20
@japgolly Actually, if this feature is implemented in a JS-like way (my proposal), then you don't need any bundler at all. Most browsers now natively support modules https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import (IE being, as usual, an exception).

So those who want to use Webpack can do so (likely for reasons such as CSS/SCSS processing, image minifying during build, and to reduce the number of separate chunks to be downloaded) and those who don't like Webpack etc. can use browser's native module support. With HTTP2/HTTP3, downloading many small files is less of an issue, so this is where things are heading, anyway.

**Comment by gzm0** [comment] 2020-02-25 09:47
Thank you all for your comments. This is very insightful.

What I'm hearing is the following:

@ramnivas would like the system to be as automated as possible (high automation, low control), forwarding everything to webpack where feasible. A use-case he is particularly interested in is hot-reloading for React.

@japgolly and @raquo both want a simple way to generate `N > 1` output modules. There is some disagreement on which tool is easier to use / which community is stronger / has better support.

Please LMK if this summarizes the discussion appropriately.

**Comment by gzm0** [comment] 2020-02-25 10:00
With regards to circular dependencies: If I amend @ramnivas's example to:

```js
export class B extends A {
  /* snip */
}
```

The example fails *depending on* the order of which module is first loaded. Since this can perfectly happen in Scala code, Scala.js would be forced to write multiple modules per class and move away form ES2015 class declarations and instead set members mutably. I'm afraid this is unacceptable.

This would leave us with the problem of finding a maximal acyclic [graph partition][1] of the cyclic class dependency graph. I'll do some research on the feasibility of this.

[1]: https://en.wikipedia.org/wiki/Graph_partition

**Comment by gzm0** [comment] 2020-02-25 10:17
Stackoverflow answer with algorithms for finding cycles: https://stackoverflow.com/a/2794683/1149944

**Comment by gzm0** [comment] 2020-02-25 10:23
Seems what we want is strongly connected components: https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm

**Comment by scf37** [comment] 2020-02-25 16:16
Can't you guys start with subprojects? Must be simpler, no recursive deps by definition, also looks like good practice for modular javascript applications,

**Comment by ramnivas** [comment] 2020-02-26 18:16
> @ramnivas would like the system to be as automated as possible (high automation, low control), forwarding everything to webpack where feasible. A use-case he is particularly interested in is hot-reloading for React.
> 
> Please LMK if this summarizes the discussion appropriately.

Pretty much. I will clarify that by webpack, I really mean "webpack" 😄 i.e. any bundler system that exists or will exists in the future (including directly using a modern browser that supports modules). The main use case for me is the ability to defer loading of many many (in the range of ~50) modules, which would be painful without a JS-like approach.

**Comment by ramnivas** [comment] 2020-02-28 19:23
> With regards to circular dependencies: If I amend @ramnivas's example to:
> 
> ```js
> export class B extends A {
>   /* snip */
> }
> ```

It seems that 'A' will be always loaded before B. Either A is loaded because some other class has a dependency on it or it be loaded in the process of loading B.

**Comment by gzm0** [comment] 2020-04-02 14:07
@sjrd I'm writing the code to import SJS definitions from one module into another. For this, we have two higher level options:
- Import a module wildcard and select on that module (you have expressed that you prefer another solution).
- Import the relevant identifiers individually / directly (e.g. `import $c_frobber from 'module.js'`).

For the second solution we need to know what to import. We can do that based on:
- What each imported module defines. Cons: We over-import and over-invalidate.
- What each importing module needs.

The second option seems clearly desirable here.

For this in turn, we have two options:
- Record as we build the trees in `Emitter` (on `WithGlobals`).
- Pass it down as analysis.

If I remember correctly, you have expressed preference for the second solution. However, it seems to introduce substantial coupling between the `Analyzer` and the `Emitter`. As such, I still feel a solution recording the required imports as we build the trees is easier to build and maintain. WDYT?

**Comment by sjrd** [comment] 2020-04-02 14:38
I thought we could simply import what a module defines. We can determine that just from the fields of the target `LinkedClass`, which means we don't need to record anything nor consult a full `Analysis`. Of course that means we can over-import, but only of members that are anyway defined by a module that we have to refer to. So it won't result in importing too many *modules*, only too many *fields* of the modules. IMO that seems reasonable for now, and we can be more precise in the future as an optimization.

If you think we should only import the fields we're going to use, then recording as we build the trees seems preferable, IMO.

**Comment by gzm0** [comment] 2020-04-02 14:58
> So it won't result in importing too many modules, only too many fields of the modules.

Ah, yes indeed. This is not the main concern I have with over-importing. It's that we might be forced to re-emit a module even though it did not change (but one of its dependencies changed). This would not support the use cases for fine grained modules (which is what I'm prototyping for right now, to find out whether "too slow due to too many files" is a problem and if yes how big of a problem).

**Comment by sjrd** [comment] 2020-04-02 15:25
True. That could potentially cause more re-generation than necessary. Although I would assume that the set of variables exported for any given `LinkedClass` wouldn't change often.

**Comment by gzm0** [comment] 2020-04-15 16:34
So now linking a PR closes the linked issue...

**Comment by japgolly** [comment] 2020-04-19 01:06
Forgive my delayed response here. Ok so @ramnivas has pointed out that modules can be used directly in browsers. It's a bit of a psychological barrier for me to overcome but MDN is saying Chrome/FF have supported dynamic imports since 63/67 so I guess this is the new world! In which case, I think my earlier points are less valid now. Looking forward to seeing how this turns out!

**Comment by gzm0** [comment] 2020-05-17 17:16
More context/discussion on this in #4010.

**Comment by gzm0** [comment] 2020-07-29 07:46
Cross posting from #4111 (v2 prototype). We are discussing about a solution where each `@JSTopLevelExport` would have to specify its target module (with a default). As such, there would be very little linker configuration:
- Module initializers (as right now, but per module).
- `ModuleSplitStyle` (`SmallestModules`, `FewestModules`)

Would this be a viable alternative for everybody's use cases?

**Comment by japgolly** [comment] 2020-07-29 08:01
For my personal use cases, I'm fine with that.

I would like to just confirm though: Let's say I have two top level SBT modules A & B with a `@JSExportTopLevel` in each, and a shared SBT modules C & D that they both A & B on. I'd like to end up with three JS modules: A, B, and a shared module of C+D (roughly speaking). Specifying the target modules in A & B is no problem but how would one go about extracting the parts of C & D that are shared by both A & B? I sense webpack in the answer but what are the SJS outputs / webpack inputs going to look like?

**Comment by gzm0** [comment] 2020-07-29 08:25
For your example, you'd get 3 files (with `FewestModule` splitting mode):

- `a.js`: everything that is only needed by `A`, imports `root.js`
- `b.js`: everything that is only needed by `B`, imports `root.js`
- `root.js`: everything that is needed by `A` and `B` and Scala.js itself.

With `SmallestModule` splitting mode, you'd get:

- `a.js`: the top level export only
- `b.js`: the top level export only
- tons of small files with minimal imports between them (with class level granularity).

Both of these you can but don't need to run them through webpack (but the second one is probably better suited for this).

**Comment by sjrd** [comment] 2020-07-29 08:39
One distinction is that @japgolly was talking about a case where A and B are different sbt project. To achieve the result shown by @gzm0, they would either have to both be put in the same sbt project, or have an additional sbt project E that depends on A and B and contains no code. You'd then use E/fastOptJS to produce all the .js files.

**Comment by japgolly** [comment] 2020-07-29 10:59
Ok cool. Yes, as @sjrd says I was mostly concerned about different sbt modules/projects. If I have to create an exports-only sbt project E, that's actually no problem, especially if there's a `FewestModule` mode that avoids me needing to involve webpack, well that's a perfectly acceptable trade-off and I'd be very happy with that. Thanks!!

**Comment by ramnivas** [comment] 2020-07-29 14:33
This looks good for our use case. We are likely to have only one `JSExportTopLevel` and `SmallestModules` should suffice our needs.

**Closed** 2020-10-04 16:36 UTC
Labels: enhancement
