### ISSUE TITLE
ScalaCheckFramework is not allowed or does not exist.

### ISSUE THREAD

**Issue by Josef-Vonasek** [scala-js/scala-js#3861] opened 2019-11-19 09:32 UTC
If I run `sbt projectJs/test` on empty project on Linux and Mac trough CI, I get the following error:

`org.scalajs.testcommon.RPCCore$RPCException: scala.scalajs.js.JavaScriptException: TypeError: Access to host class org.scalacheck.ScalaCheckFramework is not allowed or does not exist.`

Note that test on Windows does not throw this error and I don't have any dependencies on ScalaCheck. My build.sbt looks like this:
```scala
lazy val all = (project in file("."))
  .settings(version := "0.1")
  .aggregate(
    projectjvm,
    project.js
  )

lazy val project = crossProject(JVMPlatform, JSPlatform)
  .withoutSuffixFor(JVMPlatform)
  .crossType(CrossType.Pure)
  .in(file("project"))
  .configs(Test)
  .settings(
    scalaJSUseMainModuleInitializer := true,
    version := "0.1",
    libraryDependencies ++= Seq(
      "org.scalatest"     %%% "scalatest"  % "3.0.5" % Test,
    )
  )
  .enablePlugins(ScalaJSPlugin)
```

**Comment by sjrd** [comment] 2019-11-19 09:37
Most likely a duplicate of https://github.com/scala-js/scala-js/issues/3673.

**Closed by sjrd** 2019-11-19 09:37 UTC
