### ISSUE TITLE
Companion object for ScalaJSDefined classes, or not?

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2806] opened 2017-03-14 23:25 UTC
```scala
@ScalaJSDefined class X extends js.Object
val X = js.constructorOf[X]
```
This fails with
> X is already defined as (compiler-generated) case class companion object X

Ok no worries, let's check it out:
```scala
@ScalaJSDefined class Y extends js.Object
println(Y)
```
This fails with
> not found: value Y

**Comment by sjrd** [comment] 2017-03-14 23:31
Looks like a scalac thing. Neither error message is triggered by Scala.js. I'm sure you can reproduce worth plain old Scala classes on Scala/JVM.

**Comment by japgolly** [comment] 2017-03-15 00:48
I could've sworn I'd done stuff like that before with the only difference here being the `@ScalaJSDefined`.

Anyway, let's try:
```scala
package hmmm

object Hmmm {
  class X
  val X = 123
}
```
This compiles fine with normal scalac.

Let's try this with Scala.JS:
```scala
package hmmm

object Hmmm {
  @ScalaJSDefined class X extends js.Object
  val X = 123

  class Y
  val Y = 123
}
```
fails with
```
X is already defined as (compiler-generated) case class companion object X
```

You sure `@ScalaJSDefined` isn't doing/causing something weird?

**Comment by sjrd** [comment] 2017-03-15 04:40
I am not completely sure, no. I will investigate today.

**Comment by sjrd** [comment] 2017-03-15 10:49
I cannot reproduce with any of Scala 2.10.2, 2.11.8 or 2.12.1. What is your exact setup?

**Comment by japgolly** [comment] 2017-03-15 10:52
At the time, I was dumping the above snippet right here:
https://github.com/japgolly/scalajs-react/blob/master/test/src/test/scala/japgolly/scalajs/react/core/RawComponentEs6Test.scala#L13

You could try cloning the repo. You'll see that it's using:
* Scala 2.12.1
* Scala.JS 0.6.14
* SBT 0.13.13

**Comment by japgolly** [comment] 2017-03-15 10:54
FWIW I'm only on Arch Linux although I can't see how that could affect this.
```
Linux golly-desktop 4.10.1-1-ARCH #1 SMP PREEMPT Sun Feb 26 21:08:53 UTC 2017 x86_64 GNU/Linux
```

How bizarre. Tomorrow I'll hijack a different project to try it in.

**Comment by japgolly** [comment] 2017-03-16 00:40
I've narrowed this down some more: it only occurs when using macro paradise.
Add this to SBT settings and it consistently fails.

```scala
compilerPlugin("org.scalamacros" % "paradise" % "2.1.0" cross CrossVersion.full)
```

**Comment by sjrd** [comment] 2017-03-16 08:45
Ah, indeed! But then I can also reproduce it on Scala/JVM with any random annotation:
```scala
package hmmm

final class anyannot extends scala.annotation.StaticAnnotation

object Hmmm {
  @anyannot class X
  val X = 123

  class Y
  val Y = 123
}
```
fails to compile with
```
[error] /localhome/doeraene/projects/temp/test/Test.scala:7: X is already defined as (compiler-generated) case class companion object X
[error]   val X = 123
[error]       ^
```
So this is definitely not a Scala.js issue. It's an issue with macro-paradise. I'll close this here. I suggest you open an issue at https://github.com/scalamacros/paradise

**Closed by sjrd** 2017-03-16 08:45 UTC

**Comment by japgolly** [comment] 2017-03-16 20:30
Ah good find. Thanks. Raised https://github.com/scalamacros/paradise/issues/93

**Comment by nonsleepr** [comment] 2019-04-30 17:41
It's been two years. Are there any workarounds available?

**Comment by sjrd** [comment] 2019-04-30 19:16
@nonsleepr I guess the workaround is not to use macro paradise, or not to declare a val with the same name as a class.

Other than that, you'd have to look at macro paradise to change something. The investigation in this thread shows that Scala.js is not responsible for the error that is shown here.

**Comment by nonsleepr** [comment] 2019-04-30 19:33
Interestingly, the problem I have appears only when using Mill (v0.3.6) and Binding.scala (v11.7.0). (Scala v2.12.8 and Scala.JS v0.6.27).
I switched the project back to SBT and it no longer complains.
I would be able to create a small project to reproduce the problem if you're interested. Or should that go to Mill?

**Comment by sjrd** [comment] 2019-04-30 19:37
> I would be able to create a small project to reproduce the problem if you're interested. Or should that go to Mill?

I'm tempted to say Mill by default. We don't maintain anything Mill-related in this repo, nor do we have any knowledge about Mill. So if something works in sbt and doesn't work in Mill, you have a better chance of finding someone knowledgeable among Mill maintainers than here.
