### ISSUE TITLE
regex does not give the same outcome in scalajs vs scala

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-js/scala-js#1847] opened 2015-08-14 04:01 UTC
scala
```
scala> val that = """|<p><code>
                     |List(1)
                     |</code></p>""".stripMargin
scala> "(?s).*<code>(.*?)</code>.*".r.pattern.matcher(that).matches()
res1: Boolean = true
```
vs
scalajs
```scala
dom.console.log("(?s).*<code>(.*?)</code>.*".r.pattern.matcher(that).matches()) // false
```

**Comment by andreaTP** [comment] 2015-08-14 06:47
This is documented in http://www.scala-js.org/doc/semantics.html

Javascript RegEx are supported and not Java ones:
```The support for regular expressions in Scala.js is implemented on top of JavaScript regexes.```

**Comment by sjrd** [comment] 2015-08-14 10:03
Duplicate of #1201.

**Closed by sjrd** 2015-08-14 10:03 UTC
