### ISSUE TITLE
Linker crash with shapeless

### ISSUE THREAD

**Issue by InTheNow** [scala-js/scala-js#1585] opened 2015-04-08 16:10 UTC
As per https://github.com/milessabin/shapeless/issues/347, the linker crashes in fastoptJs when running the tests. 

I've isolated the offending code and added to a [mini project](https://github.com/InTheNow/scalajs-cross-compile-example), extra details there

**Comment by sjrd** [comment] 2015-04-09 16:15
It's not the linker's fault. The IR is faulty. Checking the IR gives the following errors:
```
MyLibrary.scala(10:18:VarRef): Cannot find variable fresh$macro$1$module in scope
MyLibrary.scala(10:18:VarRef): Cannot find variable fresh$macro$1$module in scope
MyLibrary.scala(10:18:VarRef): Cannot find variable fresh$macro$1$module in scope
```
Offending part of the IR:
```scala
    this.l2$1 = mod:Lshapeless_HList$.hlistOps__Lshapeless_HList__Lshapeless_syntax_HListOps(
        this.li__Lshapeless_$colon$colon()).map__Lshapeless_Poly__Lshapeless_ops_hlist$Mapper__Lshapeless_HList({
      val fresh$macro$1$module: sr_VolatileObjectRef = mod:sr_VolatileObjectRef$.zero__sr_VolatileObjectRef();
      this.fresh$macro$1$1__p1__sr_VolatileObjectRef__LMyLibrary$fresh$macro$1$2$(fresh$macro$1$module)
    }, mod:Lshapeless_ops_hlist$Mapper$.hlistMapper1__Lshapeless_PolyDefns$Case__Lshapeless_ops_hlist$Mapper__Lshapeless_ops_hlist$Mapper(
        this.fresh$macro$1$1__p1__sr_VolatileObjectRef__LMyLibrary$fresh$macro$1$2$(fresh$macro$1$module).caseUniv__Lshapeless_PolyDefns$Case(),
        mod:Lshapeless_ops_hlist$Mapper$.hlistMapper1__Lshapeless_PolyDefns$Case__Lshapeless_ops_hlist$Mapper__Lshapeless_ops_hlist$Mapper(
            this.fresh$macro$1$1__p1__sr_VolatileObjectRef__LMyLibrary$fresh$macro$1$2$(fresh$macro$1$module).caseUniv__Lshapeless_PolyDefns$Case(),
            mod:Lshapeless_ops_hlist$Mapper$.hlistMapper1__Lshapeless_PolyDefns$Case__Lshapeless_ops_hlist$Mapper__Lshapeless_ops_hlist$Mapper(
                this.fresh$macro$1$1__p1__sr_VolatileObjectRef__LMyLibrary$fresh$macro$1$2$(fresh$macro$1$module).caseUniv__Lshapeless_PolyDefns$Case(),
                mod:Lshapeless_ops_hlist$Mapper$.hnilMapper1__Lshapeless_ops_hlist$Mapper()
            )
        )
    )).asInstanceOf[Lshapeless_$colon$colon];
```
We can indeed see that `fresh$macro$1$module` is used thrice outside its defining scope, which is not good.

**Comment by sjrd** [comment] 2015-04-09 16:23
Well, it's not even Scala.js' fault at all. Here is the Tree we receive from scalac:
```scala
MyLibrary.this.l2 = shapeless.this.HList.hlistOps(MyLibrary.this.li()).map({
  @volatile var fresh$macro$1$module: runtime.VolatileObjectRef = scala.runtime.VolatileObjectRef.zero();
  MyLibrary.this.fresh$macro$1$1(fresh$macro$1$module)
}, shapeless.ops.hlist$Mapper.hlistMapper1(
    MyLibrary.this.fresh$macro$1$1(fresh$macro$1$module).caseUniv(),
    shapeless.ops.hlist$Mapper.hlistMapper1(
        MyLibrary.this.fresh$macro$1$1(fresh$macro$1$module).caseUniv(),
        shapeless.ops.hlist$Mapper.hlistMapper1(
            MyLibrary.this.fresh$macro$1$1(fresh$macro$1$module).caseUniv(),
            shapeless.ops.hlist$Mapper.hnilMapper1()))
)).$asInstanceOf[shapeless.::]();
```
in which we can observe the same issue: `fresh$macro$1$module` is used outside its defining scope.

@milessabin I suspect this is caused by a macro coming from Shapeless. I guess it "works" on the JVM, by "chance", because the JVM back-end lets you get away with this inconsistency. But the Scala.js back-end requires well-behaved trees.

**Comment by sjrd** [comment] 2015-04-09 16:31
For reference, the relevant part of the tree after `typer`, where the inconsistency is already visible:
```scala
private[this] val l2: shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]] =
  shapeless.this.HList.hlistOps[shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]]](MyLibrary.this.li).map({
    object fresh$macro$1 extends AnyRef with shapeless.poly.~>[shapeless.Id,shapeless.Id] {
      def <init>(): fresh$macro$1.type = {
        fresh$macro$1.super.<init>();
        ()
      };
      def apply[T](t: T): T = mIdId[T](t)
    };
    fresh$macro$1
  })(hlist.this.Mapper.hlistMapper1[fresh$macro$1.type, Int, shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]](
      fresh$macro$1.caseUniv[Int],
      hlist.this.Mapper.hlistMapper1[fresh$macro$1.type, Int, shapeless.::[Int,shapeless.HNil]](
          fresh$macro$1.caseUniv[Int],
          hlist.this.Mapper.hlistMapper1[fresh$macro$1.type, Int, shapeless.HNil](
              fresh$macro$1.caseUniv[Int],
              hlist.this.Mapper.hnilMapper1[fresh$macro$1.type]))));
```

**Comment by InTheNow** [comment] 2015-04-09 19:28
Well... I'm treading on very dangerous territory:

 I've changed `Poly.scala` and now it works :)

**Comment by sjrd** [comment] 2015-04-09 19:30
What's `Poly.scala`?

**Comment by milessabin** [comment] 2015-04-09 19:31
What's the change?

**Comment by InTheNow** [comment] 2015-04-09 19:32
the shapeless class where the macro is defined - but i may have spoken too soon

**Comment by milessabin** [comment] 2015-04-10 08:37
OK, I _think_ this all relates to my attempt to have vanilla Scala functions and (polymorphic) methods lifted to shapeless `Poly`s via a macro ... I consider that to be a largely failed experiment, which should at the very least be revisited in the light of the work on SAM support.

So I think it would be acceptable to simply disable [these tests](https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/poly.scala#L292-L459) on the Scala.js branch(es).

**Comment by sjrd** [comment] 2015-04-10 08:45
OK, so, I'll close it here. Whether it should be fixed or ignored, anyway there's nothing that can be done about it on Scala.js' side.

**Closed by sjrd** 2015-04-10 08:45 UTC
Labels: bug

**Comment by milessabin** [comment] 2015-04-10 08:50
FWIW, whatever I'm doing is clearly getting past the typer on both JVM and JS, so if there's a real problem then I think it's there.

Escape from a defining context _is_ allowed though ... it should just be widened to something which is meaningful in the context being escaped to. I'm fairly sure that I'm not doing anything which would require anything illegitimate.

**Comment by sjrd** [comment] 2015-04-10 09:25
I agree that the typer failing to catch this as an error is a problem. But I do believe it *is* a problem (and, from a short discussion, so does @densh). What does it even mean to access a variable outside its defining scope? It just happens to find its way through the compiler pipeline without being hurt any further, and eventually produces bytecode that works. But it's definitely not *valid*. With scala.meta, I'm told it couldn't even happen. And I'm pretty sure this is one of the crucial things that `-Ycheck` validates in dotty.

Note that, at least "manually", it's easy to write the equivalent but valid code for the above, simply by moving the definition of `fresh$macro$1` a bit before:
```scala
private[this] val l2: shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]] = {
  object fresh$macro$1 extends AnyRef with shapeless.poly.~>[shapeless.Id,shapeless.Id] {
    def <init>(): fresh$macro$1.type = {
      fresh$macro$1.super.<init>();
      ()
    };
    def apply[T](t: T): T = mIdId[T](t)
  };
  shapeless.this.HList.hlistOps[shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]]](MyLibrary.this.li).map({
    fresh$macro$1
  })(hlist.this.Mapper.hlistMapper1[fresh$macro$1.type, Int, shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]](
      fresh$macro$1.caseUniv[Int],
      hlist.this.Mapper.hlistMapper1[fresh$macro$1.type, Int, shapeless.::[Int,shapeless.HNil]](
          fresh$macro$1.caseUniv[Int],
          hlist.this.Mapper.hlistMapper1[fresh$macro$1.type, Int, shapeless.HNil](
              fresh$macro$1.caseUniv[Int],
              hlist.this.Mapper.hnilMapper1[fresh$macro$1.type]))));
}
```
It seems to me that there should be a way for the macro to generate this valid code. I'm not saying the change is trivial or even easy. But in theory it should be able to do so.

**Comment by milessabin** [comment] 2015-04-10 09:30
Well, I'm not so sure. IIRC the only thing I'm interested in is the singleton type of a value. The singleton type of any value should be meaningful in any context in which the value exists. Values escape from the contexts in which they're created, and so their singleton types (qua bare singleton types, we need not know anything about them) should escape along with them.
