### ISSUE TITLE
Scala.js 1.3.1 with scalajs-bundler breaks Circe

### ISSUE THREAD

**Issue by kamilkloch** [scala-js/scala-js#4305] opened 2020-11-27 22:22 UTC
See the following repository for full example: https://github.com/kamilkloch/x-monitor-webpack.git
```
sbt
project frontend
fastOptJS / webpack
```
Open `frontend/index-dev.html`, show console.

With Scala.js 1.3.1 web console reads
```
{
   "name" : "Bob"
}
io.circe.FailedCursor@1
Left(DecodingFailure(Attempt to decode value on failed cursor, List(DownField(name))))
```

With Scala.js 1.3.0 it works:
```
{
  "name" : "Bob"
}
io.circe.cursor.ObjectCursor@1
Right(Bob)
```

**Comment by sjrd** [comment] 2020-11-28 18:00
Thanks for the report. I can indeed reproduce the issue. I minimized it here: https://github.com/sjrd/x-monitor-webpack/tree/minimize

The trouble is that I cannot create a minimization that does not involve scalajs-bundler/webpack. In that minimization, both `frontend/run` and `frontend/test` display a `Right(Bob)` result. Only `frontend/fastOptJS/webpack` followed by opening in a browser reproduces the issue.

Therefore, I don't think this is a Scala.js issue. It may be a scalajs-bundler issue, but I suspect that it's even somewhere in Webpack.

---

Adding the following setting in `frontend` *does* work around the issue:
```scala
scalaJSLinkerConfig ~= { _.withESFeatures(_.withAvoidClasses(false)) }
```
in the sense that now the Webpack-processed output correctly prints `Right(Bob)`, like the non-Webpack-processed outputs.

**Comment by kamilkloch** [comment] 2020-11-28 23:20
Thanks for looking into it! The question remains: what changed from 1.3.0 to 1.3.1 so that `fastOptJS / webpack` is failing?
Adding your proposed setting to `scalaJSLinkerConfig` does not look like a long-term solution...

**Comment by sjrd** [comment] 2020-11-29 06:28
What changed is that we stopped emitting JavaScript `class`es for most Scala classes (for performance readings; see [the release notes](https://www.scala-js.org/news/2020/11/16/announcing-scalajs-1.3.1/)). That is a non observable change, but it affects how the code "looks" internally, which could trigger a bug in a downstream processing tool. The setting reverts to the old behavior, which apparently works around whatever bug there is downstream.

**Comment by kamilkloch** [comment] 2020-11-29 23:08
Thanks. What would be the next step to solve the issue? 
```scala
scalaJSLinkerConfig ~= { _.withESFeatures(_.withAvoidClasses(false)) }
```
takes away Firefox performance. I am happy to report it to `webpack`, just not sure what to do. Attach the outputs of `fastOptJS`?

**Comment by sjrd** [comment] 2020-11-30 05:52
I'm not sure. You can try reporting to Webpack, but they might not like it because, from their point of view, it's going to be far from minimized.

But at least getting a reproduction that involves only Webpack on the Scala.js output, without scalajs-bundler in the middle, would be very helpful. Or failing to do so would also be very useful, since that would isolate the issue in scalajs-bundler.

**Comment by gzm0** [comment] 2020-11-30 09:15
> That is a non observable change, but it affects how the code "looks" internally

FWIW: We are providing hints to GCC what a class is in ES5.1 mode. Maybe webpack requires something similar?

**Comment by gzm0** [comment] 2021-02-01 18:34
Is there anything to be done here, or shall we close this?

**Comment by sjrd** [comment] 2021-02-01 18:39
I don't think there's anything we can do in Scala.js core.

**Comment by gzm0** [comment] 2021-02-04 13:22
Thinking about this some more, I think we should at lest leave this open and ideally dedicate some time minimizing this. Especially because:
- We do not know for sure this isn't a Scala.js issue (or at the very least I'm not convinced we know for sure based on what I read in this issue).
- If Scala.js + bundler + webpack are affected, we should care, since this isn't a niche case.

**Comment by sjrd** [comment] 2021-08-02 09:57
This was apparently fixed in Scala.js 1.5.0. I can reproduce the issue with Scala.js 1.4.0, but not with 1.5.0 nor 1.6.0. The diff of `main.js` as produced by Scala.js, from 1.4.0 to 1.5.0, is here:
https://gist.github.com/sjrd/51192488979fd0686e313acc6ed67cc6
The diff of the `-bundle.js` file produced by scalajs-bundler is equivalent up to line numbers.

I don't know what, in that diff, fixes the issue. I also don't know why it was surfaced only with the bundler, nor why it is fixed by reverting the class encoding. Scala.js 1.5.0 fixed several codegen bugs (see [bug list here](https://github.com/scala-js/scala-js/issues?q=is%3Aissue+milestone%3Av1.5.0+is%3Aclosed)) so it is not completely nonsensical, even though I cannot pinpoint the specific fix.

@gzm0 Shall we close this and assign to milestone v1.5.0, or do you want me to keep investigating to find the real cause?

**Comment by gzm0** [comment] 2021-08-02 10:14
Hrm... it would be nice to have a regression test, but given the effort required to do that, maybe we just close this?

**Comment by sjrd** [comment] 2021-08-02 10:31
I found why it only surfaces in scalajs-bundler! The bundle produced by scalajs-bundler doesn't have
```js
'use strict';
```
at the top of the file! It has it at the beginning of the Scala.js code, but that comes after the code inserted by the bundler for the "module system". This means that the whole script loses strict mode, including the Scala.js-related code. If I manually add the `'use strict';` at the top of the file produced by scalajs-bundler, then it also fixes the bug!

That also explains why forcing `class`es fixes the issue, because [the body of JavaScript `class`es always executes in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#strict_mode).

It does not explain why Scala.js 1.5.0+ fixes the issue. Most likely, because for an arbitrary reason, we do not rely on having strict mode somewhere where we previously relied on it.

It does mean that the root issue is not in this repo, however, and that it can pop up again in the future, at any arbitrary time. We should fix it properly in scalajs-bundler.

**Comment by sjrd** [comment] 2021-08-02 14:05
I created https://github.com/scalacenter/scalajs-bundler/issues/407 to track this over in scalajs-bundler, along with a failing test case. I'm going to close this here.

**Closed by sjrd** 2021-08-02 14:05 UTC
Labels: separate repo
