### ISSUE TITLE
Regexp Behavior changed:  0.6.26 -> 0.6.29 /  Cannot read property 'length' of null

### ISSUE THREAD

**Issue by scalway** [scala-js/scala-js#3954] opened 2020-02-08 16:38 UTC
In my project I have code similar to this one:

```scala
val regexp = """((\.)|(\>))""".r
val text = """ Test. Next <Oj> Test """

println(regexp.replaceAllIn(text, _.matched + "/"))
// in scalajs 0.6.26: Test./ Next <Oj>/ Test
// in scalajs 0.6.29+: thrwos error.

```

https://scalafiddle.io/sf/58Nl4aN/0

```
ERROR: Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at $c_ju_regex_Matcher.eval [as end__I__I] (eval at  (https://scalafiddle.io/resultframe?theme=light:46:37), :5134:27)
    at $c_s_util_matching_Regex$Match.eval [as ends$lzycompute__p1__AI] (eval at  (https://scalafiddle.io/resultframe?theme=light:46:37), :5319:35)
    at $c_s_util_matching_Regex$Match.eval [as ends__p1__AI] (eval at  (https://scalafiddle.io/resultframe?theme=light:46:37), :5340:64)
    at $c_s_util_matching_Regex$Match.eval [as force__s_util_matching_Regex$Match] (eval at  (https://scalafiddle.io/resultframe?theme=light:46:37), :5279:8)
    at $c_s_util_matching_Regex$MatchIterator$$anon$1.eval [as next__s_util_matching_Regex$Match] (eval at  (https://scalafiddle.io/resultframe?theme=light:46:37), :10417:184)
    at $c_LScalaFiddle$.eval [as init___] (eval at  (https://scalafiddle.io/resultframe?theme=light:46:37), :2136:19)
    at $m_LScalaFiddle$ (eval at  (https://scalafiddle.io/resultframe?theme=light:46:37), :2153:47)
    at eval (eval at  (https://scalafiddle.io/resultframe?theme=light:46:37), :16655:18)
    at eval (eval at  (https://scalafiddle.io/resultframe?theme=light:46:37), :16657:4)
    at https://scalafiddle.io/resultframe?theme=light:58:37
```

I'm using scala 2.12. It doesn't affect me anymore (I've changed implementation) but still it took me awhile to figure out what happened.

**Comment by sjrd** [comment] 2020-02-08 17:24
Duplicate of #3901, which is already fixed in 0.6.32.

**Closed by sjrd** 2020-02-08 17:24 UTC
