### ISSUE TITLE
NPE in Scala typechecker in Scala.js project

### ISSUE THREAD

**Issue by arthurp** [scala-js/scala-js#2529] opened 2016-07-14 05:33 UTC
I am getting a reproducible null pointer exception when compiling a Scala.JS project. The crash is not in the Scala.JS code, but I figured this was probably the best place to start anyway since Scala.JS is a pretty extensive plugin (and core projects tend to want to reproduce things on pure systems).

The exception trace starts:
java.lang.NullPointerException
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1769)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:111)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1390)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[rest is in https://gist.github.com/arthurp/e523283e4a7d94beeadab9a69b8d75d7]

The triggering project is available at https://github.com/arthurp/amps-screeps/tree/compiler-crash-1. I was able to reproduce the problem on another machine so I think it's general.

The code that triggers the problem appears to be [src/main/scala/org/singingwizard/screeps/ai/Loop.scala line 26](https://github.com/arthurp/amps-screeps/blob/compiler-crash-1/src/main/scala/org/singingwizard/screeps/ai/Loop.scala#L26). The problem version is:
```
Unpickle[AIContext].from(Memory.AIContext)
```
replacing this with:
```
Unpickle[AIContext].from(Memory.AIContext).get
```
removes the crash. (But leaves the type error. It's not well typed.)

Sorry I didn't minimize the test case. I just don't have the brain space. I hope this is helpful anyway.

**Comment by sjrd** [comment] 2016-07-14 05:48
Since the error is in "rechecks", it is almost certainly not related to Scala.js. It's either in scalac itself or caused by a macro (i.e., Prickle).

Since the faulty code does not use any Scala.js type directly, it should be possible to reproduce the bug in a JVM project, in which case it proves that Scala.js is not involved. If however a JVM project compiles fine and just adding `enablePlugins(ScalaJSPlugin)` causes the crash, then it's most likely caused by Scala.js and we can look into it.

**Comment by sjrd** [comment] 2016-07-21 08:21
Closing this until there is some evidence that this is caused by Scala.js (i.e., it cannot be reproduced in a Scala/JVM project).

**Closed by sjrd** 2016-07-21 08:21 UTC
