### ISSUE TITLE
Eliminate IIFEs where `this` is the sole arg, by inlining

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4653] opened 2022-03-11 02:29 UTC
After doing some more testing on a post-#4646 world, there's one other case I'd like to optimise, so that hot-reloading is really nice and hot 🔥, instead of warm 🍿. (And by that I mean it preserves user's state instead of reloading the entire page 😄)

This Scala

```scala
package demo
object Test {
  var x = 0
  val f: scalajs.js.Function1[Int, Int] = _ + x
}
```

generates this JS

```js
function $c_Ldemo_Test$() {
  this.Ldemo_Test$__f_x = 0;
  this.Ldemo_Test$__f_f = null;
  $n_Ldemo_Test$ = this;
  this.Ldemo_Test$__f_x = 0;

  this.Ldemo_Test$__f_f = (this$1 => _$1 => {
    var _$1$1 = $j_java$002elang$002eObject.$uI(_$1);
    return _$1$1 + this$1.Ldemo_Test$__f_x | 0;
  })(this);
}
```

and I'd love to optimise it to inline the arg and eliminate the IIFE as follows

```js
function $c_Ldemo_Test$() {
  this.Ldemo_Test$__f_x = 0;
  this.Ldemo_Test$__f_f = null;
  $n_Ldemo_Test$ = this;
  this.Ldemo_Test$__f_x = 0;

  this.Ldemo_Test$__f_f = _$1 => {
    var _$1$1 = $j_java$002elang$002eObject.$uI(_$1);
    return _$1$1 + this.Ldemo_Test$__f_x | 0;
  };
}
```

I understand that `this` is contextual and a bit hairy in the JS world cos I hacked this little test together and it seems that the `this` in the inner function is identical to the outer `this`.

```js
function $c_Ldemo_Test$() {
  this.Ldemo_Test$__f_x = 0;
  this.Ldemo_Test$__f_f = null;
  $n_Ldemo_Test$ = this;
  this.Ldemo_Test$__f_x = 5;

  this.Ldemo_Test$__f_f = (this$1 => _$1 => {
    console.log("inner this val: ", this)
    console.log("inner this arg: ", this$1)
    console.log("inner this match: ", this$1 === this)
    return _$1 + this$1.Ldemo_Test$__f_x | 0;
  })(this);

  console.log("outer this: ", this)
  console.log("result (expecting 6): ", this.Ldemo_Test$__f_f(1))
}
$c_Ldemo_Test$()
```

I'm thinking we could keep this optimsation small in scope by only applying it to capture values of `this`, and extracting & inlining it before the #4646 optimisation kicks in. WDYT?

**Comment by japgolly** [comment] 2022-03-11 02:33
Or actually this is probably a safer output in the event of nested closures:

```js
function $c_Ldemo_Test$() {
  this.Ldemo_Test$__f_x = 0;
  this.Ldemo_Test$__f_f = null;
  $n_Ldemo_Test$ = this;
  this.Ldemo_Test$__f_x = 0;

  this.Ldemo_Test$__f_f = _$1 => {
    var this$1 = this; // hello!!! <-----------------
    var _$1$1 = $j_java$002elang$002eObject.$uI(_$1);
    return _$1$1 + this$1.Ldemo_Test$__f_x | 0;
  };
}
```

**Comment by sjrd** [comment] 2022-03-11 03:19
In that case, the capture *is* necessary. What is not necessary is the usage of an IIFE to *implement* that capture. But then the problem is exactly #2675/#4384. So this looks like a duplicate to me.

**Comment by japgolly** [comment] 2022-03-11 03:28
Correct! The capture is necessary but I wouldn't say it's a dup of #2675 because that issue is much larger in scope; in this issue I'm just talking about optimisation the capture of `this`.

I think it would be a good idea to start with only `this` in scope for optimisation, then afterwards the scope could be expanded to include other things like purity checking, deduping, etc.

**Comment by sjrd** [comment] 2022-03-11 03:34
`this` is like any `val`, only with a funny name. From the compiler's perspective, there is no real difference.

In fact, if anything, `this` is a bit more complicated to deal with than `val`s, because it cannot be directly captured (at the JS level, not at the IR level) by a `function` function.

**Comment by gzm0** [comment] 2022-04-03 15:20
I propose to close this as a dupe of #2675.

**Closed** 2022-04-03 15:26 UTC
Labels: duplicate, optimization
