### ISSUE TITLE
Uncaught exceptions in 0.6.6 deadlock PhantomJS

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2223] opened 2016-02-03 02:16 UTC
If a test throws a `scala.scalajs.runtime.UndefinedBehaviorError`and it isn't caught, PhantomJS silently deadlocks with SJS 0.6.6. Tested with versions 2.0.0 and 2.1.1 of PhantomJS.

Stack trace: [stack.txt](https://github.com/scala-js/scala-js/files/114986/stack.txt)

**Comment by sjrd** [comment] 2016-02-03 09:30
Is this a regression wrt 0.6.5? i.e., did it work in 0.6.5?

**Comment by japgolly** [comment] 2016-02-03 10:08
I just now tried with 0.6.5 and it didn't deadlock, so yes, it appears to be a 0.6.6 regression.

**Comment by gzm0** [comment] 2016-02-03 10:10
There are subtle differences in how PhantomJS launches the internal websocket server between 0.6.5 and 0.6.6 so it is very well possible that something is fishy there.

**Comment by sjrd** [comment] 2016-02-03 10:19
So I guess it is either https://github.com/scala-js/scala-js/commit/f7f6de10a489c41bd8a6f5c3838c7cea60227e64#diff-2873085d7d2862ecf48da5fffc6c281f or https://github.com/scala-js/scala-js/commit/3a6562e81e129b43676e092078a9b01e41726a3e#diff-2873085d7d2862ecf48da5fffc6c281f

**Comment by gzm0** [comment] 2016-02-03 10:21
I bet on the tools refactoring. That one actually intended to change behavior....

**Comment by japgolly** [comment] 2016-02-03 10:32
The surprise is that every time is has occurred so far, it's been a `scala.scalajs.runtime.UndefinedBehaviorError`. Throwing a `java.lang.AssertionError` works fine and just prints a stack-trace.

**Comment by sjrd** [comment] 2016-02-03 10:36
That would be because UBE is a *fatal* error, which is not caught by `case NonFatal(e) =>`. If you use `Future`s, for example, the UBE would fall through directly to the global error handler of PhantomJS, whereas `AssertionError` would be caught and displayed explicitly by the `ExecutionContext`.

**Comment by nicolasstucki** [comment] 2016-02-08 10:23
@japgolly I'm having some trouble reproducing this deadlock. 
How is that `scala.scalajs.runtime.UndefinedBehaviorError` thrown? In which context? What kind of test? How are you running the tests?

**Comment by japgolly** [comment] 2016-02-08 11:29
@nicolasstucki It should be enough just to execute this:
```scala
().asInstanceOf[Boolean]
```

**Comment by japgolly** [comment] 2016-02-08 11:30
I can reproduce it by having the above line of code in a unit test, using lihaoyi's μtest and PhantomJS 2.

**Comment by nicolasstucki** [comment] 2016-02-08 13:45
@japgolly did you by any chance set `autoExit = false` in `PhantomJSEnv`?

**Comment by nicolasstucki** [comment] 2016-02-08 14:02
Im trying your code using something like this:
```scala
object Test1 extends TestSuite{
  val tests = TestSuite{ 'test1{ ().asInstanceOf[Boolean] } }
}
```
but it just fails with the `UndefinedBehaviorError` as expected. Are you using some other uTest construct?
How are you executing the tests?

**Comment by japgolly** [comment] 2016-02-08 21:45
Hi @nicolasstucki. Ok, this is really weird but I can't reproduce this anymore either!

##### Before

When I this occurred, it was very reproducible. The snippet I posted above was all that was needed. It was reproducible...
* in two different projects.
* after exiting and restarting SBT.
* after doing a clean build.
* after a downgrade and then re-upgrade of Phantom JS.

Both projects used scalajs 0.6.6 and Scala 2.11.7. Neither used `autoExit = false` and I *thought* but projects used PhantomJS but I've just double-checked and one project uses NodeJS, meaning this also occurred in NodeJS (!).

##### After

Since it was last reproducible and now, only two things really occurred.

1. I rebooted my machine a few days ago.
2. I upgraded some system components. *([Specifically](https://gist.github.com/japgolly/4f9700b1930749735f5c))*

Now that I can no longer reproduce this I'm not sure what else I can do. I can confirm that when it *was* reproducible it would occur with SJS 0.6.6 100% of the time, and not at all when I dropped to SJS 0.6.5.

Here is some other info:
```
> uname -a     
Linux golly-desktop 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux

> scala -version 
Scala code runner version 2.11.7 -- Copyright 2002-2013, LAMP/EPFL

> java -version 
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

> phantomjs --version
2.1.1

> node --version 
v5.5.0
```

**Comment by japgolly** [comment] 2016-02-08 21:53
Btw, yes, that snippet you posted @nicolasstucki is exactly what I expected to reproduce the issue. With a file like that in the tests I would just run `test` or `test-only abc.xyz.Test1` from SBT.

**Comment by gzm0** [comment] 2016-02-09 08:01
I'm wondering whether a mismatch between the test runtime library and the sbt-adapter could cause this? Notably I'm not sure what happens if `test-interface` and `test-adapter` are not in sync.

**Comment by sjrd** [comment] 2016-02-09 08:16
Could have been a reasonable explanation if `test-interface` had changed since 0.6.5. But it [has not](https://github.com/scala-js/scala-js/commits/master/test-interface/src/main/scala) (not the protocol, anyway).

**Comment by sjrd** [comment] 2016-02-20 10:23
Closing since it can't be reproduced anymore.

**Closed by sjrd** 2016-02-20 10:23 UTC
Labels: bug
