### ISSUE TITLE
Compile error with `functionName _` on Scala 2.12.0

### ISSUE THREAD

**Issue by vossad01** [scala-js/scala-js#2656] opened 2016-11-19 01:40 UTC
A method or function name followed by underscore does not appear be assignable to `js.Function0` on Scala 2.12.0 while it is on Scala 2.11.8.

On Scala 2.11.8, the following code compiles and works:

```scala
package object mypackage {
  import scala.scalajs.js
  def render() = {}
  val handler: js.Function0[Any] = render _
}
```
However, on Scala 2.12.0, it gives a compilation error:
>```
>[error] /home/user/dev/untitled/src/main/scala/mypackage/Main.scala:4: type mismatch;
>[error]  found   : Unit
>[error]  required: scala.scalajs.js.Function0[Any]
>[error]       setInterval(render _)
>[error]                   ^
>```

I am not sure if this is a known impact of the newer compiler, I couldn't figure out the right things to search for to find another record of this.  It can be worked around, but is a little bit of a wart because if the signature of `handler` could be `scala.Function0[Any]`, instead of `js.Function0[Any]`, it would compile.

### Workaround
Using lambda syntax rather than partial application syntax allows it to work. (Do I have that terminology right?)

Use
```scala
val handler: js.Function0[Any] = () => render()
```
instead of
```scala
val handler: js.Function0[Any] = render _
```

### Investigation
Looking with `-Xprint:typer` it appears that on 2.12.0 `render _` gets processed to be `` `package`.this.render()`` while `() => render()` ends up as ``(() => `package`.this.render())``.

On 2.11.8 they are processed to ``js.this.Any.fromFunction0[Unit]({(() => `package`.this.render())}`` and ``js.this.Any.fromFunction0[Unit]((() => `package`.this.render())``, respectively.

Scala.js 0.6.13

**Comment by sjrd** [comment] 2016-11-19 06:34
I am not sure whether this is intended or not. I know that *automatic* eta-expansion (which is what you're doing here, not partial application) was deprecated/removed. But here you're explicitly eta-expanding.

Anyway, if it's a bug, it's a scalac bug, and there is nothing Scala.js can do about it. Please find a reproduction that is independent of Scala.js (perhaps using `Runnable` or `Callable` from Java instead of `js.Function0`), and report a bug to Scala itself.

**Comment by vossad01** [comment] 2016-12-06 14:48
A quick update:

In my investigation there has been some support that this could be a bug in scala and scala/scala-dev#284 has been opened accordingly.

In the process have learned that the most specific term for this syntax is *method value* which then utilizes eta-expansion.  It also seems this is limited to the zero-argument case as parameterless and unary cases have been shown to work.

**Comment by sjrd** [comment] 2017-03-23 21:37
I don't think there's anything we can do about it in this repo, so I'll close this issue here.

**Closed by sjrd** 2017-03-23 21:37 UTC
Labels: upstream
