### ISSUE TITLE
Need a way to debug Scala.js offline via sourcemaps

### ISSUE THREAD

**Issue by solomatov** [scala-js/scala-js#2276] opened 2016-03-02 23:57 UTC
See http://stackoverflow.com/questions/35757352/how-to-debug-scala-js-in-offline-mode

**Comment by sjrd** [comment] 2018-06-16 18:28
The more recent #2489 is basically a duplicate of this issue, but since there is more discussion on that one, I am closing this issue as duplicate.

**Closed by sjrd** 2018-06-16 18:28 UTC
Labels: enhancement
