### ISSUE TITLE
Repeated calls to Map#apply results in crash

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#3989] opened 2020-03-10 03:56 UTC
Here is a minification. In `def wtf()` I create an immutable map and then call `.apply` 4 times. The first 3 times work but the 4th results in a `NoSuchElementException` exception.

```scala
import utest._

final case class X(a: X.Y, b: X.Y)

object X {

  final case class Y(value: Int)

  def fromInts(i: Int, j: Int): X =
    X(Y(i), Y(j))

  new scala.collection.mutable.HashMap[Int, Int]()
}

object Bug extends TestSuite {

  def v(i: Int, j: Int) = X.fromInts(i, j)

  val v10 = v(1, 0)
  val v11 = v(1, 1)
  val v12 = v(1, 2)
  val v20 = v(2, 0)
  val v21 = v(2, 1)

  def wtf() = {
    val a = List(v10, v11, v12, v20, v21).iterator.zipWithIndex.toMap

    println(a(v10)) // Prints 0
    println(a(v10)) // Prints 0
    println(a(v10)) // Prints 0
    println(a(v10)) // Throws java.util.NoSuchElementException: key not found: X(Y(1),Y(0))
  }

  override def tests = Tests {
    "wtf" - wtf()
  }
}

```

There are some bizarre things to notice about this minification:

* ~~removing the `new scala.collection.mutable.HashMap[Int, Int]()` line avoids the bug~~
* ~~similarly, prefixing it with `lazy val x = ` avoids the bug~~
* changing `def v(i: Int, j: Int) = X.fromInts(i, j)` to use `X(X.Y(i), X.Y(j))` directly, avoids the bug
* moving  the `val v10` lines from `object Bug` to inside `wtf()` avoids the bug
* removing the `X.b` field so that there's only one field avoids the bug
* unboxing the `X` fields to just be two `Int`s avoids the bug
* creating a map of less than 5 items avoids the bug (makes sense cos they use different implementations)
* ~~moving everything out of `Bug` into a different object `Z`, then changing the test line to `"wtf" - Z.wtf()` avoids the bug~~

**Comment by japgolly** [comment] 2020-03-10 03:58
Oh and btw, implicitly obvious but this minification while consistently crashing in JS, works when run from JVM.

**Comment by japgolly** [comment] 2020-03-10 04:00
Actually, further reduced slightly:

```scala
import utest._

final case class X(a: X.Y, b: X.Y)

object X {

  final case class Y(value: Int)

  def fromInts(i: Int, j: Int): X =
    X(Y(i), Y(j))
}

object Z {

  def v(i: Int, j: Int) = X.fromInts(i, j)

  val v10 = v(1, 0)
  val v11 = v(1, 1)
  val v12 = v(1, 2)
  val v20 = v(2, 0)
  val v21 = v(2, 1)

  def wtf() = {

    val a = List(v10, v11, v12, v20, v21).iterator.zipWithIndex.toMap

    println(a(v12)) // Prints 2
    println(a(v12)) // Prints 2
    println(a(v12)) // Prints 2
    println(a(v12)) // Throws java.util.NoSuchElementException: key not found: X(Y(1),Y(2))
  }
}

object Bug extends TestSuite {
  override def tests = Tests {
    "wtf" - Z.wtf()
  }
}
```

**Comment by japgolly** [comment] 2020-03-10 04:02
Finally, I'm seeing this with Scala.JS 0.6.32 and 0.6.31 on Scala 2.12.10.

**Comment by gzm0** [comment] 2020-03-10 08:34
I cannot reproduce this without `utest`. @japgolly can you confirm that removing `utest` makes the issue disappear?

**Comment by sjrd** [comment] 2020-03-10 08:46
I also cannot reproduce this without `utest` with Scala 2.12.10, either in the latest 0.6.x branch or master. I used the following code:
```scala
package helloworld

final case class X(a: X.Y, b: X.Y)

object X {
  final case class Y(value: Int)

  def fromInts(i: Int, j: Int): X =
    X(Y(i), Y(j))
}

object Z {
  def v(i: Int, j: Int) = X.fromInts(i, j)

  val v10 = v(1, 0)
  val v11 = v(1, 1)
  val v12 = v(1, 2)
  val v20 = v(2, 0)
  val v21 = v(2, 1)

  def wtf() = {
    val a = List(v10, v11, v12, v20, v21).iterator.zipWithIndex.toMap

    println(a(v12)) // Prints 2
    println(a(v12)) // Prints 2
    println(a(v12)) // Prints 2
    println(a(v12)) // Throws java.util.NoSuchElementException: key not found: X(Y(1),Y(2))
  }
}

object Bug {
  def main(args: Array[String]): Unit =
    println(tests)

  @noinline
  def tests: Any = {
    Z.wtf()
  }
}
```

**Comment by japgolly** [comment] 2020-03-10 09:20
I can't reproduce this without utest. My first thought was maybe this was a utest bug because I believe `Tests { ... }` is actually a macro that does some magic, but I've moved everything out of the utest `TestSuite` so that all it does is a normal method call, so there shouldn't be anything for the macro call to suspiciously transform. It's also a question of power too, is there anything utest could do to affect the internal logic of stdlib `Map.apply`? For those reasons I'm thinking (guessing) that maybe SJS is emitting slightly broken JS for stdlib?

**Comment by sjrd** [comment] 2020-03-10 10:44
I didn't manage to reproduce within the HelloWorld at the tip of 0.6.x branch (by adding uTest 0.7.2 as a dependency and running `helloworld/test`). :-s

**Comment by japgolly** [comment] 2020-03-10 22:04
Damn I was hoping the above would be enough. Ok no worries, let me get a project or maybe even docker image to reproduce this...

**Comment by japgolly** [comment] 2020-03-10 22:33
For the record, here's the error output

```
-------------------------------- Running Tests --------------------------------
2
2
2
X Bug.wtf 2ms 
  java.util.NoSuchElementException: key not found: X(Y(1),Y(2))
    <jscode>.fillInStackTrace__jl_Throwable(webapp-base-test-test-fastopt.js:154737)
    <jscode>.init___T__jl_Throwable__Z__Z(webapp-base-test-test-fastopt.js:154864)
    <jscode>.init___T(webapp-base-test-test-fastopt.js:279760)
    scala.collection.MapLike.$default(webapp-base-test-test-fastopt.js:374469)
    <jscode>.$default__O__O(webapp-base-test-test-fastopt.js:384085)
    scala.collection.MapLike.apply(webapp-base-test-test-fastopt.js:374431)
    <jscode>.apply__O__O(webapp-base-test-test-fastopt.js:384037)
    <jscode>.wtf__V(webapp-base-test-test-fastopt.js:12112)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:156937:26(Unknown)
    <jscode>.apply__O(webapp-base-test-test-fastopt.js:215314)
    <jscode>.dropOutside__F0__O(webapp-base-test-test-fastopt.js:110553)
    <jscode>.run__sci_List__O(webapp-base-test-test-fastopt.js:110644)
    <jscode>.run__sci_List__O(webapp-base-test-test-fastopt.js:110640)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:110152:71(Unknown)
    <jscode>.apply__O(webapp-base-test-test-fastopt.js:215314)
    <jscode>.dropOutside__F0__O(webapp-base-test-test-fastopt.js:110553)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:110143:106(Unknown)
    <jscode>.apply__O(webapp-base-test-test-fastopt.js:215314)
    <jscode>.evaluateFutureTree__Lutest_framework_HTree__s_concurrent_ExecutionContext__s_concurrent_Future(webapp-base-test-test-fastopt.js:110065)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:110079:134(Unknown)
    <jscode>.apply__O__O(webapp-base-test-test-fastopt.js:215342)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:112901:142(Unknown)
    <jscode>.apply__O__O__O(webapp-base-test-test-fastopt.js:215374)
    scala.collection.IndexedSeqOptimized.foldl(webapp-base-test-test-fastopt.js:373910)
    <jscode>.foldLeft__O__F2__O(webapp-base-test-test-fastopt.js:400985)
    <jscode>.traverse__sc_TraversableOnce__F1__scg_CanBuildFrom__s_concurrent_ExecutionContext__s_concurrent_Future(webapp-base-test-test-fastopt.js:112898)
    <jscode>.evaluateFutureTree__Lutest_framework_HTree__s_concurrent_ExecutionContext__s_concurrent_Future(webapp-base-test-test-fastopt.js:110083)
    <jscode>.runAsync__Lutest_Tests__F2__sc_Seq__Lutest_framework_Executor__s_concurrent_ExecutionContext__s_concurrent_Future(webapp-base-test-test-fastopt.js:110203)
    <jscode>.runSuite__sc_Seq__T__Lsbt_testing_EventHandler__Lsbt_testing_TaskDef__s_concurrent_Future(webapp-base-test-test-fastopt.js:153723)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:154034:109(Unknown)
    <jscode>.apply__O__O__O(webapp-base-test-test-fastopt.js:215374)
    <jscode>.execute__Lsbt_testing_EventHandler__ALsbt_testing_Logger__F1__V(webapp-base-test-test-fastopt.js:154114)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:28075:77(Unknown)
    <jscode>.apply__O__O(webapp-base-test-test-fastopt.js:215342)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:26768:29(Unknown)
    <jscode>.apply__O__O(webapp-base-test-test-fastopt.js:215342)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:112775:55(Unknown)
    <jscode>.apply__O__O(webapp-base-test-test-fastopt.js:215342)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:214110:57(Unknown)
    <jscode>.apply__O__O(webapp-base-test-test-fastopt.js:215342)
    <jscode>.run__V(webapp-base-test-test-fastopt.js:214040)
    <jscode>.scala$scalajs$concurrent$QueueExecutionContext$PromisesExecutionContext$$$anonfun$execute$2__sr_BoxedUnit__jl_Runnable__sjs_js_$bar(webapp-base-test-test-fastopt.js:244926)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/webapp-base-test-test-fastopt.js:244943:155(Unknown)
    <jscode>.h(webapp-base-test.js:1)
    <jscode>.file:///tmp/shipreq.sbt/webapp-base-test/js/target/scala-2.12/test-classes/webapp-base-test.js:1:397894(Unknown)
    <jscode>.run(webapp-base-test.js:1)
    <jscode>.d(webapp-base-test.js:1)
```

**Comment by japgolly** [comment] 2020-03-11 02:21
I've provided a reproduction here: https://github.com/japgolly/misc/tree/scalajs-3989

Once you checkout the branch, all you need to do is run `./reproduce` - it will download everything it needs.

I also shrank this further. Here's some new learnings...

* `es6-shims` on test classpath is required to reproduce the bug (see `webapp-base-test/js/src/test/resources/webapp-base-test.js`)
* I've cut out the majority of `es6-shims` so that it's only shimming `Math.imul` (see `webapp-base-test/js/src/test/resources/pre-webpack-source.js`)
* it's necessary to run it through webpack in production mode (config: `frontend/webpack/local.js`); running through webpack in development mode (src: `webapp-base-test/js/src/test/resources/webpack-dev.js`) doesn't produce the bug
* bug occurs with PhantomJS and not with Node

**Comment by sjrd** [comment] 2020-03-11 07:37
Thanks for the repro. Due to the giant SIP meeting, I won't have time to look at it until next week.

Just from the set of things needed to reproduce, my hunch is that the shim for `imul` implemented in es6-shims is either fundamentally buggy, or somehow triggers a bug in PhantomJS. The shim that is built in Scala.js seems to be correct, since not having es6-shims causes the bug not to surface, following your comment.

**Comment by sjrd** [comment] 2020-03-13 11:12
So, with your reproduction, I can reproduce *on Linux* (but not on Windows) using PhantomJS 2.1.1, the last version (but not 1.x), using `sbt test` (what's eventually run by the Docker image IIUC).

However, if I force Scala.js to *always* use its implementation of `Math.imul`, instead of first looking for an existing `Math.imul` (I did that by editing the `-fastopt.js` file by hand), then the bug is not reproducible anymore.

I conclude that the `Math.imul` polyfill of es6-shims is buggy, and ours is not. (It works on Node.js because Node.js does define the correct built-in `Math.imul`, so neither es6-shims' nor Scala.js' polyfill is used.) Therefore, this is not a bug in Scala.js, and there is also no workaround that we could possibly use (we are most definitely not going to detect wrong implementations of `Math.imul` polyfilled by random libraries).

I will therefore close this issue as "invalid" and "separate repo".

**Closed by sjrd** 2020-03-13 11:12 UTC
Labels: needs reproduction

**Comment by japgolly** [comment] 2020-03-14 23:34
Ok cool. Thanks for your time confirming this!

**Comment by japgolly** [comment] 2020-03-14 23:37
Btw, if anyone else comes across this issue in future, the higher-level problem I had was that I was using `airbnb-js-shims` in my tests because some other dependency was using `Map` and `Set`.

A workaround for this is to switch from `airbnb-js-shims` to `core-js`. In my case I simply imported `'core-js/features/map'` and `'core-js/features/set'` and problem avoided.
