### ISSUE TITLE
Web Console does not show Scala sources when using Scala.js 1.x source map

### ISSUE THREAD

**Issue by vmunier** [scala-js/scala-js#4058] opened 2020-05-23 13:51 UTC
Hi,

It looks like the Scala sources are not shown correctly in the browser's web console when using Scala.js 1.x source map.

## steps
* Set up a simple Scala.js project following https://www.scala-js.org/doc/tutorial/basic/index.html
SBT v1.3.7
Scala.js v1.1.0
Scala v2.13.1

* Modify `TutorialApp.scala` to throw an Exception
```
package tutorial.webapp

object TutorialApp {
  def main(args: Array[String]): Unit = {
    println("Hello world!")
    throw new Exception("Tada!")
  }
}
```
* run `sbt fastOptJS`
* open `index-dev.html` in Firefox
* open the Web Console (Tools -> Web Developer -> Web Console)

We can see `java.lang.Exception: Tada!`, but the source points to `scala-js-tutorial-fastopt.js:771:5`

## expectation

I am expecting the source to be `TutorialApp.scala:6:4`

## notes

The source looks correct when using Scala.js v0.6.32:
* Update plugins.sbt to use Scala.js `0.6.32`
* `sbt clean fastOptJS`
* open `index-dev.html` and we can see `TutorialApp.scala:6:4`

I tried with Chrome and it behaves differently:
- with Scala.js v0.6.32: no issue
- with Scala.js v1.1.0: the source is `TutorialApp.scala:6:4` the first time I open the Web Console, but it shows `Throwables.scala:18` after I refresh the page

**Comment by gzm0** [comment] 2020-05-26 20:30
I can reproduce this (including the strange refresh issue).

The full stack trace is:

```
Throwables.scala:18 Uncaught java.lang.Exception: Tada!
    at $c_Ltutorial_webapp_TutorialApp$.main__AT__V (scalajs-tutorial/target/scala-2.13/scala-js-tutorial-fastopt.js:893:95)
    at $s_Ltutorial_webapp_TutorialApp__main__AT__V (scalajs-tutorial/target/scala-2.13/scala-js-tutorial-fastopt.js:886:38)
    at scalajs-tutorial/target/scala-2.13/scala-js-tutorial-fastopt.js:1910:1
    at scalajs-tutorial/target/scala-2.13/scala-js-tutorial-fastopt.js:1911:4

$c_jl_Throwable @ Throwables.scala:18
$c_jl_Exception @ Throwables.scala:375
main__AT__V @ TutorialApp.scala:4
$s_Ltutorial_webapp_TutorialApp__main__AT__V @ TutorialApp.scala:3
(anonymous) @ scala-js-tutorial-fastopt.js:1910
(anonymous) @ scala-js-tutorial-fastopt.js:1911
```

Line `scala-js-tutorial-fastopt.js:893:95` is:

```javascript
    throw $m_sjsr_package$().unwrapJavaScriptException__jl_Throwable__O($ct_jl_Exception__T__(new $c_jl_Exception(), "Tada!"))
```

Column 95 is the `new $c_jl_Exception` call.

I do not know what is happening here...

**Comment by gzm0** [comment] 2020-05-27 06:47
Note that the first time (when the source maps resolve to `TutorialApp.scala`), the position in the stacktrace is also `scala-js-tutorial-fastopt.js:893:95`.

So it seems that the same position is resolved to different positions :-/

**Comment by sjrd** [comment] 2020-05-30 13:33
Even weirder: in step-by-step debugging, the source maps work exactly as expected. So they seem to be correct, except that FF/Chrome won't pick them up for displaying stack traces?

**Comment by ritschwumm** [comment] 2020-05-31 17:19
could this be related to me not seeing scala files in the performance view in chrome any more? this used to work, but broke some months (?) ago. i blamed this on chrome, and spent some hours digging through their bug-tracker, to no avail..

**Comment by ritschwumm** [comment] 2020-06-04 10:50
what's you gut feeling - something wrong with the source maps, or a bug in one or both browsers? my first guess would be something is defined twice in the source maps, or somehow looks to be the same for the browser and this is confusing the browser. if i find time, i'll have a look - maybe i can find something interesting.

**Comment by sjrd** [comment] 2020-06-04 10:53
Source maps are woefully underspecified. It's the worst standard I had to ever work with. So whether something's wrong with the source map or with the browser is anyone's guess, really.

**Comment by ritschwumm** [comment] 2020-06-06 11:36
wow, funny - with the latest chrome, the performance view does show locations in the call tree for my app  again. the locations are not associated to scala files, but at least they are there again.

**Comment by gzm0** [comment] 2020-07-11 17:48
What shall we do with this issue? It seems to be clear that there is a problem somewhere, but it seems to be very unclear how to even determine where to fix it, provided we find the actual underlying problem.

From what I have understood here, it seems that to debug this, our best bet would be to start looking at v8 / chromium source mapping code? :(

**Comment by ritschwumm** [comment] 2020-07-11 19:30
... or whatever firefox does, since that's what the original issue said. the problem with chrome might be related, but it could be something completely different, too. 
my first idea was to do some statistics on the generated source maps in the hope of finding something suspicious like e.g. lots of scala code positions pointing to the same js code positions, or the other way round.

**Comment by ritschwumm** [comment] 2020-07-13 11:17
haha, another data point: today, chromium's performance view displays a few (4 or so) positions as being in scala files, and all the rest as being  inside the generated javascript code. something very weird is going on here...

**Comment by gzm0** [comment] 2020-11-24 06:25
I propose to close this as wontfix for now. This will become actionable if we have more solid standards / evidence that Scala.js is doing something wrong. Any objections?

**Comment by vmunier** [comment] 2020-11-24 08:06
> I propose to close this as wontfix for now. This will become actionable if we have more solid standards / evidence that Scala.js is doing something wrong. Any objections?

That's fine by me.

**Closed** 2020-11-24 11:15 UTC
Labels: wontfix

**Comment by strobe** [comment] 2025-02-26 11:42
@gzm0 what status of this currently? I encountered something similar but it little bit hard to understand is it just I'm doing something wrong (with source maps generation) or it's still some well known issue with stack traces exists.

**Comment by sjrd** [comment] 2025-02-26 12:24
There is renewed interest in standardizing source maps for real here: https://github.com/tc39/ecma426
Hopefully this will give us something more solid to build upon in the foreseeable future.
