### ISSUE TITLE
@ScalaJSDefined function name is empty

### ISSUE THREAD

**Issue by disblader** [scala-js/scala-js#3495] opened 2018-11-21 16:54 UTC
Hello

I believe I may have found a bug (?) in scala.js, but I'm a novice in Javascript, so it might also not be one.

Let's say I define a `@ScalaJSDefined` object as follows:

```scala
@JSExportTopLevel("Potato")
class Potato extends js.Object {
  def someDef(): Int = 3
}
```

I would expect the following to hold if using this class in javascript
```javascript
new Potato().someDef.name === "someDef" // Should be true, but is false
new Potato().someDef.name === "" // Should be false, but is true
```

I noticed that my class generates code as follows
```javascript
function $a_LPotato() {
  if ((!$b_LPotato)) {
    // ... other stuff ... 
    $c_LPotato.prototype.someDef = (function() {
      return $s_LPotato__someDef__LPotato__I(this)
    });
    $b_LPotato = $c_LPotato
  };
  return $b_LPotato
}
```

The lack of function name in the someDef declaration (i.e. `$c_LPotato.prototype.someDef = (function() {..}`) seems to cause the function to have an empty name property. However, the following would cause the name property to be populated correctly.

```javascript
function $a_LPotato() {
  if ((!$b_LPotato)) {
    // ... other stuff ... 
    $c_LPotato.prototype.someDef = (function someDef() {
      return $s_LPotato__someDef__LPotato__I(this)
    });
    $b_LPotato = $c_LPotato
  };
  return $b_LPotato
}
```

Are my expectations misplaced, or is this an issue?

**Comment by sjrd** [comment] 2018-11-21 23:14
It's not a bug, insofar as our spec doesn't make any guarantee about the `name` property of methods in JS classes (nor any other JS function, for that matter).

It could be considered a feature request, but I'm afraid it would have very severe complications if, within the body of `someDef`, the developer tries to read a global variable named `someDef` (this seems silly but when you're a language designer, you have to take *every* corner case into account).

That said, if you choose to emit ECMAScript 2015 code with
```scala
scalaJSLinkerConfig ~= { _.withUseECMAScript2015(true) }
```
in your project's settings, then you'll get the expected `name` property.

It is still not *guaranteed*, though. I'll have to think about whether we can guarantee that in ES 2015 for all cases.

**Comment by disblader** [comment] 2018-11-22 00:30
Thanks for your explanation. 

If I do go down the ECMAScript2015 route, is there any edge cases I should look out for? This really is mostly relevant for fairly simple use cases for me.

**Comment by disblader** [comment] 2018-11-22 00:56
It seems to work directly with `@ScalaJSDefined` classes, like the one in the original question. Unfortunately, it is not in some others, which happen to be rather important for myself:

```scala
@JSExportTopLevel("BigPotato")
object BigPotato {
  // someDef.name will be empty
  @JSExport
  def sampleAnonObj() = new js.Object() {
    def someDef(): Int = 3
  }

  // someDef.name is also empty here
  @JSExport
  def sampleObj() = new PotatoTrait() {
    override def someDef(): Int = 3
  }
}

trait PotatoTrait extends js.Object {
  def someDef(): Int
}
```

I can appreciate this might be one of the weirder edge cases I suppose. Is there anything I can do in this scenario? Any settings that would help me?

Slightly off-topic: Alternatively, the above would be irrelevant for me if I was able to make it such that @ScalaJSDefined classes would not by default create a `constructor` function on the method - is that at all possible?

**Comment by disblader** [comment] 2018-11-22 09:05
When you have an `@ScalaJSDefined` class like Potato above if I instantiate it in javascript and check its members it has 2: `constructor` and `someDef`. 
```scala
@JSExportTopLevel("Potato")
class Potato extends js.Object {
  def someDef(): Int = 3
}
```

If I do a similar thing via anonymous class like with the other example, then it has only one member: `someDef`
```scala
@JSExportTopLevel("BigPotato")
object 
  // someDef.name is also empty here
  @JSExport
  def sampleObj() = new PotatoTrait() {
    override def someDef(): Int = 3
  }
}

trait PotatoTrait extends js.Object {
  def someDef(): Int
}
```

I figure the reason for it is that anonymous classes don't need a constructor, whereas concrete classes do. 

Unfortunately, the above is causing some issues for me when using them with Vue.js, and I'm just a little stumped with how to go about it. Specifically, for one property that I use a @ScalaJSDefined class for (or rather trying to) vue JS takes the generated JS object, goes through its members and adds them to its own generated "component" object. The unfortunate thing here is that it has its own `constructor` method, which then gets overwritten because the @ScalaJSDefined class also has a `constructor`. At the moment my solution is to use a trait with a static method that generates a `js.Dynamic` that conforms to that trait, but having both the signatures and the implementation in one place would be better.

**Comment by sjrd** [comment] 2018-11-26 15:46
`constructor` is a JavaScript thing. It is unavoidable for non-anonymous JS classes. JavaScript will not let a class *not* have a `constructor`.

**Comment by disblader** [comment] 2018-11-26 19:21
Ah, unfortunate. Well, thanks for your help!

**Comment by sjrd** [comment] 2019-01-13 12:38
I'm going to close this as invalid/as-designed, as I don't see what could/should be improved in Scala.js.

**Closed by sjrd** 2019-01-13 12:38 UTC
