### ISSUE TITLE
Outer instance conflict for classes with more than one outer class

### ISSUE THREAD

**Issue by ghik** [scala-js/scala-js#3177] opened 2017-11-10 18:06 UTC
This happens on Scala 2.11.11, ScalaJS 0.6.20.
On Scala 2.12.4 things are fine.

You can see this problem in the wild here: https://travis-ci.org/UdashFramework/udash-core/jobs/299716429 and below is a minimized test case.

```scala
import org.scalatest.FunSuite

class Outer {
  def foo(): Unit = {
    println("foo1")
    println("foo2")
  }

  class BaseInner {
    println("CONSTR OUTER " + Outer.this)
    def bar(): Unit = {
      println("METHOD OUTER " + Outer.this)
      foo()
    }
  }
}

class EvenOuter {
  def evenFoo(): Unit = {
    println("evenfoo1")
    println("evenfoo2")
  }

  val outer = new Outer
  class Inner extends outer.BaseInner {
    println("CONSTR EVEN OUTER " + EvenOuter.this)
    def lol(): Unit = {
      println("METHOD EVEN OUTER " + EvenOuter.this)
      bar()
      evenFoo()
    }
  }
}

class OuterInstancesTest extends FunSuite {
  test("outer instances test") {
    val outer = new EvenOuter
    val inner = new outer.Inner
    inner.lol()
  }
}
```

This is what happens when running this test:

```
CONSTR OUTER io.udash.rpc.Outer@1
CONSTR EVEN OUTER io.udash.rpc.EvenOuter@2
METHOD EVEN OUTER io.udash.rpc.Outer@1 <-- not good, this should be EvenOuter
METHOD OUTER io.udash.rpc.Outer@1
foo1
foo2
[info] OuterInstancesTest:
[info] - outer instances test *** FAILED ***
[info]   scala.scalajs.js.JavaScriptException: TypeError: this.$$outer$f.evenFoo__V is not a function
[info]   at io.udash.rpc.EvenOuter$Inner.lol(file:///home/ghik/idea-workspace/udash-core/rpc/frontend/target/scala-2.11/udash-rpc-frontend-test-fastopt.js:34652:18)
...
```

The class `Inner` has **two** independent outer classes - `Outer` and `EvenOuter`. It seems that in the generated code the outer instance field for both is the same - `$$outer$f`. Because of that, `Outer` instance of the base class overwrites `EvenOuter` instance which leads to a crash when trying to invoke `EvenOuter.this.evenFoo()`

**Comment by sjrd** [comment] 2017-11-10 23:04
This is a duplicate of https://github.com/scala-js/scala-js/issues/2382. Fixed for 2.12+ only in Scala.js 0.6.x, and fixed for all versions of Scala in Scala.js 1.x.

It's a won't fix for Scala 2.10 and 2.11 in the 0.6.x branch for binary compatibility reasons.

**Closed by sjrd** 2017-11-10 23:04 UTC

**Comment by ghik** [comment] 2017-11-10 23:10
Cool, although I think it would be nice to add some compilation warning or error in 2.10/2.11 to save people some debugging/googling time :)

**Comment by sjrd** [comment] 2017-11-10 23:15
That's an interesting idea. I'll have to think about its feasibility.

**Comment by ghik** [comment] 2017-11-11 08:36
The problem with this particular bug is that the runtime error is so enigmatic that you can't find the reported issue until you actually understand what's causing it. Even a better runtime error message would help a lot.
