### ISSUE TITLE
Formatting a byte as a hexadecimal integer produces an incorrect result for a negative value

### ISSUE THREAD

**Issue by integralla** [scala-js/scala-js#4975] opened 2024-04-05 16:07 UTC
When formatting a byte encoded as a negative value to a hexadecimal integer, Scala.js produces a different/invalid value compared with the JVM.

```scala
String.format("%02x", -38.byteValue) 
```
- JVM: `da`
- Scala.js: `ffffffda`

As a work-around, the byte value can first be converted to an unsigned int:

```scala
String.format("%02x", -38.byteValue & 0xff))
```

Scala Version: 3.3.1
Scala.js Version: 1.15.0

**Comment by gzm0** [comment] 2024-04-05 16:24
Hrm. I was going to write that this is a direct consequence of "Runtime type tests are based on values" documented here: https://www.scala-js.org/doc/semantics.html

However, one would expect the JVM result in this case. It seems that the relevant code simply only considers ints and longs:

https://github.com/scala-js/scala-js/blob/b5158b2fdddd38481cca9b44eeeaf4fce5a7411a/javalib/src/main/scala/java/util/Formatter.scala#L433-L442

I vaguely recall that we needed to make this decision a long time ago, but I do not remember why we settled on this. I'll try and dig in the commit history.

**Comment by gzm0** [comment] 2024-04-05 16:33
Commit removing the handling of Byte/Short: 000fb141b309e7567f2458e32f003281122948a5

**Comment by sjrd** [comment] 2024-04-05 17:18
This is working as designed. The behavior is indeed a consequence of value-based type tests for numeric types. The fact that it behaves like `Int` instead of `Byte`/`Short` is the better trade-off. As mentioned in the issue description, portable behavior is recoverable by converting to `Int`; if we had chosen the other way around, no workaround would exist for the `Int` behavior.

**Comment by sjrd** [comment] 2024-04-05 17:18
Also Duplicate of #2206.

**Closed by sjrd** 2024-04-05 17:18 UTC
