### ISSUE TITLE
j.l.Float.parseFloat's result is 1 ULP off of the best approximation in some cases

### ISSUE THREAD

**Issue by plokhotnyuk** [scala-js/scala-js#4035] opened 2020-05-07 17:42 UTC
Code to reproduce:
```
"1725440439005216752".toFloat.toString
```

Expected result:
```
1.72544037E18
```

Actual result:
```
1725440507724693500
```
 
The difference is 1 ULP but it can be critical for some use cases.

Below is how it works on JVM:
```
scala> "1725440439005216752".toFloat
res0: Float = 1.72544037E18

scala> "1725440507724693500".toFloat
res1: Float = 1.72544051E18

scala> java.lang.Float.floatToRawIntBits("1725440507724693500".toFloat).toHexString
res2: String = 5dbf8ff8

scala> java.lang.Float.floatToRawIntBits("1725440439005216752".toFloat).toHexString
res3: String = 5dbf8ff7
```

**Comment by sjrd** [comment] 2020-05-07 17:47
Did you read "Floats can behave as Doubles by default" at https://www.scala-js.org/doc/semantics.html ? AFAICT this happens because of the non-strict floats by default, which is as designed.

**Comment by plokhotnyuk** [comment] 2020-05-07 17:50
I've tried with `scalaJSLinkerConfig ~= { _.withSemantics(_.withStrictFloats(true)) }` and it doesn't help.

**Comment by sjrd** [comment] 2020-05-08 15:50
OK so our `parseFloat()` is indeed not completely consistent with the one on the JVM :( For what it's worth, it *is* consistent with `"1725440439005216752".toDouble.toFloat`. In other words, `"1725440439005216752".toFloat` and `"1725440439005216752".toDouble.toFloat` are not self-consistent on the JVM:
```scala
scala> "%f".format("1725440439005216752".toFloat)
val res0: Float = 1725440370285740030.000000

scala> "%f".format("1725440439005216752".toDouble.toFloat)
val res1: Float = 1725440507724693500.000000
```
Apparently direct `.toFloat` rounds *down* to the closest float, while going through `.toDouble.toFloat` rounds *up*.

Checking just `.toDouble`:
```scala
scala> "%f".format("1725440439005216752".toDouble)
val res2: String = 1725440439005216770.000000
```
which turns to be *exactly* half-way between `res0` and `res1`:
```scala
scala> "%f".format(("1725440439005216752".toFloat.toDouble + "1725440439005216752".toDouble.toFloat.toDouble) / 2.0)
val res3: String = 1725440439005216770.000000
```
And well, that's where we get to an explanation: the original string is closer to `res2` than to `res0` (hence `toDouble` chooses `res2`), but it is closer to `res0` than to `res1` (hence `toFloat` chooses `res0`)! But when it's already at `res2` and we do `toFloat`, it rounds *up* to `res1` (it has to choose one option, and the rules for `double-to-float` say it must be up in this case, both on JVM and JS). Since in Scala.js we only receive `parseFloat` from the JS library, which actually parses to *double*-precision, and we *then* apply `fround` (`.toFloat`), we end up with `res1`.

Can we fix it? That's unclear. It might require actually reimplementing float parsing from scratch, which would not only be a lot of code (parsing is hard) but also significantly slower than the built-in `parseFloat`. 😐

**Comment by gzm0** [comment] 2020-05-09 07:49
Wouldn't it be enough to implement a special float rounding method that rounds down? And then simply do: `x.toFloat = myFround(parseFloat(x))`.

If up and down actually means up and down (and not towards away from zero), wouldn't `myFround(x) = -fround(-x)`?

**Comment by plokhotnyuk** [comment] 2020-05-09 11:30
No inconsistency here. It is just a double rounding happens when `toDouble.toFloat` is called:
```
scala> BigInt("1725440439005216752").underlying.toString(2)
res0: String = 1011111110001111111101110111111111111111111111111111111110000

scala> "1725440439005216752".toLong
res1: Long = 1725440439005216752

scala> "1725440439005216752".toLong.toBinaryString
res3: String = 1011111110001111111101110111111111111111111111111111111110000

scala> "1725440439005216752".toDouble.toLong.toBinaryString
res4: String = 1011111110001111111101111000000000000000000000000000000000000

scala> "1725440439005216752".toFloat.toLong.toBinaryString
res5: String = 1011111110001111111101110000000000000000000000000000000000000

scala> "1725440439005216752".toDouble.toFloat.toLong.toBinaryString
res6: String = 1011111110001111111110000000000000000000000000000000000000000
```
Jsoniter-scala has fast and mid paths for exact parsing of floats from the decimal representation when mantissa is less than 60-bits. But for longer numbers it falls back to standard `toFloat`.
I have tested it ad-hoc using code bellow and it seems quite competitive with the original `parseFloat` on Node.js. Also, in this code the ad-hoc implementation for exact serialization was tested too:
```
object Float extends org.scalajs.benchmark.Benchmark {
  import com.github.plokhotnyuk.jsoniter_scala.core._

  private val float = new ThreadLocal[Array[Byte]] with JsonValueCodec[Float] {
    def parse(x: String): Float = {
      val buf = get
      val len = x.length
      var i = 0
      while (i < len) {
        buf(i) = x.charAt(i).toByte
        i += 1
      }
      readFromSubArray(buf, 0, len)(this)
    }

    def stringify(x: Float): String =
      if (java.lang.Float.isFinite(x)) {
        val buf = get
        val len = writeToSubArray(x, buf, 0, 32)(this)
        new String(buf, 0, len)
      } else java.lang.Float.toString(x)

    override def decodeValue(in: JsonReader, default: Float): Float = in.readFloat()

    override def encodeValue(x: Float, out: JsonWriter): Unit = out.writeVal(x)

    override def initialValue(): Array[Byte] = new Array[Byte](32)

    override val nullValue: Float = 0.0f
  }

  private val allBenches = Array[org.scalajs.benchmark.Benchmark](
    new Benchmark[Float]("float-parse-original-1") {
      def runImpl(): Float = "1725440439005216752".toFloat
    },
    new Benchmark[Float]("float-parse-proposed-1") {
      def runImpl(): Float = float.parse("1725440439005216752")
    },
    new Benchmark[Float]("float-parse-original-2") {
      def runImpl(): Float = "1725440439.005216752".toFloat
    },
    new Benchmark[Float]("float-parse-proposed-2") {
      def runImpl(): Float = float.parse("1725440439.005216752")
    },
    new Benchmark[Float]("float-parse-original-3") {
      def runImpl(): Float = "17254.40439".toFloat
    },
    new Benchmark[Float]("float-parse-proposed-3") {
      def runImpl(): Float = float.parse("17254.40439")
    },
    new Benchmark[Float]("float-parse-original-4") {
      def runImpl(): Float = "17254".toFloat
    },
    new Benchmark[Float]("float-parse-proposed-4") {
      def runImpl(): Float = float.parse("17254")
    },
    new Benchmark[Float]("float-parse-original-5") {
      def runImpl(): Float = "1.7".toFloat
    },
    new Benchmark[Float]("float-parse-proposed-5") {
      def runImpl(): Float = float.parse("1.7")
    },
    new Benchmark[String]("float-stringify-original-1") {
      def runImpl(): String = 1.72544037E18f.toString
    },
    new Benchmark[String]("float-stringify-proposed-1") {
      def runImpl(): String = float.stringify(1.72544037E18f)
    },
    new Benchmark[String]("float-stringify-original-2") {
      def runImpl(): String = 1725440439f.toString
    },
    new Benchmark[String]("float-stringify-proposed-2") {
      def runImpl(): String = float.stringify(1.72544037E18f)
    },
    new Benchmark[String]("float-stringify-original-3") {
      def runImpl(): String = 17254.40439f.toString
    },
    new Benchmark[String]("float-stringify-proposed-3") {
      def runImpl(): String = float.stringify(17254.40439f)
    },
    new Benchmark[String]("float-stringify-original-4") {
      def runImpl(): String = 17254f.toString
    },
    new Benchmark[String]("float-stringify-proposed-4") {
      def runImpl(): String = float.stringify(17254f)
    },
    new Benchmark[String]("float-stringify-original-5") {
      def runImpl(): String = 1.7f.toString
    },
    new Benchmark[String]("float-stringify-proposed-5") {
      def runImpl(): String = float.stringify(1.7f)
    }
  )

  override def main(args: Array[String]): Unit = for (bench <- allBenches) bench.main(args)

  def run(): Unit = ???
}

abstract class Benchmark[A](val name: String) extends org.scalajs.benchmark.Benchmark {
  override def report(): String = name + ';' + super.report()

  def runImpl(): A

  def run(): Unit = if (runImpl() == null) throw new AssertionError()
}
```
Here are results:
```
float-parse-original-1;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.3572410613896801;0.0005677213056332895
float-parse-proposed-1;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.4513021132453354;0.0007641042568813265
float-parse-original-2;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.3836510111346361;0.0004962188044630542
float-parse-proposed-2;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.502384252715442;0.0005888723203847167
float-parse-original-3;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.36292188584911067;0.0012780125790230199
float-parse-proposed-3;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.3860662783670665;0.0017093434375278663
float-parse-original-4;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.2828611434454142;0.0008301380804091708
float-parse-proposed-4;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.31697487769379806;0.0012365497411122573
float-parse-original-5;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.33236390422630535;0.0006917437578871621
float-parse-proposed-5;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.2896473534479211;0.0013488039115068591
float-stringify-original-1;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.20133578570204996;0.0004738754355726278
float-stringify-proposed-1;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.8655509037814398;0.000596409664962737
float-stringify-original-2;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.20200527095814622;0.0005073475107379033
float-stringify-proposed-2;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.8709211472351153;0.0006203773195573935
float-stringify-original-3;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.2008606353082;0.00034059028748996325
float-stringify-proposed-3;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.7912777685532606;0.003436410933452108
float-stringify-original-4;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.20324164130865643;0.0005295262796144453
float-stringify-proposed-4;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.5930769706567133;0.0007414262157546941
float-stringify-original-5;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.20272807839639306;0.00010318290479100037
float-stringify-proposed-5;json;Scala.js;es2015;prod;opt;gcc;Node.js;0.677278676615745;0.0004581900487469975
```
When re-implemented for Scala.js more performance can be squeezed. But in any case it will not be enough to opt-in it by default.

**Comment by sjrd** [comment] 2020-05-09 14:49
> Wouldn't it be enough to implement a special float rounding method that rounds down? And then simply do: `x.toFloat = myFround(parseFloat(x))`.

The problem is that, once you've got the double, you don't know whether you need to round up or down. Because your original string number might be *above* the middle point, closer to the middle point than to the next up float (instead of *below* the middle point, closer to the middle point than to the next down float). Do just from the parsed double, you cannot know the correct answer. You need to work from the original string.

**Comment by sjrd** [comment] 2020-05-09 16:06
> Jsoniter-scala has [fast and middle paths for exact parsing of floats from the decimal representation](https://github.com/plokhotnyuk/jsoniter-scala/blob/bc121d8572022305c8e38d62d5e9f9c9db9cfed2/jsoniter-scala-core/js/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1493-L1648) when truncated mantissa bits are not close to the [halfway (or middle)](https://www.exploringbinary.com/the-shortest-decimal-string-that-round-trips-examples/) point where it falls back to standard `toFloat`.

Aren't we precisely having issues because we're close to the halfway point, here? So if your algorithm falls back to `parseFloat` if it's too close the halfway point, how would we make our `parseFloat` more correct based on that code?

> Also, in this code an implementation for [exact serialization for floats](https://github.com/plokhotnyuk/jsoniter-scala/blob/6b093e0816794ab310fd2adad1c5cb780bdca4e0/jsoniter-scala-core/js/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L1837-L2040) was tested too:

Fixing `parseFloat` is one thing. Changing `toString` is out of scope. We simply cannot change the `toString()` of primitive numbers, and I'm not going to make `java.lang.Float.toString(f)` inconsistent with `f.toString()`.

**Comment by gzm0** [comment] 2020-05-09 16:45
> Aren't we precisely having issues because we're close to the halfway point, here? So if your algorithm falls back to parseFloat if it's too close to the halfway point, how would we make our parseFloat more correct based on that code?

The way I understand @plokhotnyuk's comment is that it uses `parseFloat` if it doesn't yield a wrong result.

> Changing toString is out of scope.

It's a bit unfortunate that there seems to be *no* way to convert a float to a string representation that will yield the same value when parsed. OTOH, using decimals strings to store IEEE floats is probably not ideal in the first place. But then again, if that is the case, why bother with proper parsing :(

**Comment by sjrd** [comment] 2020-05-09 16:55
> > Changing toString is out of scope.
> 
> It's a bit unfortunate that there seems to be _no_ way to convert a float to a string representation that will yield the same value when parsed. OTOH, using decimals strings to store IEEE floats is probably not ideal in the first place. But then again, if that is the case, why bother with proper parsing :(

Er ... unless shown otherwise, we don't have *that* problem. If you start with an `f: Float`, I'm pretty sure it's always true that `f.equals(f.toString().toFloat)`.

**Comment by gzm0** [comment] 2020-05-11 06:38
> Er ... unless shown otherwise, we don't have that problem.

Right. Sorry, that was a bit premature indeed. I thought we might have that problem because of inaccuracies when converting to strings, but binary to decimal representation should be non-lossy / not require an infinite, periodic decimal representation.

**Comment by sjrd** [comment] 2020-05-11 09:49
> > Aren't we precisely having issues because we're close to the halfway point, here? So if your algorithm falls back to parseFloat if it's too close to the halfway point, how would we make our parseFloat more correct based on that code?
> 
> The way I understand @plokhotnyuk's comment is that it uses `parseFloat` if it doesn't yield a wrong result.

Rereading this, this is not how I understand it. IIUC `parseFloat` always gives the correct result (on the JVM) but is slow. So @plokhotnyuk has a faster implementation of `parseFloat` that works for most cases, but it falls back to the JDK `parseFloat` for corner cases.

**Comment by plokhotnyuk** [comment] 2020-05-11 13:15
@sjrd You are right that round-trip conversion of float values is stable in both JS and JVM worlds and following test doesn't print any failures:
```
(0 to Int.MaxValue).foreach { i =>
  val f = java.lang.Float.intBitsToFloat(i)
  if (java.lang.Float.isFinite(f) && f != f.toString.toFloat) println(s"i=$i, f=$f")
}
```
So, the originally reported issue is just a double round-up when parsing floats from string representation with too long mantissas that exceed 17 digits.

Also, on JVM I have run a test through all floats (serialized to a string by JVM's `toString`) for jsoniter-scala's implementation `readFloat` and there wasn't any fallback to slow Java's implementation. Even all tested double values (serialized by JVM too) do not fall to the slow path.

But, that is not a case on Node.js. It serializes some floats with so long mantissa that exceeds the capacity of doubles. As an example, `1.0000001f` is serialized as `1.00000017881393432617187499`.

So, if we consider other cases of round-trip conversions though the string representation between client and server parts (JS -> JVM -> JS) then there are could be other reasons to use jsoniter-scala's `readFloat` and `writeVal(x: Float)`: fewer bytes to send/receive and fewer cycles to parse and serialize on JVM side.

**Comment by sjrd** [comment] 2020-05-11 13:31
> But, that is not a case on Node.js. It serializes some floats with so long mantissa that exceeds the capacity of doubles. As an example, `1.0000001f` is serialized as `"1.00000017881393432617187499"`.

Yes, that's because `f.toString()` is effectively `f.toDouble.toString()`. And as I said above, we *cannot* change `f.toString()`. So if transferring less bytes for a particular serialization mechanism is desired, the serialization has to use a different method than `f.toString()`. But that's up to the serialization library's discretion; it's out of scope for this repo.

**Closed** 2021-02-22 13:52 UTC
Labels: bug
