### ISSUE TITLE
Match Error (Nil, _).

### ISSUE THREAD

**Issue by Josef-Vonasek** [scala-js/scala-js#3885] opened 2019-11-26 11:10 UTC
Our azure pipelines tests on Linux and Mac fail with match error:
```
[info]  - testing a property *** FAILED ***
[info]   scala.MatchError: (List(),List()) (of class scala.Tuple2)
[info]   at @Error(Unknown Source)
[info]   at /__w/1/s/common/scala/project/.js/target/scala-2.12/project-test-fastopt.js:43656:14@$c_s_MatchError.fillInStackTrace__jl_Throwable(Unknown Source)
[info]   at /__w/1/s/common/project/specialization/.js/target/scala-2.12/project-test-fastopt.js:43774:10@$c_s_MatchError.init___T__jl_Throwable__Z__Z(Unknown Source)
[info]   at /__w/1/s/common/project/specialization/.js/target/scala-2.12/project-test-fastopt.js:97648:58@$c_s_MatchError.init___O(Unknown Source)
```

I have tracked it down to this piece of code:
```scala
// cats.data.NonEmptyList
  def zipWith[B, C](b: NonEmptyList[B])(f: (A, B) => C): NonEmptyList[C] = {

    @tailrec
    def zwRev(as: List[A], bs: List[B], acc: List[C]): List[C] = (as, bs) match {
      case (Nil, _)           => acc
      case (_, Nil)           => acc
      case (x :: xs, y :: ys) => zwRev(xs, ys, f(x, y) :: acc)
    }

    NonEmptyList(f(head, b.head), zwRev(tail, b.tail, Nil).reverse)
  }
```
It seems that the js engine believes that the pattern  `(Nil, _)` does not cover `(List(), List())`.

**Comment by gzm0** [comment] 2019-11-26 11:32
Thanks for the report. What Scala.js and Scala version is this?

**Comment by Josef-Vonasek** [comment] 2019-11-26 11:36
scalacVersion = "2.12.10"
graalVersion  = "19.2.0.1"
scalajsVersion = "0.6.29"

**Comment by gzm0** [comment] 2019-11-26 11:46
Ah, so this is not related to RC1? What *change* in your pipeline caused this?

**Comment by Josef-Vonasek** [comment] 2019-11-26 11:52
What is RC1? My pipelines were passing when doing `sbt root/test` with

```scala
lazy val root =crossProject ...
  .aggregate(project.jvm, project.js)
```
Then I changed it to just
```scala
lazy val root =crossProject ...
  .aggregate(project.jvm)
```
and created two pipeline jobs `sbt root/test`, `sbt projectJS/test`

**Comment by gzm0** [comment] 2019-11-26 12:02
> What is RC1?

Ah, sorry. By RC1 I meant Scala.js 1.0.0-RC1 which we [just announced][1].

Hum, are you sure about that change? `crossProject` does not support `aggregate` on non-CrossProjects. Please provide a [minimal working example][2] so we are able to reproduce this.

[1]: https://www.scala-js.org/news/2019/11/26/announcing-scalajs-1.0.0-RC1/
[2]: https://en.wikipedia.org/wiki/Minimal_working_example

**Comment by Josef-Vonasek** [comment] 2019-11-26 12:08
Oops, the root is just ordinary `project`.

**Comment by sjrd** [comment] 2019-11-26 12:24
Could you provide a minimal reproduction, *including the build* (since it's a build change that caused the issue), and including the build that works *and* the build that doesn't work, please?

**Comment by gzm0** [comment] 2019-11-28 09:11
Closing because there was no follow-up. Feel free to re-open if you have further informatin.

**Closed** 2019-11-28 09:11 UTC
Labels: can't reproduce
