### ISSUE TITLE
require(condition, something) Uncaught Error when condition fails instead of

### ISSUE THREAD

**Issue by antonkulaga** [scala-js/scala-js#2415] opened 2016-05-26 18:43 UTC
When in my code I have something like
```scala
require(condition, "some error message") 
```
When it fails instead of the error message I see Uncaught Error in the chrome console

**Comment by gzm0** [comment] 2016-06-05 20:36
Duplicate of #2383?

**Closed** 2016-06-05 21:28 UTC
Labels: duplicate
