### ISSUE TITLE
NPE with a scalajsdefined class

### ISSUE THREAD

**Issue by dispalt** [scala-js/scala-js#3022] opened 2017-06-16 19:49 UTC
I think I found a legitimate bug based on some compiler NPE I observed.  Here's exactly what's happening when I get the NPE and if I comment it out I do not get the NPE.  I am using version 

0.6.17, 2.12.2

```scala
@ScalaJSDefined
trait Opts[R] extends js.Object {
    val dataSource: js.Array[R]
    val rowKey: js.UndefOr[String | js.Function1[R, String]] = js.undefined
  }
```

if I instantiate that class and use it as follows I get the NPE.  If I comment the second line out, I do not get the NPE.

```scala
new Opts[SangriaEdge[PolicyFrag]] {
  override val rowKey = js.defined((r: SangriaEdge[PolicyFrag]) => r.cursor)
  val dataSource = foo
}
```

if I also change that line to something like this, it works.
```scala
          override val rowKey = { r: SangriaEdge[PolicyFrag] =>
            r.cursor
          }: js.Function1[SangriaEdge[PolicyFrag], String]
```

This is all embedded in a production app, so sorry I don't have more context.  Here is the NPE, any thoughts?

```scala
Caused by: java.lang.NullPointerException: null
        at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:254)
        at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:83)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformTrees$1(Trees.scala:2559)
        at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2559)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1351)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:372)
```

**Comment by sjrd** [comment] 2017-06-16 22:06
Definitely looks like a bug. Could you provide a dependency-free reproduction? Now you refer to `SangriaEdge` which is not self-contained.

**Comment by sjrd** [comment] 2017-06-21 19:37
I cannot reproduce the crash. Using 0.6.x and Scala 2.12.2, and replacing `SangriaEdge[PolicyFrag]` by `Int`:
```scala
import scala.scalajs.js
import js.annotation._
import js.|

@ScalaJSDefined
trait Opts[R] extends js.Object {
  val dataSource: js.Array[R]
  val rowKey: js.UndefOr[String | js.Function1[R, String]] = js.undefined
}

object HelloWorld extends js.JSApp {
  def main() {
    new Opts[Int] {
      override val rowKey = js.defined((r: Int) => r.toString)
      val dataSource = js.Array()
    }
  }
}
```
I get the following compile error:
```
[error] C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\HelloWorld.scala:21: type mismatch;
[error]  found   : Int => String
[error]  required: String | scala.scalajs.js.Function1[Int,String]
[error]       override val rowKey = js.defined((r: Int) => r.toString)
[error]                                                 ^
[error] one error found
```
which is perfectly reasonable. Even with SAM support of 2.12, there's no way the type inference can see through the union type to apply the SAM conversion on the function.

**Comment by sjrd** [comment] 2017-07-07 11:35
Closing this as I cannot reproduce it. The issue can be reopened with a stand-alone reproduction.

**Closed by sjrd** 2017-07-07 11:35 UTC
Labels: bug, can't reproduce

**Comment by dispalt** [comment] 2017-07-07 17:22
Yeah I'm sorry I dropped the ball, If I run into it, I'll reopen.
