### ISSUE TITLE
RPCCore$RPCException thrown during test for Scala.js project if ScalaMock added

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#3174] opened 2017-11-08 12:55 UTC
I firstly reported this to https://github.com/paulbutcher/ScalaMock/issues/205. But from stack trace, it might be a bug in scala-js, so I post here. 

## steps
Since it requires a lots of sbt configuration, I made a small project that reproduces the issue.

1.  Clone  https://github.com/exoego/scalamock-fail-with-scalajs
2.  Run `sbt`
3.  Run `test` command

## problem
If ScalaMock is added as dependency, even if ScalaMock is not used in the code,  ScalaTest could not run any test for ScalaJS project. 

Test is aborted by `org.scalajs.testcommon.RPCCore$RPCException`, which is caused by `scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'FooTest' of undefined` according to stack trace.

```
sbt:foo> test
[info] Compiling 1 Scala source to C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\test-classes ...
[info] Done compiling.
[info] Fast optimizing C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js
[error] org.scalajs.testcommon.RPCCore$RPCException
[error]         at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:54)
[error]         at scala.Option.foreach(Option.scala:257)
[error]         at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:52)
[error]         at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:32)
[error]         at org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:48)
[error]         at org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:32)
[error]         at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:34)
[error] Caused by: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'FooTest' of undefined
[error]         at org.scalajs.testinterface.TestUtils$.deepSelect(C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js:4929)
[error]         at org.scalajs.testinterface.TestUtils$.newInstance(C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js:4880)
[error]         at org.scalatest.tools.TaskRunner.executionFuture(C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js:19877)
[error]         at org.scalatest.tools.TaskRunner.execute(C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js:19839)
[error]         at org.scalajs.testinterface.internal.Slave.execute(C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js:5359)
[error]         at <jscode>.{anonymous}()(C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js:5518)
[error]         at scala.scalajs.runtime.AnonFunction1.apply(C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js:27089)
[error]         at <jscode>.{anonymous}()(C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js:12448)
[error]         at scala.scalajs.runtime.AnonFunction1.apply(C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js:27089)
[error]         at <jscode>.{anonymous}()(C:\Users\xxxxxxxx\IdeaProjects\scalamock-fail-with-scalajs\target\scala-2.12\foo-test-fastopt.js:26381)
[error] Could not run test foo.FooTest: org.scalajs.testcommon.RPCCore$RPCException
(...)
```

## expectation
ScalaTest should run tests for ScalaJS project.

## notes

If ScalaMock is removed from dependencies, error does not occur. 
I have tried the following combinations. However, I could not find a problrem-free combination...

sbt \ scala-js  | 0.6.21 | 0.6.20 | 0.6.19 | 0.6.18
-- | -- | -- | -- | --
1.0.3 | x | x | x | N/A
1.0.2 | x | x | x | N/A
0.13.16 | x | x | x | x (scala 2.12.3)
0.13.15 | N/A | N/A | x | x  (scala 2.12.3)

* "x" means same error happens.
* Unless noted, scala 2.12.4 is used.
* ScalaTest 3.0.4 and ScalaMock 3.6.0 are used

**Comment by gzm0** [comment] 2017-11-08 13:20
The stacktrace is caused by Scala.js not being able to load `foo.FooTest`. This might have two reasons:

- `foo.FooTest` is not on the classpath (yet sbt detects it, so there might be some classpath config mismatch).
- `foo.FooTest` is missing relevant annotations to make the test dynamically discoverable `@JSExportAll` or `@EnableReflectiveInstantiation` depending on the version of the testing framework.

From what I have seen so far, I find the second option more likely. But it needs investigation. `scalajsp` output for `foo.FooTest` would be helpful.

**Comment by exoego** [comment] 2017-11-08 13:55
Unfortunately, adding `@JSExportall` or `@EnableReflectiveInstantiation` does not resolve the error...

However, using `scalajsp` against `FooTest.sjsir` shows some hints.

If ScalaMock added...

```bash
$ scalajsp FooTest.sjsir                                                                                                                          
class Lfoo_FooTest extends Lorg_scalatest_FunSuite {                                                                                                                                                                                         
  @hints(1) def $$anonfun$new$1__p2__Lorg_scalatest_compatible_Assertion(): Lorg_scalatest_compatible_Assertion = {                                                                                                                          
    val $$org_scalatest_assert_macro_expr: Lorg_scalactic_Bool = mod:Lorg_scalactic_Bool$.simpleMacroBool__Z__T__Lorg_scalactic_Prettifier__Lorg_scalactic_Bool(true, "", mod:Lorg_scalactic_Prettifier$.$default__Lorg_scalactic_Prettifier(
));                                                                                                                                                                                                                                          
    this.assertionsHelper__Lorg_scalatest_Assertions$AssertionsHelper().macroAssert__Lorg_scalactic_Bool__O__Lorg_scalactic_Prettifier__Lorg_scalactic_source_Position__Lorg_scalatest_compatible_Assertion($$org_scalatest_assert_macro_expr
, "", mod:Lorg_scalactic_Prettifier$.$default__Lorg_scalactic_Prettifier(), new Lorg_scalactic_source_Position().init___T__T__I("FooTest.scala", "Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at compile time to
 enable this feature.", 12))                                                                                                                                                                                                                 
  }                                                                                                                                                                                                                                          
  def init___() {                                                                                                                                                                                                                            
    this.Lorg_scalatest_FunSuite::init___();                                                                                                                                                                                                 
    this.test__T__sc_Seq__F0__Lorg_scalactic_source_Position__V("1 is 1", new sjs_js_WrappedArray().init___sjs_js_Array([]), new sjsr_AnonFunction0().init___sjs_js_Function0((lambda<$this: Lfoo_FooTest = this>() = {                      
      $this.$$anonfun$new$1__p2__Lorg_scalatest_compatible_Assertion()                                                                                                                                                                       
    })), new Lorg_scalactic_source_Position().init___T__T__I("FooTest.scala", "Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at compile time to enable this feature.", 11))                                       
  }                                                                                                                                                                                                                                          
}                                                                                                                                                                                                                                            
 ```                                                                                                                                                                 


If ScalaMock removed...
```bash
class Lfoo_FooTest extends Lorg_scalatest_FunSuite {
  @hints(1) def $$anonfun$new$1__p2__Lorg_scalatest_compatible_Assertion(): Lorg_scalatest_compatible_Assertion = {
    val $$org_scalatest_assert_macro_expr: Lorg_scalactic_Bool = mod:Lorg_scalactic_Bool$.simpleMacroBool__Z__T__Lorg_scalactic_Prettifier__Lorg_scalactic_Bool(true, "", mod:Lorg_scalactic_Prettifier$.$default__Lorg_scalactic_Prettifier());
    this.assertionsHelper__Lorg_scalatest_Assertions$AssertionsHelper().macroAssert__Lorg_scalactic_Bool__O__Lorg_scalactic_Prettifier__Lorg_scalactic_source_Position__Lorg_scalatest_compatible_Assertion($$org_scalatest_assert_macro_expr, "", mod:Lorg_scalactic_Prettifier$.$default__Lorg_scalactic_Prettifier(), new Lorg_scalactic_source_Position().init___T__T__I("FooTest.scala", "Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at compile time to enable this feature.", 12))
  }
  def init___() {
    this.Lorg_scalatest_FunSuite::init___();
    this.test__T__sc_Seq__F0__Lorg_scalactic_source_Position__V("1 is 1", new sjs_js_WrappedArray().init___sjs_js_Array([]), new sjsr_AnonFunction0().init___sjs_js_Function0((lambda<$this: Lfoo_FooTest = this>() = {
      $this.$$anonfun$new$1__p2__Lorg_scalatest_compatible_Assertion()
    })), new Lorg_scalactic_source_Position().init___T__T__I("FooTest.scala", "Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at compile time to enable this feature.", 11))
  }
  export "foo.FooTest"() {
    this.Lfoo_FooTest::init___()
  }
}
```
where `export ...` exists.

**Comment by gzm0** [comment] 2017-11-08 15:47
The missing `export` is definitely the culprit. The annotation should have been simply `@JSExport`. But we should investigate why the export does get nuked.

**Comment by robby-phd** [comment] 2018-02-25 15:33
I encountered a similar issue when using ScalaTest 3.0.4, even without ScalaMock.
If I use ScalaTest 3.0.1, however, it works fine (in my project).

Here are the steps to reproduce it in my case (Java 8 or 9):

1. `git clone -b scalajs-rpcexception --recurse-submodules https://github.com/sireum/v3.git sireum-v3 && cd sireum-v3 && JAVA_OPTS="-Xmx2G" sbt 'project runtime-library-js' test`
   This produces RPCExceptions.

2. `scalajsp runtime/library/js/target/scala-2.12/test-classes/org/sireum/BuiltInTypesTest.sjsir | grep export`
   This turns up nothing.

3.  [Downgrading to ScalaTest 3.0.1](https://github.com/sireum/v3/commit/88705e89c9c4fa6990edab288b7ecddce660783f): `git checkout 22619bb && JAVA_OPTS="-Xmx2G" sbt clean 'project runtime-library-js' test`
    All tests now pass.

4. `scalajsp runtime/library/js/target/scala-2.12/test-classes/org/sireum/BuiltInTypesTest.sjsir | grep export`
    This turns up `  export "org.sireum.BuiltInTypesTest"() {`

For a more robust reproduction without Java, Node.js, etc., installed, replace occurrences of `sbt` in the above with `bin/sbt-launch.sh` (scalajsp is still required for steps 2 & 4).

**Comment by sjrd** [comment] 2018-06-19 12:46
@robby-phd Somehow your `runtime-library-js` project *depends on* your `runtime-library-jvm` project. This means that you end up with *two* versions of ScalaTest on the compilation classpath: one for JS, with the proper `@EnableReflectiveInstantiation` that would cause Scala.js to generate the proper metadata for `TestUtils` to load your test classes, *and one for the JVM*, which of course does *not* have the annotation.

Depending on the order of resolution of your dependencies, one or the other will come first on the classpath. If it's the JVM one, the Scala.js compiler will be confused and produce false artifacts. In your case that translates into the `RPCException`s.

Since your build is non-standard, I am not investigating further why you end up with that dependency. You should be able to do that better than I would.

**Comment by sjrd** [comment] 2018-06-19 12:47
I'm going to close this issue as there does not seem to exist a macro-less reproduction. The issue can be reopened if such a reproduction is found.

**Closed by sjrd** 2018-06-19 12:47 UTC

**Comment by robby-phd** [comment] 2018-06-20 14:13
@sjrd Thanks for investigating the issue and for the explanation.

**Comment by adamw** [comment] 2018-07-24 20:42
I think I'm getting a similar error in sttp, e.g. 
https://travis-ci.org/softwaremill/sttp/jobs/405665845

The error happens "sometimes" which could be explain by the classpath ordering problem. However, I don't see anywhere where the build would pull in a jvm dependency on the js classpath. Is there some way to verify that?

**Comment by sjrd** [comment] 2018-07-24 21:56
> Is there some way to verify that?

    > show theProjectJS/test:fullClasspath

You should only have dependencies with `_sjs0.6` in their names (except scala-library, scalajs-library and scalajs-test-interface).

**Comment by ddworak** [comment] 2018-07-24 22:10
Exactly the same thing happens in one of our internal projects (random `RPCCore$RPCException`s on the same changeset) and we were not able to trace the root cause so far - we definitely do not have `runtime-library-jvm` on the classpath. The common theme seems to be multi-module SBT projects (some of them shared), also the failures seem to concern the shared/cross projects exclusively. I haven't seen this failure in a JS-only project yet.

**Comment by adamw** [comment] 2018-07-25 07:03
@sjrd Here's my output:

```
sbt:circe> show test:fullClasspath
[info] * Attributed(/Users/adamw/projects/sttp/json/circe/.js/target/scala-2.12/test-classes)
[info] * Attributed(/Users/adamw/projects/sttp/json/circe/.js/target/scala-2.12/classes)
[info] * Attributed(/Users/adamw/projects/sttp/core/js/target/scala-2.12/classes)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/machinist_sjs0.6_2.12/0.6.2/machinist_sjs0.6_2.12-0.6.2.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/io/circe/circe-core_sjs0.6_2.12/0.9.3/circe-core_sjs0.6_2.12-0.9.3.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/cats-macros_sjs0.6_2.12/1.0.1/cats-macros_sjs0.6_2.12-1.0.1.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-dom_sjs0.6_2.12/0.9.6/scalajs-dom_sjs0.6_2.12-0.9.6.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/io/circe/circe-scalajs_sjs0.6_2.12/0.9.3/circe-scalajs_sjs0.6_2.12-0.9.3.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/io/circe/circe-parser_sjs0.6_2.12/0.9.3/circe-parser_sjs0.6_2.12-0.9.3.jar)
[info] * Attributed(/Users/adamw/.sbt/boot/scala-2.12.6/lib/scala-reflect.jar)
[info] * Attributed(/Users/adamw/.sbt/boot/scala-2.12.6/lib/scala-library.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-test-interface_2.12/0.6.24/scalajs-test-interface_2.12-0.6.24.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/io/circe/circe-numbers_sjs0.6_2.12/0.9.3/circe-numbers_sjs0.6_2.12-0.9.3.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.12/0.6.24/scalajs-library_2.12-0.6.24.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalatest/scalatest_sjs0.6_2.12/3.0.5/scalatest_sjs0.6_2.12-3.0.5.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/cats-kernel_sjs0.6_2.12/1.0.1/cats-kernel_sjs0.6_2.12-1.0.1.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalactic/scalactic_sjs0.6_2.12/3.0.5/scalactic_sjs0.6_2.12-3.0.5.jar)
[info] * Attributed(/Users/adamw/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/cats-core_sjs0.6_2.12/1.0.1/cats-core_sjs0.6_2.12-1.0.1.jar)
```

Without sjs, there's `scala-reflect.jar` and `scala-library.jar`, as well as `scalajs-test-interface`, but I think that's fine?

**Comment by mdedetrich** [comment] 2019-03-28 15:41
Wanted to state that I ended up having this issue. It turns out that somewhere down the line the amount of memory Scala.js needed to compile increased a lot. For some reason this ends up causing `org.scalajs.testcommon.RPCCore$ClosedException` errors.

Increasing the amount of memory on the machine where I was experiencing the issue (it was a CD machine which is why I couldn't replicate it locally) solved the issue

**Comment by gzm0** [comment] 2019-03-29 06:39
So you are saying this is potentially "just" a reporting problem? So a "out of memory" exception / error somewhere gets swallowed, node crashes, the JVM gives a "useful" `ClosedException`?

**Comment by mdedetrich** [comment] 2019-03-29 10:29
Exactly.

We were having this issue with a project that had a branch which just updated all dependencies in the project. At some point in time this branch just started failing with this error and we had no idea why (considering the exact same branch would work locally). This project is quite massive, it has 15 SBT subprojects around 7 of which are Scala.js projects.

I tried wiping out the CD cache completely (so it was "fresh" install) and that did nothing. Then I just double the memory of the CD and it solved the issue.

I think this is why people experience this problem typically in CD (such as Travis), the instances for these CD platforms often have lower amounts of memory compared to a desktop/laptop.

**Comment by ddworak** [comment] 2019-04-19 17:41
I'm inclined to agree with this explanation. We have observed that using `concurrentRestrictions in Global += Tags.limit(ScalaJSTags.Link, 1)` from 0.6.27 in CI environments reduces the number of these failures.

**Comment by gzm0** [comment] 2019-05-12 15:18
Thank you all for your help and patience on this issue. I have filed #3644 to follow up to improve error reporting. Unfortunately the API in 0.6.x for JSEnv's makes it very difficult for us to fix this, so for now I have scheduled the issue into the 1.0.x branch.

**Comment by gzm0** [comment] 2019-05-12 17:09
Upon better investigation, it seems that simply forwarding the message of the causing exception would be very helpful. I have re-purposed #3644 for that.
