### ISSUE TITLE
Compiler crash with java.lang.IllegalArgumentException when using play-json

### ISSUE THREAD

**Issue by yoo-haemin** [scala-js/scala-js#3144] opened 2017-09-20 08:16 UTC
I'm trying play-json to serialize some simple case classes, but scala-js compiler crashes when I call Json.format on a sealed trait(abstract class). I am creating an issue here and not at play-json because it's a compiler crash.

I first tried on Ubuntu/OpenJDK and then on a Mac Sierra/Oracle JVM and got same results.

Here's the reproduction: https://github.com/yoo-haemin/scalajs-bugreport
sharedJVM/compile works fine, while sharedJS/compile gives a java.lang.IllegalArgumentException.

**Comment by sjrd** [comment] 2017-09-20 08:19
Thanks for the report! I will have a look at it within the next few days.

**Comment by yoo-haemin** [comment] 2017-09-28 07:59
Any updates on this?

**Comment by sjrd** [comment] 2017-09-28 08:19
Sorry. My plans for the past week have been completely overhauled by https://contributors.scala-lang.org/t/alternative-scalajs-scala-native-distribution-mechanisms/1166. This week I am away for a conference, so I don't have time for dev. I will look into this next week.

**Comment by sjrd** [comment] 2017-10-03 11:49
So, it turns out the macro in Play JSON generates a local `val` whose name is `vehicleFormat ` (*note the space at the end*). This is not a valid identifier for a local val, but somehow scalac (JVM) is sloppy and lets it through. The Scala.js back-end, which has more checks for identifiers, detects the issue.

IMO this is a bug in the Play JSON macro, not in Scala.js. I would argue that Scala.js does the right thing by crashing there. Even the error message is appropriate:

    java.lang.IllegalArgumentException: requirement failed: vehicleFormat  is not a valid identifier

(note the double space)

Play JSON most likely generates this name because it copies it from the name of a *field* symbol, which, in scalac, have an extra space for weird internal reasons. But a local val should never a space in its name.

**Comment by sjrd** [comment] 2017-10-03 11:52
The code responsible for this issue is here: https://github.com/playframework/play-json/blob/73c65ebe19964851e41b88d3bb6c0e561fd75fbd/play-json/shared/src/main/scala/play/api/libs/json/JsMacroImpl.scala#L588-L595

**Comment by sjrd** [comment] 2017-10-03 12:00
OK, here's a proof that it is Play JSON's fault. The code generated by the macro does not pass `-Ycheck:refchecks`, even with Scala/JVM:
```
scalajs-bugreport$ sbt
[info] ...
[info] Set current project to scalajs-bugreport (in build file:.../scalajs-bugreport/)
> set scalacOptions in sharedJVM += "-Ycheck:refchecks"
[info] Defining sharedJVM/*:scalacOptions
[info] The new value will be used by sharedJVM/compile:scalacOptions
[info] Reapplying settings...
[info] Set current project to scalajs-bugreport (in build file:.../scalajs-bugreport/)
> sharedJVM/compile
[info] Compiling 1 Scala source to .../scalajs-bugreport/shared/.jvm/target/scala-2.12/classes...
[info] [Now checking: refchecks]
[warn] [check: refchecks] 'value vehicleFormat' has getter but cannot be found. List(value vehicleFormat, value $anonfun, value vehicleFormat, object Serialization, package <empty>, package <root>)
[warn] one warning found
```
So I'll close this issue here as "invalid". You should report the bug to Play JSON.

**Closed by sjrd** 2017-10-03 12:00 UTC
Labels: bug

**Comment by yoo-haemin** [comment] 2017-10-04 12:26
Thanks for the clarification and your time!

**Comment by cchantep** [comment] 2017-10-25 19:19
Hi, I would like to understand why so, the same sources compiled without Scala.JS are working fine : https://github.com/cchantep/scalajs-bugreport/tree/without_scalajs

**Comment by sjrd** [comment] 2017-10-25 21:09
Because scalac/JVM is more "forgiving", and *somehow* the code produced by the macro makes it through the rest of the pipeline of scalac. That can happen because scalac does not always perform expensive comprehensive checks on all trees produced by macros. It is still not valid, as evidenced by the `-Ycheck` failure. It could be that a future version of scalac breaks on the same code without notice, simply because it would rely on more invariants that are supposed to hold for `Tree`s, that the macro violates.

It is the same scenario as if you call a function while not respecting its precondition. It *might* work for your use case by chance, but your code is still wrong. Replacing the function's implementation by another one that relies more on that precondition to be satisfied doesn't make the function wrong. Your code was wrong all along.

Replacing scalac/JVM by scalac+Scala.js is such a replacement of the function's implementation. It turns out that Scala.js relies more on the preconditions that should be satisfied by any `Tree` produced by macros. That doesn't make Scala.js wrong. It is still the macro that is at fault.

**Comment by cchantep** [comment] 2017-10-25 21:54
I don't see. If Scala.js is checking that "the preconditions that should be satisfied by any Tree produced by macros", as the macro impl is `shared` then as far as I understand it would also fails, as the `Tree` is so generated in the same way by the JS macro and the JVM macro.

**Comment by sjrd** [comment] 2017-10-25 22:05
It's not *checking* the preconditions, it's *relying* on them.

Anyway, `shared` is only a source concept. Projects are duplicated for JVM and JS. If the compiler for the JS side complains about something, that doesn't mean the compiler for JVM will complain about the same thing.

**Comment by cchantep** [comment] 2017-10-25 22:18
Still, the `Tree` generated in both JVM and JS impl are the same, and neither the JS nor the JVM macro build is complaining, even with similar cases in unit tests.

**Comment by sjrd** [comment] 2017-10-26 08:35
I'm not following you anymore. You're saying nothing is complaining. So everything is working as expected?

Please be very clear about what experiments you do, what are your expectations, and what are the results.

**Comment by cchantep** [comment] 2017-10-26 09:01
I'm saying that the build of the lib declaring the macro doesn't raise any compilation error or warning, neither for the JS nor the JVM, including not for the unit test (in a separate compilation unit).

I can understand that the ScalaJS compiler doesn't different assumptions, but it seems to me that the difference between those assumption and the "vanilla" compiler will make the compatibility of such macro unpredictable.

**Comment by sjrd** [comment] 2017-10-26 09:13
> I'm saying that the build of the lib declaring the macro doesn't raise any compilation error or warning, neither for the JS nor the JVM, including not for the unit test (in a separate compilation unit).

Building the macro, of course, would not produce any specific error or warning. You need to at least *apply* the macro to see something. The fact that the unit tests don't fail on JS just means that unit tests are not complete enough. In other words, their coverage is not large enough.

> but it seems to me that the difference between those assumption and the "vanilla" compiler will make the compatibility of such macro unpredictable.

If the macro relies on unspecified behavior (violates preconditions), even a future version of the "vanilla" compiler could compromise the compatibility of the macro.

Preconditions exist for a reason. They are a contract. If you (the macro) don't satisfy your part of the contract, then I (the Scala.js compiler) don't have to satisfy mine.

This is exactly the same as in everyday programming with functions: you cannot a function to do its job if you call it with arguments that violate its preconditions.

Contracts exist to ensure portability. It is the macro's responsibility to ensure it complies with the contract in order for it to be portable.

**Comment by cchantep** [comment] 2017-10-26 09:38
> ... even a future version of the "vanilla" compiler could compromise the compatibility of the macro

Of course, but the issue there is that at the current time/for the same Scala versions, the macro doesn't violate the assumptions of the "vanilla" compiler, for none of the Scala version supported from 2.10 to 2.12 (2.13 being tested), but would "silently" (as not indicated during macro build) violates some for the Scala.JS one.

> They are a contract. If you (the macro) don't satisfy your part of the contract, then I (the Scala.js compiler) don't have to satisfy mine.

Once again, I can understand that the "contract" is not the same (even if as previously said if not the same for the same Scala version it impact compability), but I can hardly understand how a macro developer can predict that some error could be raise in very specific case on the caller site (even more as not being responsible/involved as such caller).

> It is the macro's responsibility to ensure it complies with the contract in order for it to be portable.

The compiler compiling the macro is checking, up to some point, that the produced `Tree` is ok. If the compiler raises some error, then the macro can be updated to comply with such enforced contract.

It can be seen as "coverage is not large enough". For me, the issue is that the contract you are speaking of is not enforced on the macro build by the Scala.js compiler, and is not clearly documented ("Can I use macros with Scala.js? What about compiler plugins? Yes, you can. There is nothing specific to Scala.js here.")

**Comment by sjrd** [comment] 2017-10-26 09:44
If you don't pass `-Ycheck`, you don't satisfy the contract. Period. In the above code, the code produced by the macro does not pass `-Ycheck` even on the JVM version. Therefore, it does not comply with the contract.

There is no arguing about this.

**Comment by cchantep** [comment] 2017-10-26 10:29
Considering `-Ycheck:all` (or even only `-Ycheck:typer`) as the "contract", overriding the default compiler one, then even the `library` module of Scala.JS is not satifying it.

"There is no arguing about this" ... fine

**Comment by sjrd** [comment] 2017-10-26 12:04
> then even the library module of Scala.JS is not satifying it.

That's because of https://github.com/scala/bug/issues/10565

**Comment by cchantep** [comment] 2017-10-26 13:09
As for the failure when compiling the macro ...

**Comment by sjrd** [comment] 2017-10-26 13:29
... it does not seem reproducible with vanilla macro-free source code. Therefore, I blame the macro before I blame `-Ycheck`. Plus, in the case of https://github.com/scala/bug/issues/10565, I had [confirmation on Gitter](https://gitter.im/scala/contributors?at=59f05af7d6c36fca31942b26) that `-Ycheck` was faulty.

**Comment by cchantep** [comment] 2017-10-26 13:54
The seen `-Ycheck` failures are not about the macro code or code generated by the macro in tests, so for now that's not related.
