### ISSUE TITLE
ScalaJS 0.6.15 and Scala 2.12 linkage error when using specialized classes

### ISSUE THREAD

**Issue by axel22** [scala-js/scala-js#2899] opened 2017-04-24 07:56 UTC
There is a specialization-related regression on ScalaJS 0.6.15 and Scala 2.12, with respect to Scala 2.11. The underlying reason is most likely that specialization does not generate all the methods in specialized classes any more.

(related to [this bug](https://github.com/scala/bug/issues/10277))

Suppose you have this trait:

```
trait Arrayable[@specialized(Byte, Short, Int, Float, Long, Double) T]
extends Serializable {
  val classTag: ClassTag[T]
  val nil: T
  def newArray(sz: Int): Array[T]
  def newRawArray(sz: Int): Array[T]
  def apply(array: Array[T], idx: Int): T
  def update(array: Array[T], idx: Int, v: T): Unit
  def withNil(n: T) = new Arrayable.WithNil(this, classTag, n)
}

object Arrayable {
  implicit val long: Arrayable[Long] = new Arrayable[Long] {
    val classTag = implicitly[ClassTag[Long]]
    val nil = Long.MinValue
    def newArray(sz: Int) = {
      val a = new Array[Long](sz)
      var i = 0
      while (i < sz) {
        a(i) = nil
        i += 1
      }
      a
    }
    def newRawArray(sz: Int) = new Array[Long](sz)
    def apply(array: Array[Long], idx: Int): Long = array(idx)
    def update(array: Array[Long], idx: Int, v: Long): Unit = array(idx) = v
  }
}
```

The code that gets generated (Scala 2.12.2):

```
public interface io.reactors.Arrayable<T extends java.lang.Object> extends scala.Serializable
...
  public abstract int nil$mcI$sp();
    descriptor: ()I
    flags: ACC_PUBLIC, ACC_ABSTRACT
```

Method `nil$mcI$sp` is not overridden in the following interface:

```
public interface io.reactors.Arrayable$mcJ$sp extends io.reactors.Arrayable<java.lang.Object>
```

It is also not overridden in the following concrete class:

```
public final class io.reactors.Arrayable$$anon$1 implements io.reactors.Arrayable$mcJ$sp
```

This means that there is no implementation of `nil$mcI$sp` at all in a concrete class. When ScalaJS tries to link against this, it breaks:

```
[error] Referring to non-existent method io.reactors.Arrayable$$anon$1.nil$mcI$sp()scala.Int
[error]   called from io.reactors.common.BloomMap$mcI$sp.<init>(io.reactors.Arrayable,io.reactors.Arrayable)
[error]   called from io.reactors.Reactor$MarshalContext.<init>()
[error]   called from io.reactors.Reactor$$anon$1.initialValue()io.reactors.Reactor$MarshalContext
[error]   called from io.reactors.Reactor$$anon$1.initialValue()java.lang.Object
[error]   called from java.lang.ThreadLocal.get()java.lang.Object
[error]   called from io.reactors.Reactor$.currentFrame()io.reactors.concurrent.Frame
[error]   called from io.reactors.Reactor$.currentReactor()io.reactors.Reactor
[error]   called from io.reactors.Reactor$.selfAs()io.reactors.Reactor
[error]   called from io.reactors.Reactor$.self()io.reactors.Reactor
[error]   called from io.reactors.concurrent.Services$.loggingTag()java.lang.String
[error]   called from io.reactors.services.Log.$$anonfun$apply$1(java.lang.Object)scala.Unit
[error]   called from io.reactors.services.Log.<init>(io.reactors.ReactorSystem)
[error]   called from io.reactors.services.Log.<clinit>()
[error]   called from core module analyzer
[error] involving instantiated classes:
[error]   io.reactors.Reactor$$anon$1
[error]   io.reactors.Reactor$$anon$2
[error]   java.lang.ThreadLocal
[error]   io.reactors.Reactor$
[error]   io.reactors.concurrent.Services$
[error]   io.reactors.services.Log
```

**Comment by sjrd** [comment] 2017-04-24 08:17
The snippet above does not appear to be self-contained. There's a call to `new Arrayable.WithNil` which is not defined. Moreover, an entry point (in the form of a `main()` method) would be useful for me to reproduce.

If I comment out `def withNil` and I have a `main()` method that simply makes sure that `Arrayable` is initialized, it is not enough to reproduce the linking error.

Additionally, I'd have to look at the output of `-Xprint:mixin` to be sure, but it seems like this is caused by invalid code produced by scalac to begin with, so I doubt there's anything we can do about it in Scala.js. The bug should be fixed upstream.

**Comment by axel22** [comment] 2017-04-24 11:16
Yes, it's a scalac issue, but I still wanted to give you a heads-up. Will produce a minimal example there.

**Closed** 2017-04-24 11:16 UTC

**Comment by axel22** [comment] 2017-04-24 16:59
@sjrd FYI - the following gist should be self-contained: https://gist.github.com/axel22/d208a0612679a0eee9f9305508bd807e
