### ISSUE TITLE
Performance regression in running tests, v0.6.20

### ISSUE THREAD

**Issue by tindzk** [scala-js/scala-js#3123] opened 2017-09-02 16:08 UTC
Was: **Performance regression in the optimiser**

I noticed that [upgrading Scala.js to v0.6.20](https://github.com/sparsetech/pine/commit/831541e0ff886c604db3b444286c1066ecc39185) increased the time of running our test suite by ~60%.

This regression can be reliably reproduced with the following commands:

```bash
git clone git@github.com:sparsetech/pine.git
cd pine

git checkout 284b857d0d0233966d2793d9c30e07a9434d724d  # Last commit before the upgrade
sbt clean && sbt pineJS/test  # Takes 29s

git checkout 831541e0ff886c604db3b444286c1066ecc39185  # First commit after the upgrade
sbt clean && sbt pineJS/test  # Takes 46s
```

It seems that the optimiser stage takes considerably longer. I opened a [similar issue before](https://github.com/scala-js/scala-js/issues/2943) which may be related.

**Comment by sjrd** [comment] 2017-09-02 21:37
It's not the optimizer; it's the time running the tests themselves. See https://gist.github.com/sjrd/8ca2ee5335bd3143493ef0655fa8fa6b
The time it takes to perform `pineJS/test:compile` and then `pineJS/test:fastOptJS` are both basically equivalent in all three configurations. It's the time taken by `pineJS/test` after having completed `pineJS/test:fastOptJS` that jumps from ~14-18s to 35s on my machine.

@gzm0 I'm afraid this could be caused by the new test adapter :s

**Comment by gzm0** [comment] 2017-09-03 07:23
Yep, indeed this is probably the test adapter. It's not like any other functionality change went into 0.6.20. I'll try this out with the completed adapter and see at how much time we're looking at.

**Comment by gzm0** [comment] 2017-09-03 08:16
I currently get this:

```
// SJS 0.6.19
[info] Run completed in 16 seconds, 108 milliseconds.
[success] Total time: 87 s, completed Sep 3, 2017 9:47:10 AM

// SJS 0.6.20
[info] Run completed in 22 seconds, 96 milliseconds.
[success] Total time: 98 s, completed Sep 3, 2017 9:50:57 AM

// less-jsenv branch
[info] Run completed in 11 seconds, 977 milliseconds.
[success] Total time: 87 s, completed Sep 3, 2017 9:54:34 AM
```

So not really conclusive about anything. I'll proceed with doing more serious benchmarks.

**Comment by gzm0** [comment] 2017-09-03 08:43
Ok, results are not encouraging:

bench.sh
```sh
#! /bin/bash

sbt clean pineJS/test:fastOptJS
for i in $(seq 1 10); do
  /usr/bin/time -f%e --append -o $1 sbt pineJS/test
done
```

```
git checkout 284b857d0d0233966d2793d9c30e07a9434d724d
./bench.sh sjs0.6.19
git checkout 831541e0ff886c604db3b444286c1066ecc39185
./bench.sh sjs0.6.20
# edit project/plugins.sbt 
./bench.sh sjs-w-less-jsenv
```

results
```
sjs0.6.19  sjs0.6.20  less-jsenv
	   	      	  
    18.72      33.81       24.91
    18.59      33.94       24.60
    19.32      33.86       24.45
    18.46      33.57       25.19
    18.60      33.80       26.19
    19.46      34.71       25.85
    19.97      34.19       25.18
    18.85      33.90       25.18
    18.92      33.21       26.06
    18.77      34.17       25.26
```

So the old adapter is still faster than the fully new one. I need to think about this. Not sure how to find out easily, where we take the performance hit.

**Comment by gzm0** [comment] 2017-09-11 12:50
Sharded numbers per methods in the adapter:

```
               v0.6.19     v0.6.20
----------------------------------	       
tasks [ms]         293         230
                   313         257
		   306         260
----------------------------------
done [ms]          181         186
                   180         189
                   180         207
----------------------------------
execute [s]         89         114
                    85         115
		    87         118
----------------------------------
total [s]           18          24
                    19          24
		    18          24
```
Note that `execute` is accumulated over all execute calls (which are executed in parallel).

**Comment by gzm0** [comment] 2017-09-11 13:14
I have also done an experiment on pine where I pass-through strings (rather than UTF8 encoding them):

```
sjs0.6.19  sjs0.6.20  less-jsenv  "fast"-ser  +less-jsenv
	   	      	  			  
    18.72      33.81       24.91       35.22        26.05
    18.59      33.94       24.60       34.84	    25.77
    19.32      33.86       24.45       34.58	    20.80
    18.46      33.57       25.19       33.90	    25.34
    18.60      33.80       26.19       33.61	    24.92
    19.46      34.71       25.85       34.60	    25.61
    19.97      34.19       25.18       33.59	    30.85
    18.85      33.90       25.18       34.20	    25.44
    18.92      33.21       26.06       33.18	    25.47
    18.77      34.17       25.26       33.81	    24.60
```

This seems to actually degrade performance slightly.

**Comment by gzm0** [comment] 2017-09-11 13:30
Two other things I have tried out:

`no-task-opt`: Do not serialize task defs inside tasks specially.
`no-log`: Reduce log (remove JUnit flags in our build).

```
               0.6.19     0.6.20   no-task-opt   no-log
-------------------------------------------------------
tasks [ms]        293        230           259      236
                  313        257           251      249
		  306        260           266      227
-------------------------------------------------------
done [ms]         181        186           205      206
                  180        189           201      207
                  180        207           198      195
-------------------------------------------------------
execute [s]        89        114           114      114
                   85        115           115      113
		   87        118           116      115
-------------------------------------------------------
total [s]          18         24            24       23
                   19         24            24       23
		   18         24            24       23
```

`no-task-opt`: Tries to see how much performance improvement the shortcutting gives us. It gives some improvement in `tasks` which is expected.
`no-log`: Tests the hypothesis that the execution time is essentially logging throughput bound. This does not verify.

**Comment by gzm0** [comment] 2017-09-13 13:29
Just as an update, I'm currently looking for a hypothesis to test on this one. The only things I can think of:

- We dispatch more often via an execution context now (in `RPCCore`).
- There is a thread more per JS VM reading messages (in `ComJSEnvRPC`).

Both of them seem kind of unlikely to be the cause.

**Comment by sjrd** [comment] 2017-09-13 13:42
Are we sure there is no thread that waits, idly, for instructions?

**Comment by gzm0** [comment] 2017-09-13 14:51
You mean a worker thread? It's not like we control them... So yes, the JVM threads block in the invocation of `execute` until the test on the JS side ends, but that was always the case. The only difference there is that the logging now happens on the message dispatcher thread for the JS VM and not on the sbt thread.

That being said, I haven't looked at a threaddump (then yet again, even if it were different, I wouldn't know what to do about it).

**Comment by gzm0** [comment] 2017-09-13 14:58
Ah, that might very well be. But the way we dispatch JVM threads on JS VMs has [not changed between v0.6.19 and v0.6.20][1].

[1]: https://github.com/scala-js/scala-js/compare/v0.6.19...v0.6.20#diff-f557773a2c06b1e58262122c70335af6

**Comment by tindzk** [comment] 2017-09-14 17:53
Thanks for the extensive analysis so far! Did you notice the same issue also with other code bases? If there is anything I can do to help narrow down the cause in Pine, please let me know. By the way, JVisualVM is capable of [showing](https://www.nuxeo.com/assets/wordpress/dev/images/6a010536291c30970b01538f8c6493970b-pi.png) the wait and sleep times of threads.

Out of curiosity, what does the `less-jsenv` branch exactly refer to?

**Comment by gzm0** [comment] 2017-09-14 19:57
> Did you notice the same issue also with other code bases? 

Yes. This also happens on the Scala.js test suite itself. So there is nothing specific to Pine here at all. Our implementation just got slower.

> Out of curiosity, what does the `less-jsenv` branch exactly refer to?

To #3122: It's purpose is to spawn less JSEnvs for test runs and hence hopefully improve performance (see #2645). The initial numbers show that it **does** improve performance, but we introduce a regression somewhere else (the changes already introduced were just to ease the implementation of #3122).

By now, I'm pretty confident that it's not due to JVM threads sleeping (in fact, they sleep even when tests are executed, since they just wait on the JS side to be done). The reason is that we actually **do** spend more time in `execute`. If threads were asleep, the `execute` times would be similar, but the overall time would be higher.

I'm afraid that this might be an asynchronous scheduling issue: Besides from the serialization (which seems to be more or less on par), we also introduced more asynchronicity. I'm concerned that both sbt and the default execution context both allocate a threadpool and that the repeated blocking (sbt expects the methods it calls to be blocking) causes a context-switch explosion between the two threadpools. As in: TP1 generates work for TP2 which unblocks TP1 which generates work for TP2, etc.

I neither have an idea right now how to test this hypothesis or how to fix this if it verifies (without changing the interface to sbt).

**Comment by gzm0** [comment] 2017-09-18 19:32
I measured cumulative execution time of the test tasks on the JS side:

```
                     0.6.19    0.6.20
execute()  JS [s]:       30        31
execute() JVM [s]:       90       115
```

This includes attaching and detaching the task (but not serialization). The results are not super astonishing and essentially just confirm that logging/event propagation is not slower in the new system.

**Comment by gzm0** [comment] 2017-09-24 12:49
I have found the culprit: It's the receiver threads as I feared. If I replace calls to `Await.result` with a specially forged `callSync` method (on `ComJSEnvRPC`) that uses the thread for the receive loop, we're back in previous ballpark performance.

Implementation is here: https://github.com/gzm0/scala-js/tree/less-threads

The implementation needs some brushing up, but has two fundamental problems:
- It claims to support arbitrary callbacks to a JVM endpoint, but it doesn't (only works when another call is pending).
- If we make the `JSEnv` interface async (#3033), the implementation won't work (trivially) anymore.

From here, we have a couple of options:

1. Do not care. Take the performance hit.
2. Brush-up the `less-threads` branch, merge it, worry about async later.
3. Try to create an `IOThreadPool` abstraction or something we can pass to `JSEnv`s for thread reuse.
4. Investigate a single receiver thread that "selects".

I'll start investigating option 3 (and maybe 4). Expected difficulties:

- Might be hard without `java.nio`.
- We wanted to make `JSEnv` compile for JS. This might be a step backwards for this.

**Comment by gzm0** [comment] 2017-10-07 13:42
Quick update: I have come up with a solution that uses a [ScheduledThreadPoolExecutor][1] to share the thread pool of the execution context to perform input I/O if necessary (with a fixed interval with cancellation if an sbt thread becomes available).

The results show that it is *not the number of threads* that causes the performance regression, but the *context switching*. In fact: If I set the I/O tick interval to 1s, on the platform I test, I get the slow numbers again. If set the I/O tick interval to 10s, I get the fast numbers on `execute` but we take a > 10s penalty when shutting down (because we actually block).

From this I must conclude that the only option how we will get comparable performance back is by "lying": that is to claim that the RPC interface is fully duplex while it is actually not. Since we probably will not need this capability, I'll start thinking whether there is a cleaner abstraction that let's us do that.

[1]: https://docs.oracle.com/javase/6/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html

**Comment by gzm0** [comment] 2017-10-08 07:57
I have gone with lying and not abstracting over it (but just documenting it). Performance is back up:

```
               0.6.19     0.6.20   no-task-opt   no-log  less-ctx-switch
------------------------------------------------------------------------
tasks [ms]        293        230           259      236              233
                  313        257           251      249              247
		  306        260           266      227              215
------------------------------------------------------------------------
done [ms]         181        186           205      206              173
                  180        189           201      207              144
                  180        207           198      195              146
------------------------------------------------------------------------
execute [s]        89        114           114      114               84
                   85        115           115      113               84
		   87        118           116      115               86
------------------------------------------------------------------------
total [s]          18         24            24       23               18
                   19         24            24       23               18
		   18         24            24       23               17
```

**Comment by sjrd** [comment] 2017-10-08 08:57
Nice! :+1:

**Comment by gzm0** [comment] 2018-03-30 18:54
Just an update on this issue: I have not found a better way how to deal with this than to make a joinable thread pool that the sbt worker threads can join and leave on the fly. This thread pool would further have to deal with mixed cases of I/O and selecting. I'm unsure whether it is feasible to pull this off at all, but I will try in the 1.0.x/master branch where the simplified `JSEnv` interface might allow for that.

Unfortunately this means that we'll have to live with the performance penalty in the 0.6.x branch :-/

**Comment by gzm0** [comment] 2018-10-09 19:19
It seems like we can live with this in v1.0.0 and we can fix this in a binary compatible manner. @sjrd unless you have any objections, I'll move this post-v1.

**Comment by gzm0** [comment] 2018-10-09 19:19
(or anybody else has objections in fact)

**Comment by gzm0** [comment] 2019-05-25 08:15
Unassigning as I'm not actively working on this.

**Comment by sjrd** [comment] 2019-09-04 06:05
@tindzk Is this still an issue?

I tested the latest `master` of the above repo with old versions of Scala.js, and I observed a significant improvement when going from 0.6.22 to 0.6.23. It might have been caused by https://github.com/scala-js/scala-js/commit/5c3e516f64fc5379b36957972eea8e6d7113062a.

**Comment by tindzk** [comment] 2019-09-05 06:39
The original issue is resolved. Compilation time in 0.6.28 is shorter than it was in 0.6.19. However, taking 0.6.[23..27] as a baseline, there does seem to be a minor regression in 0.6.28. On average, the compilation time is ~2s longer.

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `rm -rf */target && ./set-sjs-version.sh 19 && sbt pineJS/test` | 92.982 ± 1.638 | 89.774 | 94.965 | 1.1 |
| `rm -rf */target && ./set-sjs-version.sh 20 && sbt pineJS/test` | 111.453 ± 2.509 | 108.988 | 117.264 | 1.3 |
| `rm -rf */target && ./set-sjs-version.sh 21 && sbt pineJS/test` | 113.454 ± 2.681 | 109.962 | 117.347 | 1.4 |
| `rm -rf */target && ./set-sjs-version.sh 22 && sbt pineJS/test` | 93.973 ± 2.011 | 91.049 | 98.337 | 1.1 |
| `rm -rf */target && ./set-sjs-version-23.sh 23 && sbt pineJS/test` | 83.858 ± 1.702 | 81.183 | 86.690 | 1.0 |
| `rm -rf */target && ./set-sjs-version-23.sh 24 && sbt pineJS/test` | 83.898 ± 1.519 | 81.309 | 85.858 | 1.0 |
| `rm -rf */target && ./set-sjs-version-23.sh 25 && sbt pineJS/test` | 83.377 ± 1.079 | 82.139 | 85.549 | 1.0 |
| `rm -rf */target && ./set-sjs-version-23.sh 26 && sbt pineJS/test` | 83.609 ± 1.221 | 81.742 | 85.471 | 1.0 |
| `rm -rf */target && ./set-sjs-version-23.sh 27 && sbt pineJS/test` | 83.211 ± 1.282 | 81.704 | 85.380 | 1.0 |
| `rm -rf */target && ./set-sjs-version-23.sh 28 && sbt pineJS/test` | 85.388 ± 1.909 | 82.771 | 89.418 | 1.0 |

The results can be reproduced as follows:

```shell
$ docker run -it tindzk/seed:0.1.5 /bin/sh
apk add git yarn bash curl
git clone --branch scala-js-regr-test-sbt https://github.com/sparsetech/pine.git
cd pine
yarn add jsdom@11
curl -L -o hyperfine-v1.7.0-x86_64-unknown-linux-musl.tar.gz https://github.com/sharkdp/hyperfine/releases/download/v1.7.0/hyperfine-v1.7.0-x86_64-unknown-linux-musl.tar.gz
tar xvf hyperfine-v1.7.0-x86_64-unknown-linux-musl.tar.gz
curl -L -o sbt.zip https://piccolo.link/sbt-1.2.8.zip
unzip sbt.zip
export PATH=$(pwd)/hyperfine-v1.7.0-x86_64-unknown-linux-musl:$(pwd)/sbt/bin:$PATH
for v in 19 20 21 22; do rm -rf */target && ./set-sjs-version.sh $v && sbt pineJS/compile; done
for v in 23 24 25 26 27 28; do rm -rf */target && ./set-sjs-version-23.sh $v && sbt pineJS/compile; done
hyperfine -i --show-output --export-markdown comparison.md \
	'rm -rf */target && ./set-sjs-version.sh 19 && sbt pineJS/test' \
	'rm -rf */target && ./set-sjs-version.sh 20 && sbt pineJS/test' \
	'rm -rf */target && ./set-sjs-version.sh 21 && sbt pineJS/test' \
	'rm -rf */target && ./set-sjs-version.sh 22 && sbt pineJS/test' \
	'rm -rf */target && ./set-sjs-version-23.sh 23 && sbt pineJS/test' \
	'rm -rf */target && ./set-sjs-version-23.sh 24 && sbt pineJS/test' \
	'rm -rf */target && ./set-sjs-version-23.sh 25 && sbt pineJS/test' \
	'rm -rf */target && ./set-sjs-version-23.sh 26 && sbt pineJS/test' \
	'rm -rf */target && ./set-sjs-version-23.sh 27 && sbt pineJS/test' \
	'rm -rf */target && ./set-sjs-version-23.sh 28 && sbt pineJS/test'
cat markdown.md
```

**Comment by sjrd** [comment] 2019-09-06 13:06
Thanks for the measurements! Looking at these results, I think we can close this issue.

**Closed by sjrd** 2019-09-06 13:06 UTC
Labels: bug

**Comment by gzm0** [comment] 2019-09-06 14:58
Hum, do we understand what happens between 21 -> 22 and 22 -> 23?

**Comment by sjrd** [comment] 2019-09-06 15:09
22 -> 23 is probably 5c3e516f64fc5379b36957972eea8e6d7113062a, as I mentioned above. It's the only thing that touches relevant areas.

And 21 -> 22 is probably https://github.com/scala-js/scala-js/pull/3122.

**Comment by gzm0** [comment] 2022-05-22 18:04
FWIW, I have attempted to re-gain some of the speed we suspected to have lost to context switching by implementing an `ExecutionContext` using threads awaiting a future to execute tasks.

With the following naive, locking implementation, I could not see any speed improvements (even potential slowdown ~10%).

```scala
package org.scalajs.testing.adapter

import java.util.concurrent.locks.ReentrantLock

import java.util.ArrayDeque
import scala.util.control.NonFatal
import scala.annotation.tailrec
import scala.concurrent.{Future, ExecutionContext}

private abstract class Pool extends ExecutionContext {
  private[this] val tasks = new ArrayDeque[Runnable]

  final def awaitAndHelp[T](future: Future[T]): T = {
    val syncFuture = future.map(identity)(this)

    @tailrec
    def getWork(): Option[Runnable] = synchronized {
      if (syncFuture.isCompleted) {
        None
      } else if (!tasks.isEmpty()) {
        Some(tasks.remove())
      } else {
        wait()
        getWork()
      }
    }

    @tailrec
    def loop(): T = {
      getWork() match {
        case Some(work) =>
          doWork(work)
          loop()

        case None =>
          syncFuture.value.get.get
      }
    }

    loop()
  }

  private def doWork(work: Runnable): Unit = {
    try {
      work.run()
      synchronized { notifyAll() }
    } catch {
      case NonFatal(t) => reportFailure(t)
    }
  }

  final def execute(runnable: Runnable): Unit = synchronized {
    tasks.add(runnable)
    notifyAll()
  }
}
```
