### ISSUE TITLE
compiler crash in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [scala-js/scala-js#3381] opened 2018-06-16 17:50 UTC
at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3012/consoleFull we see:

```
[scala-js] [error]   bad constant pool tag 20 at byte 107
[scala-js] [error]      while compiling: /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.12/project-builds/scala-js-357d2083bf5722f9310fe505be075626829ad56d/library/src/main/scala/scala/scalajs/reflect/annotation/EnableReflectiveInstantiation.scala
```

the problem isn't reproducible outside dbuild with `++2.12.7-bin-5622f5d` followed by `library/compile`, so I don't have a guess what might be causing this, any ideas...?

**Comment by sjrd** [comment] 2018-06-16 17:59
Er ... I'm totally clueless, unless you upgraded the JDK from 8 to 9 on the community build?

According to Google, the only `bad constant pool tag 20` in the world is our own https://github.com/scala-js/scala-js/issues/3152

**Comment by sjrd** [comment] 2018-06-16 18:03
Hint: the constant pool tag 20 means "package" and [was introduced in JVM 9](https://docs.oracle.com/javase/specs/jvms/se9/html/jvms-4.html#jvms-4.4). It is not present [in JVM 8](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4).

**Comment by sjrd** [comment] 2018-06-16 18:06
Yup, the dbuild log says that task that failed is `library/compile:doc`. Definitely a duplicate of #3152.

**Closed by sjrd** 2018-06-16 18:06 UTC

**Comment by SethTisue** [comment] 2018-06-16 18:21
huh, the JDK 9 job is supposed to be separate, this one is supposed to be on Java 8. I'll look into it

**Comment by SethTisue** [comment] 2018-06-16 20:08
haha duh, it's this, in the community build config:

```
      // on Java 9, the Scala.js build expects this property to be set
      "-Dscala.ext.dirs="${ORIGINAL_HOME}"/.sbt/0.13/java9-rt-ext-oracle_corporation_9_0_4"
```

I'll fix.
