### ISSUE TITLE
java.lang.Integer.parseUnsignedInt is missing, java.lang.Long.parseLong misbehaves

### ISSUE THREAD

**Issue by lihaoyi** [scala-js/scala-js#1645] opened 2015-05-07 15:07 UTC
JVM:

```scala
scala> java.lang.Integer.parseUnsignedInt("ffffffff", 16)
res7: Int = -1

scala> java.lang.Long.parseLong("ffffffff", 16)
res8: Long = 4294967295
```

JS:

```scala
scala> java.lang.Integer.parseUnsignedInt("ffffffff", 16)
res7: Int = -1
Main.scala:11: error: value parseUnsignedInt is not a member of object Integer
    println(java.lang.Integer.parseUnsignedInt("ffffffff", 16))
                              ^

scala> java.lang.Long.parseLong("ffffffff", 16)
java.lang.NumberFormatException: For input string: "ffffffff"
```

http://www.scala-js-fiddle.com/gist/0e23afde84cd9d697c93?

(for some reason the fullOpt error is different from the fastOpt error, not sure why)

**Comment by lihaoyi** [comment] 2015-05-07 15:11
Looks like `Long.valueOf` misbehaves identically

JVM
```scala
scala> java.lang.Long.valueOf("ffffffff", 16)
res9: Long = 4294967295
```

JS
```scala
scala> java.lang.Long.valueOf("ffffffff", 16)
java.lang.NumberFormatException: For input string: "ffffffff"
```

**Comment by sjrd** [comment] 2015-05-07 15:11
Duplicate of #1583

**Comment by lihaoyi** [comment] 2015-05-07 15:12
Ah I didn't see that, thanks @sjrd

**Closed by sjrd** 2015-05-07 15:11 UTC
