### ISSUE TITLE
 Referring to non-existent class error when instantiating inner trait.

### ISSUE THREAD

**Issue by mikla** [scala-js/scala-js#4168] opened 2020-08-27 20:28 UTC
This valid Scala code fails on `fastOptJS` stage. This is quite similar to `simulacrum` type classes encodings.

Fails with following Scala.js versions: `1.0.1`, `1.1.0`, `1.1.1`

However, works on `1.0.0`

`sbt.version = 1.3.13` 

```scala

trait Named[A] {
  def name(a: A): String
}

object Named {

  trait Ops[A] {
    def typeClassInstance: Named[A]
    def self: A
    def name: String = typeClassInstance.name(self)
  }

  object ops {
    implicit def toNamedOps[A](target: A)(implicit tc: Named[A]): Ops[A] = new Ops[A] {
      val self = target
      val typeClassInstance = tc
    }
  }

}

object MainApp {

  case class Employee(id: UUID, name: String)
  object Employee {
    implicit val named: Named[Employee] = _.name
  }

  def name[E: Named](e: E): String = e.name

  def main(args: Array[String]): Unit = {
    println(name(Employee(UUID.randomUUID(), "name")))
  }

}
```

I'm getting this error:

```bash

sbt:scalajs-simulacrum> fastOptJS
[info] Compiling 1 Scala source to scalajs-simulacrum/target/scala-2.13/classes ...
[warn] 1 feature warning; re-run with -feature for details
[warn] one warning found
[info] Fast optimizing /scalajs-simulacrum/target/scala-2.13/scalajs-simulacrum-fastopt.js
[error] Referring to non-existent class io.github.mikla.Named$Ops
[error]   called from io.github.mikla.MainApp$.name(java.lang.Object,io.github.mikla.Named)java.lang.String
[error]   called from io.github.mikla.MainApp$.main([java.lang.String)void
[error]   called from static io.github.mikla.MainApp.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   io.github.mikla.MainApp$
[error] Referring to non-existent method io.github.mikla.Named$Ops.name()java.lang.String
[error]   called from io.github.mikla.MainApp$.name(java.lang.Object,io.github.mikla.Named)java.lang.String
[error]   called from io.github.mikla.MainApp$.main([java.lang.String)void
[error]   called from static io.github.mikla.MainApp.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   io.github.mikla.MainApp$
[error] Referring to non-existent class io.github.mikla.Named$Ops
[error]   called from io.github.mikla.MainApp$.name(java.lang.Object,io.github.mikla.Named)java.lang.String
[error]   called from io.github.mikla.MainApp$.main([java.lang.String)void
[error]   called from static io.github.mikla.MainApp.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   io.github.mikla.MainApp$
[error] Referring to non-existent class io.github.mikla.Named$Ops
[error]   called from io.github.mikla.Named$ops$.toNamedOps(java.lang.Object,io.github.mikla.Named)io.github.mikla.Named$Ops
[error]   called from io.github.mikla.MainApp$.name(java.lang.Object,io.github.mikla.Named)java.lang.String
[error]   called from io.github.mikla.MainApp$.main([java.lang.String)void
[error]   called from static io.github.mikla.MainApp.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   io.github.mikla.Named$ops$
[error]   io.github.mikla.MainApp$
[error] Referring to non-existent class io.github.mikla.Named$Ops
[error]   called from io.github.mikla.Named$ops$$anon$1
[error]   called from io.github.mikla.Named$ops$.toNamedOps(java.lang.Object,io.github.mikla.Named)io.github.mikla.Named$Ops
[error]   called from io.github.mikla.MainApp$.name(java.lang.Object,io.github.mikla.Named)java.lang.String
[error]   called from io.github.mikla.MainApp$.main([java.lang.String)void
[error]   called from static io.github.mikla.MainApp.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   io.github.mikla.Named$ops$
[error]   io.github.mikla.MainApp$
[error] Referring to non-existent class io.github.mikla.Named$Ops
[error]   called from constructor io.github.mikla.Named$ops$$anon$1.<init>(java.lang.Object,io.github.mikla.Named)void
[error]   called from io.github.mikla.Named$ops$.toNamedOps(java.lang.Object,io.github.mikla.Named)io.github.mikla.Named$Ops
[error]   called from io.github.mikla.MainApp$.name(java.lang.Object,io.github.mikla.Named)java.lang.String
[error]   called from io.github.mikla.MainApp$.main([java.lang.String)void
[error]   called from static io.github.mikla.MainApp.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   io.github.mikla.Named$ops$
[error]   io.github.mikla.MainApp$
[error] Referring to non-existent method io.github.mikla.Named$Ops.$init$()void
[error]   called from constructor io.github.mikla.Named$ops$$anon$1.<init>(java.lang.Object,io.github.mikla.Named)void
[error]   called from io.github.mikla.Named$ops$.toNamedOps(java.lang.Object,io.github.mikla.Named)io.github.mikla.Named$Ops
[error]   called from io.github.mikla.MainApp$.name(java.lang.Object,io.github.mikla.Named)java.lang.String
[error]   called from io.github.mikla.MainApp$.main([java.lang.String)void
[error]   called from static io.github.mikla.MainApp.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   io.github.mikla.Named$ops$
[error]   io.github.mikla.MainApp$
[error] There were linking errors
[error] (Compile / fastOptJS) There were linking errors
[error] Total time: 4 s, completed Aug 27, 2020 11:15:31 PM

```

Few notes:

- if I rename `trait Ops` to `trait NamedOps` for example - everything is fine.
- if I rename `trait Ops` to `trait NamedOps` and `object ops` to `object namedops` - getting the same error.

Reproduction case repo: https://github.com/mikla/scalajs-simulacrum-bug

Interesting that this code works in `scastie` https://scastie.scala-lang.org/3XPYbw91TmWOGb7BTos4iQ

**Comment by sjrd** [comment] 2020-08-27 22:18
This is a duplicate of #4148. It is already fixed on master.

**Closed by sjrd** 2020-08-27 22:18 UTC
