### ISSUE TITLE
JVM style module initialization under semantic flag

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1490] opened 2015-02-14 06:14 UTC
Given this minimised ADT:
```scala
sealed trait A
object A {
  private def blankSym = ""

  sealed abstract class B extends A
  case object X extends B

  sealed abstract class C(symbol: String) extends A
  case object Y extends C(blankSym)

  val cs = Vector[C](Y)
}
```

At runtime, both `A.cs.head == A.Y` and `A.cs.head eq A.Y` will fail.

Guess how to make it work? Change
```scala
case object Y extends C(blankSym)
```
to
```scala
case object Y extends C("")
```

**Comment by japgolly** [comment] 2015-02-14 06:19
Btw, workaround is to make `val cs` lazy.

**Comment by sjrd** [comment] 2015-02-14 16:38
Intriguing. I'll look into it tomorrow evening or on Monday.

**Comment by sjrd** [comment] 2015-02-15 14:44
Does it even work on the JVM?

**Comment by sjrd** [comment] 2015-02-15 20:18
I cannot reproduce. The following program prints `true` with Scala 2.11.5 and Scala.js 0.6.0, under all optimization stages:
```scala
sealed trait A
object A {
  private def blankSym = ""

  sealed abstract class B extends A
  case object X extends B

  sealed abstract class C(symbol: String) extends A
  case object Y extends C(blankSym)

  val cs = Vector[C](Y)
}

object Test extends scala.scalajs.js.JSApp {
  def main(): Unit = {
    println(A.cs.head eq A.Y)
  }
}
```

**Comment by japgolly** [comment] 2015-02-16 13:28
This is going to be a pain to reproduce. If the above code works ok outside of my codebase, it might be an initialisation order thing. There might be another `object` somewhere that creates a `val` that indirectly references `A.{B,C,X,Y}`. Tomorrow I'll might do a manual binary search turning `val`s into `def`s and see if anything has an effect...

**Comment by japgolly** [comment] 2015-02-17 01:01
I tried turning making `val`s everywhere lazy, except for `val cs = Vector[C](Y)` and the problem persists. It doesn't seem to be val initialisation order thing.

An idea is maybe we could craft a custom build of Scala.JS that spits out debug info when it creates an instance of `A.Y`, then I could send you that info?

**Comment by japgolly** [comment] 2015-02-17 02:24
I just remembered that we're generating JS here. I can look at the output!

First, I changed `A.Y` to
```scala
case object Y extends C(blankSym) {
    try {sys.error("Initialising")} catch {case e: Throwable =>
      e.printStackTrace()
      println()
    }
}
```

And sure enough it yields:
```
java.lang.RuntimeException: Initialising
  at scala.scalajs.runtime.StackTrace$.createException(http://localhost:8080/assets/dev/webapp-client-fastopt.js:40474:25)
  at java.lang.Throwable.fillInStackTrace(http://localhost:8080/assets/dev/webapp-client-fastopt.js:53554:56)
  at java.lang.Throwable.<init>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:53577:8)
  at java.lang.RuntimeException.<init>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:69275:66)
  at scala.sys.package$.error(http://localhost:8080/assets/dev/webapp-client-fastopt.js:35620:114)
  at japgolly.A$Y$.<init>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:129679:32)
  at japgolly.A$Y$$.<clinit>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:129742:163)
  at japgolly.A$.<init>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:28377:28)
  at japgolly.A$$.<clinit>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:28481:135)
  at japgolly.A$Y$.<init>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:129676:123)

java.lang.RuntimeException: Initialising
  at scala.scalajs.runtime.StackTrace$.createException(http://localhost:8080/assets/dev/webapp-client-fastopt.js:40474:25)
  at java.lang.Throwable.fillInStackTrace(http://localhost:8080/assets/dev/webapp-client-fastopt.js:53554:56)
  at java.lang.Throwable.<init>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:53577:8)
  at java.lang.RuntimeException.<init>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:69275:66)
  at scala.sys.package$.error(http://localhost:8080/assets/dev/webapp-client-fastopt.js:35620:114)
  at japgolly.A$Y$.<init>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:129679:32)
  at japgolly.A$Y$$.<clinit>(http://localhost:8080/assets/dev/webapp-client-fastopt.js:129742:163)
  at japgolly.F$.$default(http://localhost:8080/assets/dev/webapp-client-fastopt.js:61961:294)
  at japgolly.G$.$default(http://localhost:8080/assets/dev/webapp-client-fastopt.js:62053:331)
  at {anonymous}()(http://localhost:8080/assets/dev/webapp-client-fastopt.js:27635:77)
```

Something missing from the minimised example is something along the lines of this:
```
object F {
   val default = A.Y
}
object G {
   val default = F.default
}
```

Again, changing those `val`s to `def`s doesn't help.

**Comment by japgolly** [comment] 2015-02-17 02:36
I found the object initialisation JS and hacked it:
```js
ScalaJS.m.Ljapgolly_A$Y$ = (function() {
console.log("ACCESS", ScalaJS.n.Ljapgolly_A$Y$)
  if ((!ScalaJS.n.Ljapgolly_A$Y$)) {
    console.log("INIT START")
        ScalaJS.n.Ljapgolly_A$Y$ = new ScalaJS.c.Ljapgolly_A$Y$().init___()
    console.log("INIT END")
  };  
  return ScalaJS.n.Ljapgolly_A$Y$
});
```

to see:
```
ACCESS undefined
INIT START
ACCESS undefined
INIT START
INIT END
INIT END
```

which doesn't make much sense to me. `A.Y` has an empty body and the only thing it references is a method in `A` itself.

**Comment by japgolly** [comment] 2015-02-17 02:47
Changing
```scala
  case object Y extends C(blankSym)
  val cs = Vector[C](Y)
```
to
```scala
  case object Y extends C(blankSym) { console.log("INIT OBJ") }
  val cs = {
    console.log("INIT VAL - START")
    val x = Vector[C](Y)
    console.log("INIT VAL - END")
    x
  }
```
yields
```
INIT VAL - START
INIT OBJ
INIT VAL - END
INIT OBJ
```

Replacing `Y extends C(blankSym)` to `Y extends C("")` yields
```
INIT OBJ
INIT VAL - START
INIT VAL - END
```

**Comment by sjrd** [comment] 2015-02-25 05:26
@japgolly Did you manage to come up with a reproduction outside of your project? 
Or can you post the full definition of the culprit objects as well their translation to js?

**Comment by japgolly** [comment] 2015-02-25 05:38
@sjrd Heya. No, I was unable to reproduce it outside of my project. :(

Is the above information enough though? From what I've posted above we can deduce the following:

1. As `A.Y` is initialised, `A` is initialised also.
2. If `A.Y`'s initialisation needs to access `A.blankSym`, then `A` is _reinitialised_ before `A.Y` completes.
3. The reinitialisation of `A` triggers another creation of `A.Y` however this time, its access of `A.blankSym` does *not* reinitialise `A`. (Else it would loop forever and blow stack.)

Thus I would guess: there must be a variable (α) that describes the availability of `A.blankSym`, which when-or-before being set, sets another variable (β) describing that `A` has begun initialisation (due step 3). It seems to me that variable β isn't being set before `A.Y` inits (step 1) which is causing this reentrancy issue.

I assumed (and hoped) that would be enough info fix the issue. Can it be?

**Comment by sjrd** [comment] 2015-02-25 07:11
I'll try, but without a repro I can hardly tell whether I actually fixed the bug. Worse, I can't whether it even works on the JVM. I don't want to fight for a bug that's originally in scalac or a fundamental limitation of objects in Scala.

**Comment by japgolly** [comment] 2015-02-25 10:39
Ah, I understand your situation more now. I really don't know why this is so hard to reproduce - it's consistent within my large app. I guess I'll try again at some point.

**Comment by sjrd** [comment] 2015-02-25 12:30
Ah, I managed to reproduce the issue simply by inverting the two sides of the comparison, which means that `A.Y` is evaluated before `A`:
```scala
sealed trait A

object A {
  private def blankSym = ""

  sealed abstract class B extends A
  case object X extends B

  sealed abstract class C(symbol: String) extends A
  case object Y extends C(blankSym) {
    new Exception("boo").printStackTrace()
  }

  val cs = Vector[C](Y)
}

object Test extends scala.scalajs.js.JSApp {
  def main(): Unit = {
    //println(A.cs.head eq A.Y)
    println(A.Y eq A.cs.head)
  }
}
```
But then, this code also prints false on the JVM, as I expected.

So I'm afraid this is a fundamental limitation of objects. There's nothing I can do about it. There's probably nothing scalac can do about it either. Your code just falls out of the (undocumented) legal cases of circular references in the constructors of objects.

What happens is this. First, objects in objects are fundamentally equivalent to top-level objects. So we can rewrite the program as follows and still observe the exact same behavior (both the good and bad ones):
```scala
sealed trait A

object A {
  def blankSym = ""

  val cs = Vector[C](Y)
}

sealed abstract class B extends A
case object X extends B

sealed abstract class C(symbol: String) extends A
case object Y extends C(A.blankSym) {
  new Exception("boo").printStackTrace()
}

object Test extends scala.scalajs.js.JSApp {
  def main(): Unit = {
    //println(A.cs.head eq Y)
    println(Y eq A.cs.head)
  }
}
```

Now what happens is:

1. `Y` is accessed first, as the first operand of `eq`.
2. Since `Y` has not been created yet, its constructor is invoked. On the JVM this is done in the static initializer of the `Y$` class. On JS this is done by the `Scala.m.Y$` function.
3. Before calling its super constructor, the constructor of `Y` accesses `A` to get `A.blankSym`.
4. Since `A` has not been created yet, its constructor is invoked.
5. `A` calls its super constructor, which is `Object`, which does nothing.
6. Right after the call to super, the global variable holding the instance of `A` (`ScalaJS.n.A$` on JS, `MODULE$` on the JVM) is initialized with `this` from the constructor of `A`
7. The rest of the constructor of `A` accesses `Y` to fill in its vector.
8. Since `Y` has not been initialized yet (we haven't yet got passed the call to the super constructor of `Y` at this point), we have a problem. At this point the behaviors differ on the two platforms. On the JVM, the static initializer is *not* run a second time. Instead, it's just ignored and `Y` returns `null`. On JS, a new instance of `Y` gets created. Anyway, we're in trouble and bad things start to happen, on both platforms.
9. On JS, the constructor of this second `Y` accesses `A.blankSym`.
10. Now, `A` is initialized already (although it has not finished executing its constructor). So all good here.
11. So we can call `blankSym`, and receive an empty string.
12. The constructor of the second `Y` can continue. It calls its super constructor, initializes its global variable, and returns.
13. The constructor of `A` receives the second instance of `Y` and puts it in the vector. On the JVM, it receives `null` and puts it in the vector.
14. The constructor of `A` terminates, and returns.
15. The constructor of the first `Y` receives `A`, calls `blankSym`, and receives the empty string.
16. It continues, then reinitializes the global variable to this (first) instance of `Y`. On the JVM, it initializes it for the first time.
17. We return to the main program, receiving the first instance of `Y`.
18. The main program now accesses `A.cs.head`, in which was stored the *second* instance of `Y` on JS, or `null` on the JVM.
19. In both cases, the two sides do not `eq`.

**Comment by japgolly** [comment] 2015-02-25 12:46
Argh!! Hours of effort and the whole time I just had to swap the oprands around ergh

Well done and thank you.

What's really annoying about this is that when it happens, it's quite subtle to track down. It really seems like something `-Xcheckinit` should be catching but it misses it on both JVM (now that I can reproduce) and JS. This really should be fixed; I'll submit an issue for scalac. Any chance of just a warning being printed out from ScalaJS when this occurs?

**Comment by sjrd** [comment] 2015-02-25 12:50
Producing warnings would mean adding code to every module accessor, which means bigger .js + slower accesses of the modules. So no, I don't think I would that.

**Comment by sjrd** [comment] 2015-02-25 12:52
Btw, `-Xcheckinit` doesn't catch it because that's not what it checks. It checks that `val`s are not accessed before they are initialized. Not that top-level objects are not reaccessed a second time before they could at least complete the call to their super constructor.

**Comment by japgolly** [comment] 2015-02-25 12:58
Yep, I understand that's what Xcheckinit does currently, but I don't think
it's exclusive by intention. I'd argue that the flag exists to check
everything initialises in a working order. Val access order is part of
that, I think this is another case that should fall under the same umbrella.

Also would you be opposed to adding a warning if it were only enabled when
-Xcheckinit or some other option was specified? When one turns on
Xcheckinit flag, one expects a perf degradation anyway, and most people
don't specify the flag so they'd be unaffected (and I have it off for prod
builds).
​

**Comment by sjrd** [comment] 2015-02-25 13:04
> Also would you be opposed to adding a warning if it were only enabled when -Xcheckinit or some other option was specified?

I'm not opposed in theory. But in practice I just can't implement it that way because there's no place in the IR to put that code. Module accessors don't have code in the IR, they are synthesizes entirely at the time we emit the final JS. On the other hand, we could have a linker option for that. It would sort of fit in the Undefined Behaviors system (except it would be Unchecked by default, instead of Fatal by default; and Compliant would mean returning `null` like on the JVM).

**Comment by japgolly** [comment] 2015-02-25 13:11
That would be helpful. Careful people like me could add that to their non-prod settings and switch it off for prod.

Also I've raised it on the scalac side: https://issues.scala-lang.org/browse/SI-9184

I'm aware that you're time isn't infinite nor free; maybe if they patch scalac then you'll just absorb it when upgrading scalac versions (if it works that way) without much direct change to ScalaJS.

**Comment by japgolly** [comment] 2015-02-25 13:19
I just realised something. This felt important to me because most of my app worked without any warning., which made this tedious to trackdown. If it were initialised to `null` like the JVM, it would've been easy to track down: an NPE would both fail immediately and basically scream compiler issue. That makes a warning much less important. :)

**Comment by sjrd** [comment] 2015-02-25 13:44
Even initializing it with `null` means more code. Potentially worse, it adds a third type to the lifetime of this variable (besides `undefined` and its final result), which can confuse the JIT.

**Comment by gzm0** [comment] 2015-02-25 18:40
I think it makes sense to say that objects are initialized to null by (undocumented) scala specification and we add a compliance flag for that.

**Comment by sjrd** [comment] 2015-02-25 21:11
Yes, that's what I had in mind.

**Comment by gzm0** [comment] 2015-03-07 06:53
@sjrd does this still have to be labeled wontfix? IIUC we said we are going to add a semantics for that, right?

**Comment by sjrd** [comment] 2015-03-07 07:55
Yes we'll add semantics. I guess wontfix is not applicable.

**Closed** 2015-03-24 06:53 UTC
Labels: enhancement

**Comment by japgolly** [comment] 2015-03-24 09:54
:+1: :)
