### ISSUE TITLE
Pattern matcher groupCount throws

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1727] opened 2015-06-16 01:55 UTC
The following snippet behaves very differently in Scala.JS vs JVM.

```scala
"(a)(b)cd".r.pattern.matcher("").groupCount
```

In JVM, it prints 2. In JS it throws `java.lang.IllegalStateException: No match available`.

**Comment by sjrd** [comment] 2015-06-16 09:13
Unfortunately, this is virtually not fixable. With a JS regexp, there is no way to get the group count without having a *successful* match. So either we parse the regexp on an ad hoc basis to get that count (hard), or we derive automatically a matching string from the regexp to match against it (which requires to parse the regex in the first place).

Unless someone else has an idea...

**Comment by gzm0** [comment] 2015-06-16 18:22
Yet another issue that would be solved by our own regex parser as [proposed in #1201](https://github.com/scala-js/scala-js/issues/1201#issuecomment-104710898)

**Comment by japgolly** [comment] 2015-06-17 08:15
I played around with JS RegExps and read some ref doc - definitely doesn't seem possible.

Regex continues to be the largest source of incompatible Scala/Scala.JS behaviour. It's a significant problem because you only hit the errors at runtime - compilation & linking passes silently. The only way to catch incompatibilities like this one, unsupported regex like `(?<!x)`, etc is probably going to along the lines of a custom regex lib like @gzm0 suggested. I don't know what else can be done. It might not be pleasant but it is better than a partially-discovered mountain of runtime-only errors, which is what we have today.

**Comment by sjrd** [comment] 2015-06-19 11:11
I'll close this as Won't Fix. If it must be fixed, it will go into the larger scheme of things of fixing #1201 anyway.

**Closed by sjrd** 2015-06-19 11:11 UTC
Labels: bug

**Comment by MikaelMayer** [comment] 2017-08-29 16:37
For people having a problem with `groupCount`, my fix is the following:

    def countGroups(m: Regex.Match): Int = {
       try {m.groupCount} catch { case e: Throwable =>
         Stream.from(0).takeWhile(i => try { val x = m.group(i); x != null } catch { case e: Throwable => false} ).length - 1
       }
     }

If the call to groupCount fails, it tries to enumerate the groups and return the inferred count. It saved my tool (scalajs 0.6.19)

**Comment by easel** [comment] 2018-03-12 03:33
Thanks @MikaelMayer for the fix it works for me too.

@sjrd is this something we could fold into the stldlib `.groupCount`?

**Comment by sjrd** [comment] 2018-03-12 16:07
I don't think so, because the workaround builds on top of Scala's `Regex.Match`, not on top of Java's `regex.Matcher`.

**Comment by sjrd** [comment] 2021-03-29 08:43
This was in fact fixed in https://github.com/scala-js/scala-js/commit/e5d3d6b495d9aaf4e2b3aadbe24598071317242c as part of fixing #3280, which should have been marked as a duplicate of this one, but we did not notice.
