### ISSUE TITLE
Shapeless IR error in scala 2.11 and 2.12 with Scala.js 1.0.0

### ISSUE THREAD

**Issue by cquiroz** [scala-js/scala-js#3955] opened 2020-02-10 13:10 UTC
As reported in gitter, attempts to build shapless with scala.js 1.0.0-RC2 and 1.0.0-RC fail on scala 2.11 and 2.12 with this error during fastOpt

```
[error] https://raw.githubusercontent.com/milessabin/shapeless/31165f293cfce35525b8293b66afd0ba7868c4ac/core/src/test/scala/shapeless/hlist.scala(3165:48:VarDef): Duplicate local variable name x$1566.

[error] https://raw.githubusercontent.com/milessabin/shapeless/31165f293cfce35525b8293b66afd0ba7868c4ac/core/src/test/scala/shapeless/hlist.scala(3165:53:VarDef): Duplicate local variable name x$1565.

[error] There were 2 IR checking errors.

[error] (coreJS / Test / fastOptJS) There were 2 IR checking errors.
```

This is triggered by the following test:
```scala
  @Test
  def testFromProductArgs: Unit = {
    val p = "foo" :: 1 :: 3 :: HNil

    val v1 = Bar.sumLabelProduct(p)
    typed[(String, Int)](v1)
    assertEquals(("foo", 4), v1)

    val p2 = "bar" :: 1 :: 2 :: HNil
    val v2 = Bar.sumMultipleParamListLabelProduct(p2)
    typed[(String, Int)](v2)
    assertEquals(("bar", 3), v2)

    illTyped("""
      Bar.sumImplicitLabelProduct("foo" :: 1 :: 3 :: HNil)
    """)

    implicit val i2 = 7
    val v3 = Bar.sumImplicitLabelProduct("foo" :: 1 :: HNil)
    typed[(String, Int)](v3)
    assertEquals(("foo", 8), v3)

    illTyped("""
      Bar.sumLabelProduct("foo" :: "bar" :: 1 :: 2 :: HNil)
    """)

    illTyped("""
      Bar.sumMultipleParamListLabelProduct("foo" :: "1" :: 2 :: 3 :: HNil)
    """)
  }
```

**Comment by julienrf** [comment] 2020-02-11 14:51
Hey @cquiroz thanks for your investigation!

We added a line in the [compiler](https://github.com/scala-js/scala-js/blob/v1.0.0/compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala#L2177) to print symbols of val definitions:

~~~ scala
println(s"${sym.name}  (${sym.id})")
~~~

When doing so and compiling the test case, we observe that a same symbol is reused at several places:

~~~
x1  (22016)
[info] Compiling 1 Scala source to /home/julien/workspace/dev/shapeless/core/js/target/scala-2.12/test-classes ...
p  (25747)
x$3  (25753)
x$2  (25754)
x$1  (25755)
v1  (25748)
p2  (25749)
x$6  (40236)
x$5  (40237)
x$4  (40238)
v2  (25750)
i2  (25751)
v3  (25752)
x$8  (41850)
x$7  (41851)
x$8  (41850)
x$7  (41851)
~~~

(See the last four lines)

As far as I understand, this means that the tree that is passed to the Scala.js compiler is illegal in the first place. The origin of the problem could be in the way the macro is implemented in shapeless or the way the Scala 2.12 compiler expands macros.

**Comment by sjrd** [comment] 2020-02-11 14:54
Thanks for the investigation, @julienrf.

Yes, in that case I'll close this issue here as "separate repo", since the correct fix should happen in the Shapeless macro that generates this code.

Note that the issue is not specific to Scala.js. The investigation shows that the code is invalid before the Scala.js compiler gets its hands on it. So the same problem exists on the JVM. It's just that the JVM back-end is more forgiving, and apparently it works "by chance".

**Comment by cquiroz** [comment] 2020-02-11 14:54
Thanks, that is very helpful

**Closed by sjrd** 2020-02-11 14:54 UTC
