### ISSUE TITLE
Packaging dependencies

### ISSUE THREAD

**Issue by DellCliff** [scala-js/scala-js#2290] opened 2016-03-13 14:25 UTC
If the <project_name>-jsdeps.min.js exists, fastOptJS does not generate a <project_name>-jsdeps.js file.
If the <project_name>-jsdeps.js exists, fullOptJS does not generate a <project_name>-jsdeps.min.js file.

**Comment by sjrd** [comment] 2016-03-13 15:32
Duplicate of #2243

**Closed by sjrd** 2016-03-13 15:32 UTC
