### ISSUE TITLE
"Bad interaction" with scoverage

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#3803] opened 2019-10-05 01:54 UTC
# Reproducible step
```
git clone https://github.com/exoego/scalajs-scoverage-issue
cd scalajs-scoverage-issue
sbt coverage test
```

* Scala 2.12.10 (2.13.1 does not work with sbt-coverage https://github.com/scoverage/sbt-scoverage/issues/295)
* Scala.js 0.6.29
* sbt-scoverage 1.6.0

# Actual result

Then error message is shown like

```
$> sbt coverage test                                                                                                                                           [info] Loading settings for project scalajs-scoverage-issue-build from plugins.sbt ...
[info] Loading project definition from /home/vagrant/IdeaProjects/scalajs-scoverage-issue/project
[info] Loading settings for project scalajs-scoverage-issue from build.sbt ...
[info] Set current project to scalajs-scoverage-issue (in build file:/home/vagrant/IdeaProjects/scalajs-scoverage-issue/)
[info] Defining ThisBuild / coverageEnabled
[info] The new value will be used by Compile / compile / scalacOptions, libraryDependencies
[info] Reapplying settings...
[info] Set current project to scalajs-scoverage-issue (in build file:/home/vagrant/IdeaProjects/scalajs-scoverage-issue/)
[info] Compiling 1 Scala source to /home/vagrant/IdeaProjects/scalajs-scoverage-issue/target/scala-2.12/classes ...
[info] Cleaning datadir [/home/vagrant/IdeaProjects/scalajs-scoverage-issue/target/scala-2.12/scoverage-data]
[info] Beginning coverage instrumentation
[info] Instrumentation completed [4 statements]
[info] Wrote instrumentation file [/home/vagrant/IdeaProjects/scalajs-scoverage-issue/target/scala-2.12/scoverage-data/scoverage.coverage]
[info] Will write measurement data to [/home/vagrant/IdeaProjects/scalajs-scoverage-issue/target/scala-2.12/scoverage-data]
[error] /home/vagrant/IdeaProjects/scalajs-scoverage-issue/src/main/scala/net/example/JSONHelper.scala:6:24: Found a dangling UndefinedParam at Position(file:/home/vagrant/IdeaProjects/scalajs-scoverage-issue/src/main/scala/net/example/JSONHelper.scala,7,33). This is likely due to a bad interaction between a macro or a compiler plugin and the Scala.js compiler plugin. If you hit this, please let us know.
[error]   implicit final class JSONConversionsToJson(val value: js.Any) extends AnyVal {
[error]                        ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed 2019/10/05 10:46:26
```

# Expected

Scala.js should work with scoverage, and scoverage generate a report successfully as same as for JVM.

# Note

* The issue occurs regardless of test code. So I omitted the test code in https://github.com/exoego/scalajs-scoverage-issue.
* Opened this since " If you hit this, please let us know." message shown by Scala.js, though I am not sure which Scala.js or scoverage (or both) is suspicious.

**Comment by sjrd** [comment] 2019-10-05 03:52
Duplicate of https://github.com/scoverage/scalac-scoverage-plugin/issues/196. This should be fixed on scoverage's side.

One of the two plugins will have to know about the other one; there's no way to generalize a fix in one of the two that is completely agnostic of the other one.

So why should it be scoverage? There are two reasons:

* Intrinsic reason: If the fix were in Scala.js, it would have to *undo* work done by scoverage, based on the shapes of trees it produces, which is very brittle. On scoverage's side, the fix would avoid doing the work in the first place, based on semantics information, which is robust.
* Ecosystem reason: scoverage can and does depend on Scala.js for its runtime part, therefore it can actually *test* the fix in its CI. Scala.js cannot afford to depend on *anything*, because the ecosystem requires that Scala.js publishes for new versions of Scala before any other project in the entire ecosystem can do so. So a fix in Scala.js could not be tested.

Other relevant previous discussion: https://github.com/scala-js/scala-js/issues/2631

**Closed by sjrd** 2019-10-05 03:52 UTC

**Comment by exoego** [comment] 2019-10-06 10:49
Could you give what codes Scala.js expect from other compiler plugin (scoverage for this case) ?

I looked into scoverage and attempted to fixed this issue.
From some experiments, my understanding is that scoverage rewrite Scala code something like below:

```scala
// original
def toJson(value: String): String = {
    scala.scalajs.js.JSON.stringify(
        js.this.Any.fromString(value),
        scala.scalajs.js.JSON.stringify$default$2(),
        scala.scalajs.js.JSON.stringify$default$3()
    )
}

// instrumented
def toJson(value: String): String = {
    scoverage.Invoker.invoked(4, "/tmp");
    scala.scalajs.js.JSON.stringify({
        scoverage.Invoker.invoked(1, "/tmp");
        js.this.Any.fromString(value)
    }, {
        scoverage.Invoker.invoked(2, "/tmp");
        scala.scalajs.js.JSON.stringify$default$2(),
    }, {
        scoverage.Invoker.invoked(3, "/tmp");
        scala.scalajs.js.JSON.stringify$default$3(),
    })
}
```

I assumed Scala.js complained about default parameter, so modified scoverage a bit to produce code something like below: 

```scala
def toJson(value: String): String = {
    scoverage.Invoker.invoked(2, "/tmp");
    scala.scalajs.js.JSON.stringify({
        scoverage.Invoker.invoked(1, "/tmp");
        js.this.Any.fromString(value)
    },
    scala.scalajs.js.JSON.stringify$default$2(), // not instrumented if default value
    scala.scalajs.js.JSON.stringify$default$3() // same as above
    )
}
```

But Scala.js still complains about `UndefinedParam`.

**Comment by sjrd** [comment] 2019-10-06 12:32
> I assumed Scala.js complained about default parameter, so modified scoverage a bit to produce code something like below:

You assumed well and the modified code looks like what I would expect. It seems to me that it should work this way. Maybe something else got in the way? If you have a reproduction I can look at it next week. (This week I am at Scala Sphere.)

**Comment by exoego** [comment] 2019-10-08 01:34
You may try [my branch of scalac-scoverage-plugin](https://github.com/exoego/scalac-scoverage-plugin/tree/fix-196) used in https://github.com/scoverage/scalac-scoverage-plugin/pull/281

**Comment by exoego** [comment] 2019-11-02 12:52
Could you look https://github.com/scoverage/scalac-scoverage-plugin/pull/281 ?

**Comment by exoego** [comment] 2020-01-31 12:24
@sjrd
Just a kind reminder
