### ISSUE TITLE
Unused shared file causes `bad option: -P:scalajs:mapSourceURI`

### ISSUE THREAD

**Issue by jurisk** [scala-js/scala-js#2424] opened 2016-05-30 19:12 UTC
Scenario:

1. Check out revision:
https://github.com/jurisk/scala-js-photoplaces/commit/d0b330fbfcf8c4dfe38a470a120af2b2cfbbc257

2. Launch app using "sbt run"

3. Go to localhost:9000, observe error:

```
[info] Compiling 1 Scala source to /Users/juris/projects/scala-js-photoplaces/shared/.js/target/scala-2.11/classes...
[error] bad option: -P:scalajs:mapSourceURI:file:/Users/juris/projects/scala-js-photoplaces/shared/src/main/scala/->c6350df76c64249fcf86/
[error] one error found
[error] (sharedJS/compile:compileIncremental) Compilation failed
[error] application - 

! @7095db601 - Internal server error, for (GET) [/] ->
 
play.sbt.PlayExceptions$CompilationException: Compilation error[bad option: -> P:scalajs:mapSourceURI:file:/Users/juris/projects/scala-js-photoplaces/shared/src/main/scala/->c6350df76c64249fcf86/]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$2$$anonfun$apply$3.apply(PlayReload.scala:20)
	at play.sbt.run.PlayReload$$anonfun$compile$2$$anonfun$apply$3.apply(PlayReload.scala:20)
```
4. Remove file "SharedMessages.scala" (https://github.com/jurisk/scala-js-photoplaces/commit/9179ac08d755514439ba3840e096dd366d0fb6b3)

5. Refresh localhost:9090, observe that no such error appears.

**Comment by sjrd** [comment] 2016-05-30 20:12
Is this reproducible without sbt-play-scalajs nor Play at all? Only with a vanilla Scala.js `crossProject`?

**Comment by jurisk** [comment] 2016-06-02 09:16
Unlikely, because the flag comes from sbt-play-scalajs:

https://github.com/vmunier/sbt-play-scalajs/blob/master/src/main/scala/playscalajs/ScalaJSPlay.scala#L28

**Comment by gzm0** [comment] 2016-06-02 10:56
Yes, I think this is a `sbt-play-scalajs` issue. The bad option error usually comes if a `-P:scalajs:` option is passed to a compiler that does not have the Scala.js plugin loaded.

So from a bird eye's view, this seems more like `sbt-play-scalajs` not setting the flags right all the time.

**Comment by gzm0** [comment] 2016-06-12 21:32
@jurisk could you open this as an issue on sbt-play-scalajs and could they confirm it? If yes, could you link to the issue and close this one?

Thanks!

**Comment by gzm0** [comment] 2016-07-13 07:18
Closing, because there was no follow-up.

**Closed by gzm0** 2016-07-13 07:18 UTC
Labels: invalid

**Comment by tflucke** [comment] 2022-02-28 05:39
Since this is the only thing that comes up when you google `bad option: -P:scalajs:mapSourceURI`, I thought I'd add a solution here.

The problem is that [sbt-web-scalajs](https://github.com/vmunier/sbt-web-scalajs) versions earlier than 1.2.0 use `-P:scalajs:mapSourceURI`, but scala3 requires `-scalajs-mapSourceURI`.  The solution is to update sbt-web-scalajs to 1.2.0 or later, or to downgrade to scala2.
