### ISSUE TITLE
The varargs optimization does not work with multiple parameter lists

### ISSUE THREAD

**Issue by chandu0101** [scala-js/scala-js#2741] opened 2017-01-17 23:34 UTC
### Multi ParamList

```scala
@inline
def View(props:js.Object)(children:ReactNode*):ReactElement = React.createElement("View",props,children :_*)

val v = View(js.Dynamic.literal(x= 10))("hello","hello1")
```

***fastOptJS***

```scala
  var props = {
    "x": 10
  };
  var children = $m_s_Predef$().wrapRefArray__AO__scm_WrappedArray($makeNativeArrayWrapper($d_sjs_js_$bar.getArrayOf(), ["hello", "hello1"]));
  var jsx$1 = $i_react;
  var jsx$4 = jsx$1.createElement;
  if ($is_sjs_js_ArrayOps(children)) {
    var x2 = $as_sjs_js_ArrayOps(children);
    var jsx$3 = x2.scala$scalajs$js$ArrayOps$$array$f
  } else if ($is_sjs_js_WrappedArray(children)) {
    var x3 = $as_sjs_js_WrappedArray(children);
    var jsx$3 = x3.array$6
  } else {
    var result = [];
    var i = 0;
    var len = children.length__I();
    while ((i < len)) {
      var arg1 = children.apply__I__O(i);
      $uI(result.push(arg1));
      i = ((1 + i) | 0)
    };
    var jsx$3 = result
  };
  var jsx$2 = ["View", props].concat(jsx$3);
  var v = jsx$4.apply(jsx$1, jsx$2);
```
***fullOptJS***  

```scala
var a;cd||(cd=(new dd).a());var b=new (Fa(Wa).ra)(["hello","hello1"]);
null===b?b=null:0===b.R.length?(Nc||(Nc=(new Mc).a()),b=Nc.Ha):(a=new H,a.T=b,b=a);a=b;b=Oa.createElement;
if(a&&a.b&&a.b.j.ee)a=a.Nd;else if(a&&a.b&&a.b.j.ge)a=a.T;
else{for(var c=[],e=0,l=a.ja();e<l;){var k=a.S(e);c.push(k)|0;e=1+e|0}a=c}
a=["View",{x:10}].concat(a);b=b.apply(Oa,a);
```

### Single Param List 

```scala
@inline
def View(props:js.Object,children:ReactNode*):ReactElement = React.createElement("View",props,children :_*)
val v = View(js.Dynamic.literal(x= 10),"hello","hello1")
```

***fastOptJS*** : 

```scala
 var props = {
    "x": 10
  };
  var array = ["hello", "hello1"];
  var jsx$1 = $i_react;
  var v = jsx$1.createElement.apply(jsx$1, ["View", props].concat(array));
```

***fullOptJS***

```scala
var a=ua.createElement.apply(ua,["View",{x:10}].concat(["hello","hello1"]))
```

### Direct JS Function Call 

```scala
    React.createElement("View",js.Dynamic.literal(x= 10),"hello","hello1")
```

***fastOptJS***

```scala
$i_react.createElement("View", {
    "x": 10
  }, "hello", "hello1")
```

***fullOptJS***

```scala
sa.createElement("View",{x:10},"hello","hello1")
```

### Summary : 

1) Clearly multi param list method generating a lot of code and it will add up execution times!
2) Single param list method output is close to direct js call invocation, but its using `.apply`  which is less efficient than direct call! 

.call vs .apply on My machine : 

<img width="1002" alt="screen shot 2017-01-18 at 4 59 36 am" src="https://cloud.githubusercontent.com/assets/2179670/22044521/2e699928-dd3b-11e6-8a54-25f8d79f7198.png">

Ref: https://jsperf.com/call-apply-segu

**Comment by sjrd** [comment] 2017-01-18 00:42
I suspect this has the same root cause as #2265.

As for using `call`, or even better, just method call syntax, it's harder. We would need to teach the optimizer to keep track of the contents of (non-mutated) JavaScript arrays.

**Comment by chandu0101** [comment] 2017-01-18 01:34
>As for using call, or even better, just method call syntax, it's harder. We would need to teach the optimizer to keep track of the contents of (non-mutated) JavaScript arrays.

cool ok, for performance critical parts user can use direct `React.creatElement..` .

**Comment by chandu0101** [comment] 2017-01-21 09:55
@sjrd 
out of curiosity is it possible to get this in 0.6.15 ? my entire library depend on this feature :(,  or any work arounds for this ? 

```scala
def View(props:js.Object)(children:ReactNode*) = anotherMethod(props,children.toJSArray) // i want direct array[] to be passed without intermediate wrapped array steps.  
def anotherMethod(props:js.Object,children:js.Array[ReactNode]) = .. 
```

**Comment by sjrd** [comment] 2017-01-21 10:15
I don't know. For 0.6.15 we focus on missing language features before moving to 1.0.0. Bugs are also prioritized, as usual. That doesn't leave much time to work on optimizations in this release.

You could work around it with a macro. By identifying the wrapped array conductor and replacing it by a `new js.WrappedArray(js.Array(arg1, ..., argN))`.

Or you could investigate the compiler limitation. It should be related to `genActualArgs` in `GenJSCode.scala`.

**Comment by sjrd** [comment] 2017-01-21 12:56
Well, I found it in a couple minutes of actually looking. Fix pending in PR #2745. This fix gets rid of the `WrappedArray`s. It does not eliminate the `concat` in your specific case, though.

**Comment by chandu0101** [comment] 2017-01-21 15:11
> It does not eliminate the concat in your specific case, though.

thats not a problem for my production logic atm :)

**Comment by sjrd** [comment] 2017-01-22 14:23
@chandu0101 Here is a branch where the optimizer is smart enough to transform `.apply()` calls with `concat` into direct method calls: https://github.com/scala-js/scala-js/compare/master...sjrd:virtualize-jsarrayconstr
It needs tests to make sure I didn't break anything, but if you want you can play with it. Note that this branch is not based on PR #2745, so it won't handle multi-parameter-list methods unless you locally merge both branches together.

**Comment by chandu0101** [comment] 2017-01-23 00:09
@sjrd 

```scala
@inline
def View1(props:js.Object)(children:ReactNode*):ReactElement = React.createElement("View",props,children :_*)

val v1 = View1(js.Dynamic.literal(x= 10))("hellv1","hellovv12")

```

***fullOptJS*** : 

### Case1 : 

```scala
Q.createElement("View",{x:10},"hellv1","hellovv12");
```

now its directly making function call :o 👍 👏 

### Case2 : 

```scala
  def inlineElement(props:js.Object,children:js.Array[ReactNode]) = React.createElement("View",props,children :_*)

    @inline
    def View(props:js.Object)(children:ReactNode*):ReactElement = inlineElement(props,children.toJSArray)

   val v = View(js.Dynamic.literal(x= 10))("hello","hello2")
```

***fullOptJS***: 

```scala
 a=Q.createElement.apply(Q,["View",{x:10}].concat(["hello","hello2"]));
```

now we have direct array no wrapped ... 👍  , but do you think we can optimize further here ?

**Comment by sjrd** [comment] 2017-01-23 09:42
Add `@inline` to `def inlineElements` and you'll get what you want.

**Comment by chandu0101** [comment] 2017-01-23 10:49
>Add @inline to def inlineElements and you'll get what you want.

sorry for not being clear , my inlineElement method will look like 

```scala
   
    def inlineElement(props:UniversalProps,children:js.Array[ReactNode]) = {

      if(props.ref.isDefined) React.createElement("View",props,children :_*)
      else {
        props.asInstanceOf[js.Dynamic].updateDynamic("children")(children)
        js.Dynamic.literal(tag = "View",props = props).asInstanceOf[ReactElement]
      }
    }

```

anyway we rarely go that `ref` block (1 in 100) ;)

**Comment by sjrd** [comment] 2017-01-23 12:22
That can only be optimized if the condition of the if can be constant-folded to `true` by the optimizer. Otherwise the `children` array escapes on the heap (and then to a JS library), so anything could happen to it. Elements could change values, the size could change, etc. Which disables the optimization of expanding the array.

The fullOptJS you were showing is because *Closure* manages to constant-fold `props.ref !== void 0`, because Closure does some analysis of JS objects. Scala.js does not analyze JS objects, though, so it cannot do that. But at the same time Closure cannot optimize the `.apply` and `.concat`, so you're back to square one.

This could change if you used a condition that Scala.js understands.

You can also side-step the original issue (the potential escape of the original array) by making a *copy* of the array in the slow path:
```scala
props.asInstanceOf[js.Dynamic].updateDynamic("children")(js.Array(children: _*))
```
which, by the way, I would write as:
```scala
props.asInstanceOf[js.Dynamic].children = js.Array(children: _*)
```
Now the original array `children` does not escape, even in the else branch. That means that Scala.js can still optimize it away in the if branch, and create a brand new array in the else branch.

Self-contained reproducible example:
```scala
object HelloWorld extends js.JSApp {
  def main() {
    val v = view("hello", 5, 6, 7)
    println(v)
  }

  @inline
  def view(props: String, children: Int*) =
    inlineElement(props, children.toJSArray)

  @inline
  def inlineElement(props: String, children: js.Array[Int]) = {
    if (props.length < 10) {
      React.createElement("View", props, children: _*)
    } else {
      props.asInstanceOf[js.Dynamic].children = js.Array(children: _*)
      js.Dynamic.literal(tag = "View", props = props)
    }
  }
}

@ScalaJSDefined
object React extends js.Object {
  def createElement(name: String, props: String, children: Int*): Int =
    props.length + children.sum
}
```
fastOptJS result:
```js
  if (($uI("hello".length) < 10)) {
    var v = $uI($m_Lhelloworld_React$().createElement("View", "hello", 5, 6, 7))
  } else {
    "hello".children = [5, 6, 7];
    var v = {
      "tag": "View",
      "props": "hello"
    }
  };
  var this$24 = $m_s_Console$();
  var this$25 = $as_Ljava_io_PrintStream(this$24.outVar$2.v$1);
  this$25.java$lang$JSConsoleBasedPrintStream$$printString__T__V((v + "\n"))
```
and Closure will be able to give the final blow:
```js
L.prototype.main=function(){
  pb||(pb=new (qb()));
  var a=pb.createElement("View","hello",5,6,7)|0;
  nb(ob().u.q,a+"\n")
};
```

**Comment by sjrd** [comment] 2017-01-23 12:40
Fixed by #2745.

**Closed by sjrd** 2017-01-23 12:40 UTC
Labels: optimization

**Comment by chandu0101** [comment] 2017-02-02 04:30
@sjrd can you please merge this one also  https://github.com/sjrd/scala-js/tree/virtualize-jsarrayconstr to master ? , i want to depend on master in my app!

**Comment by sjrd** [comment] 2017-02-02 06:58
I'll do it when I have time. I'm currently on vacation.

The master branch is not something we support. We recommend to use released versions.

**Comment by chandu0101** [comment] 2017-02-02 07:33
cool ok  :)

**Comment by chandu0101** [comment] 2017-02-08 08:22
@sjrd 

 I have a method defined like this 

```scala
 type ReactNode = String | ReactElement | Int 

@ScalaJSDefined
trait Item extends js.Object {
  var _id: js.UndefOr[String] = js.undefined
  var name: String
  var category: String
  var price: Double
  var quantity: Double
  var updated: String
}

@inline
def View(style = js.Any)(children: ReactNode*) = inlineElement(ViewClass,props,children.toJSArray)

@inline
def Text(style = js.Any)(children: ReactNode*) = inlineElement(TextClass,props,children.toJSArray) 

@inline
def Text(children: ReactNode*) = inlineElement(TextClass,props,children.toJSArray)
```

### case 1 :  

```scala
   View(style = globalStyles.listCellRow)(
      View(style = globalStyles.vegetableInfo)(
        Text(style = globalStyles.boldText)(rowData.name),
        Text("oktest")
      ),
      Text(style = globalStyles.boldText)("dude")
    )
```

***fastOptJS*** 

```scala
    var jsx$1 = $m_sc_Seq$();
  var a$5 = $as_T(rowData.name);
  var x$19 = $as_sc_Seq(jsx$1.apply__sc_Seq__sc_GenTraversable(new $c_sjs_js_WrappedArray().init___sjs_js_Array([a$5])));
  var fresh$macro$16 = {};
  fresh$macro$16.style = a$4;
  var elem$1$1 = null;
  elem$1$1 = fresh$macro$16;
  var ctor$1 = $i_react$002dnative.Text;
  var props$1 = elem$1$1;
  var this$50 = $m_sjsr_package$();
  if ($is_sjs_js_ArrayOps(x$19)) {
    var x2 = $as_sjs_js_ArrayOps(x$19);
    var children = x2.scala$scalajs$js$ArrayOps$$array$f
  } else if ($is_sjs_js_WrappedArray(x$19)) {
    var x3 = $as_sjs_js_WrappedArray(x$19);
    var children = x3.array$6
  } else {
    var result = [];
    x$19.foreach__F1__V(new $c_sjsr_AnonFunction1().init___sjs_js_Function1((function($this$1, result$1) {
      return (function(x$2$1) {
        return $uI(result$1.push(x$2$1))
      })
    })(this$50, result)));
    var children = result
  };
  var jsx$2 = $i_react;
  var a$6 = jsx$2.createElement.apply(jsx$2, [ctor$1, props$1].concat(children));
  var x$31 = $i_react$002dnative.Text;
  var x$32 = {};
  var a$7 = $i_react.createElement(x$31, x$32, "oktest");
  var fresh$macro$1$1 = {};
  fresh$macro$1$1.style = a$3;
  var elem$1$2 = null;
  elem$1$2 = fresh$macro$1$1;
  var ctor$2 = $i_react$002dnative.View;
  var props$2 = elem$1$2;
  var a$8 = $i_react.createElement(ctor$2, props$2, a$6, a$7);
  var a$9 = $m_Lmanagramam_components_styles_package$().globalStyles$1.boldText;
  var fresh$macro$16$1 = {};
  fresh$macro$16$1.style = a$9;
  var elem$1$3 = null;
  elem$1$3 = fresh$macro$16$1;
  var ctor$3 = $i_react$002dnative.Text;
  var props$3 = elem$1$3;
  var a$10 = $i_react.createElement(ctor$3, props$3, "dude", "dude2");
```
for text element with style  ` Text(style = globalStyles.boldText)(rowData.name)` its missing optimization ? :s  if i pass extra children to that node `Text(style = globalStyles.boldText)(rowData.name,"dude")` then its directly inlining array!  it looks like its failing when we pass only one var arg :s

**Comment by chandu0101** [comment] 2017-02-08 13:23
**update :** 

wow just wow  , in my method i have first param as ` @exclude extraProps: OptionalParam[TextProps] = OptDefault,`  i just moved this param  position down and viola , everything is as expected :s
