### ISSUE TITLE
Fixed point loop exceeded the maximum number of iterations error after upgrading to 0.6.11 from 0.6.10

### ISSUE THREAD

**Issue by ngbinh** [scala-js/scala-js#2549] opened 2016-07-31 05:44 UTC
Looks like I hit this https://github.com/johan/closure-compiler/blob/master/src/com/google/javascript/jscomp/PhaseOptimizer.java#L50

`fastOptJs` works normally though.

``` scala
02:05:47.856 [info 02:05:47:AM] Full optimizing target/build/main/web/js/stargazerjs.min.js
02:19:50.690 [info 02:19:50:AM] Closure: 0 error(s), 0 warning(s)
02:19:59.496 [error 02:19:59:AM] trace: throwable: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
02:19:59.496 Please report this problem.
02:19:59.496 
02:19:59.496 Fixed point loop exceeded the maximum number of iterations.
02:19:59.498 java.lang.RuntimeException: INTERNAL COMPILER ERROR.
02:19:59.498 Please report this problem.
02:19:59.498 
02:19:59.498 Fixed point loop exceeded the maximum number of iterations.
02:19:59.498    at com.google.javascript.jscomp.Compiler.throwInternalError(Compiler.java:2216)
02:19:59.498    at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:448)
02:19:59.499    at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
02:19:59.499    at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1984)
02:19:59.499    at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:717)
02:19:59.499    at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:82)
02:19:59.499    at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:659)
02:19:59.499    at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:656)
02:19:59.499    at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
02:19:59.499    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:19:59.499    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
02:19:59.499    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
02:19:59.499    at java.lang.Thread.run(Thread.java:745)
```

**Comment by gzm0** [comment] 2016-08-01 14:13
This looks like the Google Closure Compiler does not like some of the trees we generate. Do you have a project we can look at?

As a first debugging step, can you feed the fastOptJS to the Google Closure Compiler manually and see if it occurs again?

**Comment by ngbinh** [comment] 2016-08-01 14:22
It happens on our internal repo. Will try to reproduce it. 

I will also try to feed `fastOptJS` through GCC and report back the result here.

**Comment by gzm0** [comment] 2016-08-10 09:36
@ngbinh do you have an update on this?

**Comment by ngbinh** [comment] 2016-08-10 10:07
I tried it on my Mac and things work perfectly. It only fail on our docker build build which run on Ubuntu. Will have to look more closely at it.

**Comment by ngbinh** [comment] 2016-08-20 10:52
@gzm0 I did `fastOptJS` and call 
```sh
java -Xmx8G -jar closure-compiler-v20160713.jar --language_out=ES5 --compilation_level ADVANCED_OPTIMIZATIONS --js myapp.js --externs myapp-jsdeps.js --js_output_file myapp.min.js
```

on the result and everything works. At least `myapp.min.js` exists and looks good.

```sh
0 error(s), 38592 warning(s)
>>> elapsed time 8m9s
```

**Comment by gzm0** [comment] 2016-11-06 20:43
@ngbinh Is this still an issue? Did you figure out why this works on your mac and not in the docker Ubuntu build?

**Comment by sjrd** [comment] 2017-07-09 11:55
Closing this as non-reproducible. It can be reopened with a way for us to reproduce the issue.

**Closed by sjrd** 2017-07-09 11:55 UTC
Labels: bug, upstream
