### ISSUE TITLE
runtime error on 0.6.25 Scala 2.13-M5

### ISSUE THREAD

**Issue by kailuowang** [scala-js/scala-js#3480] opened 2018-11-02 00:52 UTC
This seems to be a regression. When I tried to update Cats to 2.13-M5 from 2.13-M4, I started to randomly get the following error on a test on scalajs

https://github.com/typelevel/cats/pull/2589

>[info] - Try with Throwable.monadError.applicativeError recover consistent with recoverWith *** FAILED ***
[info]   UndefinedBehaviorError was thrown during property evaluation.
[info]     Message: An undefined behavior was detected: scala.runtime.Statics$PFMarker$@25 is not an instance of scala.util.Try
[info]     Occurred when passed generated values (
[info]       arg0 = Failure(java.lang.Exception)
[info]       arg1 = <function1>

The test is basically testing
```scala
F.recover(fa)(pf) <-> F.recoverWith(fa)(pf.andThen(F.pure))
```

where `fa` is a `Try[Int]` and `pf` is a `PartialFunction[Throwable, Int]` generated by scalacheck. 
I tried briefly to minimize it but I couldn't reproduce the error with the following code
```scala
    val F = ApplicativeError[Try, Throwable]
    val pf: PartialFunction[Throwable, Int] = {
      case _: Exception => 0
    }

    F.recover(Failure[Int](new Exception()))(pf)
    F.recoverWith(Failure[Int](new Exception()))(pf.andThen(F.pure))
```

**Comment by sjrd** [comment] 2018-11-03 08:36
I can't do a proper investigation at the moment, but this very much looks like something that would be platform-independent. It's basically a `ClassCastException`. Are you sure it doesn't happen on the JVM as well?

**Comment by sjrd** [comment] 2018-11-03 08:39
See also the commit https://github.com/scala/scala/commit/a7ac9013ad4ad2b95f8a5bb550f9880cd4c538b7 in upstream Scala.

**Comment by erikerlandson** [comment] 2018-11-03 20:37
This seems strange. Is it caused by changes to the actual language between 2.13-M4 and M5?

**Comment by sjrd** [comment] 2018-11-03 21:48
It's a change in the standard library, not in the language.

**Comment by kailuowang** [comment] 2018-11-04 15:49
@sjrd I managed to minimize it to the following consistently failing test on scalajs 0.6.25 scala 2.13-M5
```scala
    val e: Try[Int]  = Failure(new Exception("dfd"))
    val pf: PartialFunction[Throwable, Int]= {
      case _ : RuntimeException => 1
    }
    e.recoverWith(pf.andThen(Try(_)))
```

here is the error message

> [info]   scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: scala.runtime.Statics$PFMarker$@1f is not an instance of scala.util.Try
[info]   at $c_sjsr_UndefinedBehaviorError.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:53333:14)
[info]   at scala.scalajs.runtime.UndefinedBehaviorError.fillInStackTrace(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:137569:67)
[info]   at $c_sjsr_UndefinedBehaviorError.$c_jl_Throwable.init___T__jl_Throwable__Z__Z(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:53455:10)
[info]   at scala.scalajs.runtime.UndefinedBehaviorError.<init>(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:137576:58)
[info]   at scala.scalajs.runtime.UndefinedBehaviorError.<init>(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:137572:67)
[info]   at $throwClassCastException(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:213:46)
[info]   at $as_s_util_Try(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:112580:59)
[info]   at scala.util.Failure.recoverWith(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:135465:13)
[info]   at {anonymous}()(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:336865:16)
[info]   at scala.scalajs.runtime.AnonFunction0.apply(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:72407:23)
[info]   ...
[info]   Cause: java.lang.ClassCastException: scala.runtime.Statics$PFMarker$@1f is not an instance of scala.util.Try
[info]   at $c_jl_ClassCastException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:53333:14)
[info]   at $c_jl_ClassCastException.$c_jl_Throwable.init___T__jl_Throwable__Z__Z(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:53455:10)
[info]   at java.lang.ClassCastException.<init>(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:110719:58)
[info]   at $throwClassCastException(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:214:36)
[info]   at $as_s_util_Try(/Users/kailuowang/projects/typelevel/cats/tests/.js/target/scala-2.13.0-M5/cats-tests-test-fastopt.js:112580:59)

**Comment by sjrd** [comment] 2018-11-04 17:03
Thanks for the reproduction, I can indeed reliably observe the error with that snippet.

I understand why the error happens, [the new `Failure.applyOrElse`](https://github.com/scala/scala/blob/8a52aa19703004f0eb22d72a1efc82617924db32/src/library/scala/util/Try.scala#L236-L242):
```scala
  override def recoverWith[U >: T](pf: PartialFunction[Throwable, Try[U]]): Try[U] = {
    val marker = Statics.pfMarker
    try {
      val v = pf.applyOrElse(exception, ((x: Throwable) => marker).asInstanceOf[Function[Throwable, Try[U]]])
      if (marker ne v.asInstanceOf[AnyRef]) v else this
    } catch { case NonFatal(e) => Failure(e) }
  }
```
is buggy. It assigns to `val v`, which is inferred to be of type `scala.util.Try`, the value `marker`, implicitly cast to `Try` by the compiler (the unsoundness lies in casting the function).

And in fact, I can reproduce the exact same issue on the JVM:
```scala
C:\Users\Sepi>scala
Welcome to Scala 2.13.0-M5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions for evaluation. Or try :help.

scala> import scala.util._
import scala.util._

scala> :paste
// Entering paste mode (ctrl-D to finish)

    val e: Try[Int] = Failure(new Exception("dfd"))
    val pf: PartialFunction[Throwable, Int] = {
      case _: RuntimeException => 1
    }
    val e2 = e.recoverWith(pf.andThen(Try(_)))
    println(e2)

// Exiting paste mode, now interpreting.

Failure(java.lang.ClassCastException: java.lang.Object cannot be cast to scala.util.Try)
e: scala.util.Try[Int] = Failure(java.lang.Exception: dfd)
pf: PartialFunction[Throwable,Int] = <function1>
e2: scala.util.Try[Int] = Failure(java.lang.ClassCastException: java.lang.Object cannot be cast to scala.util.Try)
```
The only difference is that, on the JVM, the `ClassCastException` has been implicitly *caught* an stored in the `Failure` (whereas an `UndefinedBehaviorError` is *fatal* in Scala.js).

So the bug really exists in upstream Scala, and is not specific to Scala.js. `Failure.recoverWith` should be fixed as something like:
```scala
  override def recoverWith[U >: T](pf: PartialFunction[Throwable, Try[U]]): Try[U] = {
    val marker = Statics.pfMarker
    try {
      val v: Any = pf.applyOrElse(exception, ((x: Throwable) => marker))
      if (marker ne v.asInstanceOf[AnyRef]) v.asInstanceOf[Try[U]] else this
    } catch { case NonFatal(e) => Failure(e) }
  }
```

**Comment by sjrd** [comment] 2018-11-04 17:08
Reported upstream as https://github.com/scala/bug/issues/11242.

**Closed by sjrd** 2018-11-04 17:08 UTC
Labels: upstream
