### ISSUE TITLE
test failure "Cannot find length__I in sc_Iterator$SliceIterator" on 2.12 

### ISSUE THREAD

**Issue by adriaanm** [scala-js/scala-js#2435] opened 2016-06-02 17:17 UTC
From https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/399/consoleFull (against scala/scala#2.12.x and scala-js/scala-js)

```
[scala-js] java.lang.AssertionError: Cannot find length__I in sc_Iterator$SliceIterator
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker$$anonfun$findMethodDef$2.apply(BaseLinker.scala:417)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker$$anonfun$findMethodDef$2.apply(BaseLinker.scala:417)
[scala-js] 	at scala.Option.getOrElse(Option.scala:120)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.findMethodDef(BaseLinker.scala:416)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.loop$1(BaseLinker.scala:401)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.findInheritedMethodDef(BaseLinker.scala:407)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.org$scalajs$core$tools$linker$frontend$BaseLinker$$synthesizeReflectiveProxy(BaseLinker.scala:340)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker$$anonfun$org$scalajs$core$tools$linker$frontend$BaseLinker$$linkedClassDef$3.apply(BaseLinker.scala:270)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker$$anonfun$org$scalajs$core$tools$linker$frontend$BaseLinker$$linkedClassDef$3.apply(BaseLinker.scala:257)
[scala-js] 	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[scala-js] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.org$scalajs$core$tools$linker$frontend$BaseLinker$$linkedClassDef(BaseLinker.scala:257)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker$$anonfun$org$scalajs$core$tools$linker$frontend$BaseLinker$$optClassDef$1$1.apply(BaseLinker.scala:169)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker$$anonfun$org$scalajs$core$tools$linker$frontend$BaseLinker$$optClassDef$1$1.apply(BaseLinker.scala:166)
[scala-js] 	at scala.Option.map(Option.scala:145)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.org$scalajs$core$tools$linker$frontend$BaseLinker$$optClassDef$1(BaseLinker.scala:166)
[scala-js] 	at org.scalajs.core.tools.linker.frontend.BaseLinker$$anonfun$11.apply(BaseLinker.scala:176)
```

/cc @lrytz

**Comment by sjrd** [comment] 2016-06-02 18:07
Duplicate of #2434

**Closed by sjrd** 2016-06-02 18:07 UTC
