### ISSUE TITLE
scalajs-test-suite-2.11.html is failing on a couple of tests.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2037] opened 2015-11-19 12:47 UTC
The same tests with pass on sbt. 
In the browsers (Chrome and Firefox) the error appear only with full optimization.

![screen shot 2015-11-19 at 13 38 56](https://cloud.githubusercontent.com/assets/3648029/11271020/ab5dcff2-8ec3-11e5-8807-a76e31a76262.png)

**Comment by sjrd** [comment] 2015-11-19 14:05
No I think the same tests are *ignored* in sbt in fullOpt. They should also be ignored in the browser. This probably just means that the HTML runners should add the `fastopt-stage` and `fullopt-stage` like we do in sbt at https://github.com/scala-js/scala-js/blob/master/project/Build.scala#L1076-L1077

**Comment by sjrd** [comment] 2015-11-19 14:05
Also I think this is a duplicate of #1887.

**Comment by nicolasstucki** [comment] 2015-11-19 14:16
The first failing test is a duplicate from #1887, the second is new.

**Comment by sjrd** [comment] 2016-01-08 13:10
This was fixed in #2140.

**Closed by sjrd** 2016-01-08 13:10 UTC
Labels: bug
