### ISSUE TITLE
Crossproject artifact name changes if listed in aggregate

### ISSUE THREAD

**Issue by matthughes** [scala-js/scala-js#1471] opened 2015-02-03 19:45 UTC
If I list my project like this:

```
lazy val common = crossProject
lazy val commonJS = common.js
lazy val commonJVM = common.jvm

lazy val root = project.aggregate(ui, web)
```

The resulting jars for commonJS and commonJVM are named correctly.  However, if I list the js/jvm projects in the aggregate:

```
lazy val common = crossProject
lazy val commonJS = common.js
lazy val commonJVM = common.jvm

lazy val root = project.aggregate(ui, web, commonJS, commonJVM)
```

The jars are named "commonjs_...jar", "commonjvm_...jar".

I can fix this if I specify the name in the settings, but curious if this is expected behavior:

```
lazy val common = crossProject
lazy val commonJS = common.js.settings(name := "common")
lazy val commonJVM = common.jvm.settings(name := "common")

lazy val root = project.aggregate(ui, web)
```

**Comment by gzm0** [comment] 2015-02-03 20:10
Not, this is definitely not expected behavior, as it defies the purpose of the cross project for published libraries...

**Comment by gzm0** [comment] 2015-02-03 20:12
Hold on, what happens if you set the name in `crossProject`:

```scala
lazy val common = crossProject.settings(name := "common")
```

Are you sure this depends on whether you aggregate the projects or not?

**Comment by gzm0** [comment] 2015-02-03 20:13
@sjrd we should probably default-set the name based on the value we assign to...

**Comment by gzm0** [comment] 2015-02-03 20:14
Actually for any cross project, the default name should derive from the id of the cross project, and not the id of the individual sub-projects, right?

**Comment by matthughes** [comment] 2015-02-03 20:30
@gzm0 You get the correct behavior if you set name on either the crossProject or the individual crossProject.js/jvm.

It does seem to only happen when you aggregate.  Without aggregation, my projects were still getting referenced and generating the appropriately named jars without having to specify name.

**Comment by sjrd** [comment] 2015-02-03 20:33
You're not supposed to *anything* with the results of the `.js` and `.jvm` calls, except put them in `lazy val`s directly.

**Comment by matthughes** [comment] 2015-02-03 20:40
@sjrd So how to aggregate?  You can't put a crossProject directly in aggregate.

**Comment by sjrd** [comment] 2015-02-03 20:42
Oh, no, that, you can. I was referring to `common.js.settings(name := "common")`

**Comment by sjrd** [comment] 2015-02-03 20:54
> we should probably default-set the name based on the value we assign to...

I thought `name` defaulted to `id` in sbt? Maybe we could override that and make it default to the `id` of the `crossProject`. It would make sense.

**Comment by sjrd** [comment] 2015-02-03 20:57
If the mere fact of aggregating changes things, that looks more a bug of sbt than ours. Or it's a "feature". Anyway, as @gzm0 suggested, if setting `name := "common"` in the `crossProject`'s settings works, that's definitely the way to go.

**Comment by gzm0** [comment] 2015-02-03 21:09
> I thought name defaulted to id in sbt?

Yes, it does. But the id of the real projects have JS/JVM appended. So it is actually a bug that the project names do not have the prefix all the time...

We just should make this the default in `0.6.1` and we are good.

**Comment by sjrd** [comment] 2015-02-03 21:10
Agreed.

**Comment by gzm0** [comment] 2015-02-04 18:29
Hmm... we also have a constructor that takes two ids:

```scala
def apply(jvmId: String, jsId: String, base: File, crossType: CrossType): CrossProject
```

should we change it to take a base id (breaking change), or just not set the name in this case (a bit strange IMO)?

**Comment by sjrd** [comment] 2015-02-04 19:59
> should we change it to take a base id (breaking change), or just not set the name in this case (a bit strange IMO)?

Let's not break just yet, when we're finally telling people we won't be breaking things anymore ^^

We can introduce an additional overload with only ID, or, probably better, with two IDs and an explicit name.

We could also have the existing overload "guess" a name by selecting the longest common prefix of the two IDs, discarding a trailing `J` (because JS and JVM start with 'J' ^^). But that looks sketchy.

**Comment by gzm0** [comment] 2015-02-04 20:27
> We can introduce an additional overload with only ID, or, probably better, with two IDs and an explicit name.

We have the overload taking only a single id, so we should set the name there I suppose. We can add the one that takes an additional base name, but we could also tell people to just set it (only usage of the baseName parameter).

I am heavily opposed to guessing a name to be honest.

**Comment by sjrd** [comment] 2015-02-04 20:30
> I am heavily opposed to guessing a name to be honest.

I thought so ^^ I wasn't happy with that either.

Telling people to set the name explicitly looks OK.

**Closed** 2015-02-05 07:22 UTC
Labels: bug
