### ISSUE TITLE
 scalajs-cli 2.12

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-js/scala-js#2791] opened 2017-03-03 20:42 UTC
please release  scalajs-cli 2.12
http://search.maven.org/#search%7Cga%7C1%7Cscalajs-cli

**Comment by sjrd** [comment] 2017-03-03 21:12
Duplicate of #2677. It will be released with 0.6.15.

**Closed by sjrd** 2017-03-03 21:12 UTC

**Comment by Andrei-Pozolotin** [comment] 2017-03-03 22:08
thank you
