### ISSUE TITLE
"a.y is not a function" when writing a property called "y" from javascript into an object

### ISSUE THREAD

**Issue by fdietze** [scala-js/scala-js#1906] opened 2015-09-16 17:26 UTC
I just stumbled upon this problem:

I define a class in scalajs, export it to javascript and run it through fullOpt.
Then I create a new instance from that class from javascript and set a field, which is not defined in the class. In my case `y`.

Then javascript crashes with the following error: `a.y is not a function`.

The error makes sense. The optimizer cannot know what I write to the object from javascript and runtime and uses these short names as minified/optimized internal function names. So this name-clash can occur.

This was very strange to me in the first place, because the error occurred in production, but not in development mode.

I was able to worked around this by specifying the member `y` in the class:

```
@JSExport def y(): Int = -1
```

using a `var` or def without `()` was not working, I cannot explain why.

I think this should be mentioned in http://www.scala-js.org/doc/export-to-javascript.html, to prevent others losing lots of time on such an error.

Are there any other thoughts on this?

**Comment by sjrd** [comment] 2015-09-16 17:56
Hi,

It is indeed against the specification to add a field to a Scala.js class that does not export it. Actually even your exporting a `def y()` and then setting `y` from JS is against the spec, and could break.

What you have to do is to provision for the field and declare it as an `@JSExport var y: Int = -1`. The type should also be correct, so if it's `Int` you can only put an integer in that field. With an exported var, your JS code doesn't have to create a new field, and therefore you're in-spec.

It doesn't fail in dev mode because the dev mode uses longer names. In particular nothing could be named `y` in dev mode, but that's an implementation detail of the current impl. I guess we could [seal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal) all Scala.js objects in dev mode to highlight this error earlier.

**Comment by fdietze** [comment] 2015-09-16 19:24
As mentioned above, using `var` also was my first intuiton. But now - I tried it again - it fails with the same error message.

Sealing sounds like a good idea to prevent confusion.

**Comment by sjrd** [comment] 2015-09-16 19:27
If `var` does not work, I would very much like a reproduction. It might be a bug.

**Comment by fdietze** [comment] 2015-09-20 23:30
I'm very busy right now, but I'll come back and make a reproducible example.

**Comment by sjrd** [comment] 2015-11-18 07:49
Ping @fdietze

**Comment by sjrd** [comment] 2015-12-11 07:39
Closing as there was no follow up.

**Closed by sjrd** 2015-12-11 07:39 UTC
