### ISSUE TITLE
Proposal: Defining "JavaScript classes" in Scala.js

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1795] opened 2015-07-13 14:55 UTC
This has been the Achilles' heel of Scala.js: how to define, in Scala.js, a class inheriting from a JavaScript class. This essentially means defining a "JavaScript class" (extending js.Object or some other raw JS class) from Scala.js.

I have been thinking this through for about 2 years (!), and have finally, I think, come up with appropriate semantics for such a language feature. This proposal lays down an enhancement proposal for Scala.js that specifies all this.

## The problem

I have a JavaScript class `Foo`, defined as follows (ES6 syntax):
```js
class Foo {
  constructor(x, y) {
    this.x = x;
    this.y = y;
  }
  print() {
    console.log(`(${x},${y})`)
  }
}
```
A potential facade for this class could be:
```scala
class Foo(val x: Int, val y: Int) extends js.Object {
  def print(): Unit = js.native
}
```
I want to *extend* this class from a class `Bar` defined in Scala.js, to add a third value, and override the `print` method to also display the third value. (Please forgive me the contrived example which is even likely not to respect the LSP.) If I were to define it in JavaScript, I would write:
```js
class Bar extends Foo {
  constructor(x, y, z) {
    super(x, y);
    this.z = z;
  }
  print() {
    console.log(`(${x},${y},${z})`)
  }
}
```
Ideally, I want to write something close to this:
```scala
class Bar(x: Int, y: Int, val z: Int) extends Foo(x, y) {
  override def print(): Unit =
    println((x, y, z))
}
```

## Class notation

A class which extends `js.Any` and has the annotation `js.annotation.ScalaJSDefined` is not a facade type, but a Scala.js-defined JavaScript class:
```scala
@ScalaJSDefined
class Bar extends js.Object
```
Note: `@ScalaJSDefined` is awkward. In the future, we might want to invert the meanings: no annotation means Scala.js-defined; and `@js.native` means facade. See later for details about that.

The type `Bar` is still a *raw JS type*, so accesses to members of that type are always done "the JS way" (no mangling of member names).

## Constructors

Overloaded constructors are allowed, and run-time dispatch is used for choosing the overloads.

By default, the constructors are not accessible from JavaScript. The constructors of a Scala.js-defined JS class are only visible to Scala.js code.

`@JSExport` can be used to export constructors to JavaScript code, just like Scala.js Scala classes.

Rationale: these classes can be dead-code-eliminated if they are not instantiated nor exported.

If several constructors are exported, they must be exported under the same name. It is not allowed to export constructors under several names. (Variant: exporters can be exported under several names, but all the exported constructors must have the same set of names.)

Rationale: this allows the class to be its own export, which will allow meaningful subclassing by a JavaScript-defined class.

*Implementation restriction:* As a first implementation, it will not be allowed to export a subset of the constructors. Either none or all must be exported.

## Method declaration

A Scala.js-defined JS class can define methods. All public *and protected* methods are always "exported" to JS with semantics close to `@JSExport` for methods in Scala classes.
```scala
@ScalaJSDefined
class Bar extends js.Object {
  def foobar(a: Int, b: String): String =
    a.toString + b
}
```
*Implementation note:* formally, parameters and result type are always erased/boxed in the visible type (like in exports).

Overloading is possible, and is resolved almost like `@JSExport`. Unlike exports, the runtime overloading logic will call the variants with *static dispatch*. To be clear, instead of calling `this.foobar__I__T(a, b)`, it will call `Bar.prototype.foobar__I__T.call(this, a, b)`. This is necessary for *super calls* coming from subclasses of `Bar` to deal correctly with combinations of overloading and overriding.

This also means that, when overriding an overloaded method, the runtime overloading logic must be reemitted, even if the set of alternatives does not change (contrary to how exports handle this).

## References to `this`

References to members of `this` in the body of the methods (implicitly or explicitly) are dealt with just like any other raw JS type, which means that runtime overloading is always used, at the end of the day. This is necessary to have consistent behavior between `this.foo(5)` and `{ val self = this; self.foo(5) }`.

## Super calls

Super calls, just like references to members of `this`, always use runtime overloading in the super implementation. This is also true for super constructor calls.

## Getter and setter declaration

Like in exports, a `def` without parentheses is visible as a *getter* in JavaScript. A `def` whose Scala name ends in `_=` is visible as a *setter* in JavaScript.

## Field declaration

*Unlike* in exports, `val`s and `var`s are *not* implemented with getters and setters. They become *direct fields* of the object. This is necessary to have meaningful overriding of a field inherited from a parent class.

A `val` that implements or overrides an inherited `def` without parentheses will have the appropriate semantics as soon as the field *exists* on the object (since it will be seen before a getter/setter inherited from the prototype). However, when creating the field in the first place, we must bypass a potentially inherited getter/setter. We can do this with `Object.defineProperty`.

(This might not play well with strong mode, though. But we probably don't want Scala.js-defined JS classes to have strong mode semantics anyway.)

Unlike for Scala classes, fields will not be all created before all constructors start executing. The fields for each class will be created right after the call to the super constructor, in the primary constructor. *Rationale:* together with run-time dispatch of overloaded constructors, this allows to implement the constructors as normal JS constructors (which is good for subclassing from JS).

Compared to how this would work in Scala classes, this has surprisingly few caveats. The only semantic discrepancy I can foresee happens when accessing a field before it has been initialized by the dominating override of that field:

* Before its first creation, it would be `undefined` instead of the zero of the type (which means reading it is undefined behavior).
* For `val x: Int = 3`, then `override val x: Int = 5`: after the superclass has initialized `x` and before the subclass has initialized `x`, on the JVM `x` would be seen as 0. On JS it would be seen as 3.

In both cases, reading `x` in that interval is probably a bug in the first place anyway.

The Scala specification prevents to override a `val` or a `val` with getter/setter `def`s. This also reflects the JS limitation that "overriding" a field with getter/setters does not really work as expected (because getter/setters are on the prototype, which is checked after the object itself).

## `@JSName`

It is of course invalid to `@JSExport` or `@JSExportAll` members of a Scala.js-defined JS class. It is however possible to use `@JSName` to change the name visible in JavaScript, just like for any raw JS type.

## `apply`, `@JSBracketSelect` and `@JSBracketCall`

`apply` methods or fields without `@JSName` are forbidden. So are methods with `@JSBracketSelect` or `@JSBracketCall`.

*Rationale:* Their semantics cannot be implemented.

## Private members

Private fields are mangled in a way that, hopefully, will not clash with any JavaScript identifier. In ES6, we can use unique Symbols for that.

Private methods, and any other instance member which is not directly visible to JavaScript, will be completely hidden from JavaScript (not visible on the object nor the prototype). *Implementation note:* Make all of those static methods.

Private methods cannot be overloaded. It is also forbidden for a private method to have the same name as a non-private method.

*Implementation note:* this means that, although specified with run-time dispatch of overloads, calls to private methods can be implemented with static dispatch.

## Abstract members in native JS classes and traits

Since Scala.js-defined JS classes offer a way to implement native JS classes and traits, it is now useful to be able to define abstract term members in JS classes and traits. So now, term members of native JS classes and traits can either be abstract or implemented with `= js.native`.

## Pure JS interfaces

Due to the fact that native JS traits have concrete members with a dummy `= js.native`, it is not allowed to mixin a native JS trait in a Scala.js-defined JS class. The mixed in members would delegate to a non-existing implementation. I would, however, be very useful to declare interfaces to be implemented by JS classes.

The `@ScalaJSDefined` can also be used on a trait extending `js.Any`. This marks it as a Scala.js-defined JS trait. A Scala.js-defined JS trait must meet all of the following requirements:

* Not contain any concrete term member
* Not extend directly a native JS trait (it is OK to extend a native JS class and/or Scala.js-defined JS traits)

Such a trait is a pure interface, in the sense that it does not even have a trait impl class, and any class extending it must provide the members from its class hierarchy.

Once Scala.js-defined JS "interfaces" exist, there remains little value for native JS traits. They are useful only if we want to avoid code duplication when writing facades for native JS classes, if several classes are unrelated but expose a similar API (e.g., the various kinds of typed arrays).

In most cases, existing facade traits should be become Scala.js-defined JS interfaces. Note that this breaks binary compatibility of said traits. So libraries choosing to do so should advertise this as a breaking change.

## Backwards compatibility

As presented above, this is fully backwards source compatible with the current semantics of Scala.js. It can also probably be made backwards binary compatible.

## Breaking backwards compatibility

As noted above, the `@ScalaJSDefined` annotation is very awkward. In the future, I would like that `@ScalaJSDefined` be the default. To get a facade type, one would need to annotate the class with `@js.native`.

The migration path would be:
* In 0.6.x: have `@ScalaJSDefined` and `@js.native`. A class with neither of those will be reported as a warning, saying `@js.native` should be added to future-proof it.
* In the next major release: classes without the annotation would be Scala.js-defined. `@ScalaJSDefined` becomes deprecated, and should be removed.

## (Anonymous) nested classes

It is possible and valid to have Scala.js-defined JS classes nested in other classes (unlike facade types). In that case, it is not valid to `@JSExport` its constructors (unless `@JSExport` of nested classes is revived, see #354).

Since anonymous classes cannot have annotations, with the current state it is in fact not possible to declare an anonymous Scala.js-defined JS class, because it needs `@ScalaJSDefined`. To overcome this, and since anonymous facades are invalid anyway and cause compile errors at the moment, an anonymous class inheriting from `js.Any` is automatically a Scala.js-defined JS class.

## Extend a Scala.js-defined JS class from JavaScript

`@JSExport`ed constructors can be used as parent classes from JavaScript to subclass Scala.js-defined JS classes. In fact, exported constructors are true ES6-style classes.

## Implementation concerns

A Scala.js-defined JS class would be a new `ClassKind` of `ClassDef` in the IR. It would be a raw JS type, but with member definitions.

All public and protected fields end up having String names, since they must be visible in JS. For methods, we probably want to emit private implementations of all methods, with static types and overloads, as static methods (instead of instance methods). The public, string-named methods would dispatch and box/unbox (similar to exports), then call the appropriate static implementation.

## Open questions: full traits

It might be possible to extend Scala.js-defined JS traits so that they can also define concrete term members, effectively making them all powerful. However, at this point there are still non trivial questions to be answered regarding the "hidden" and synthetic things that scalac emits for traits, e.g., super accessors.

This proposal therefore does not allow full Scala.js-defined JS traits. It might be extended by a follow up proposal.

**Comment by sjrd** [comment] 2015-07-13 14:55
Comments welcome!

Ready, set, go!

**Comment by benjaminjackman** [comment] 2015-07-13 15:58
'@JSScalaDefined is awkward' Agreed, maybe a better name can be thought of? Even though it's seems to be a band-aid and switching facades over to requiring js.native seems the right path for consistency, it's still kind of ugly.

`@JSExport can be used to export constructors to JavaScript code` Does this just mean if that annotation is applied to the class then the constructor method is emitted? It seems that way just want to double check.

**Comment by sjrd** [comment] 2015-07-13 17:55
> maybe a better name can be thought of?

Sure. Suggestions welcome. `@JSScalaDefined` was the least bad I found myself ^^

> Does this just mean if that annotation is applied to the class then the constructor method is emitted?

It means exactly the same thing as `@JSExport` on a Scala.js Scala class: a JavaScript constructor is exposed in the exports namespace (typically the global scope) which allows to do `new Stuff(a, b)` from JS, and have that create an instance of that class.

**Comment by gzm0** [comment] 2015-07-13 22:17
Are references to `super` allowed? (how would you do that reliably in JS?)

**Comment by sjrd** [comment] 2015-07-13 22:30
Yes, with precisely the same mechanism that we use for super calls in scala classes, i.e., `SuperClass.prototype.method.call(this, arg1, arg2)`

**Comment by gzm0** [comment] 2015-07-13 22:41
Another thing: Will Scala.js leak members on these classes or are these safe to use in iteration (and such)?

**Comment by chandu0101** [comment] 2015-07-14 01:10
much awaited feature for me  :+1:

**Comment by chandu0101** [comment] 2015-07-14 04:01
>There would be no way to declare "Scala.js-defined JS traits", so mixin composition is not available when writing Scala.js-defined JS classes. We should keep an eye out for mixins in upcoming ES, and make sure we can play well with those in the future.

does this mean 

```scala
class Foo(val x: Int, val y: Int) extends js.Object {
  def print(): Unit = js.native
}
trait CommonCode {
 def common() = println("common")
}
class Bar extends Foo with CommonCode // not allowed ? 

```

or its related to traits that extends js.Any ... ?

**Comment by sjrd** [comment] 2015-07-14 04:43
> Will Scala.js leak members on these classes or are these safe to use in iteration (and such)?

For top-level classes, there will be no member other than the `val`s and `var`s declared explicitly in the code. So no there's no leak. Nested classes will have fields for captures, however.

**Comment by sjrd** [comment] 2015-07-14 04:46
`@chandu0101` Your snippet is not valid for another reason: it is not possible for a class to extend both `js.Any` and something that does not itself extend `js.Any`. This is an existing restriction, which will be maintained.

**Comment by chandu0101** [comment] 2015-07-14 08:14
>@chandu0101 Your snippet is not valid for another reason: it is not possible for a class to extend both js.Any and something that does not itself extend js.Any. This is an existing restriction, which will be maintained.

oh ok :(

**Comment by gzm0** [comment] 2015-07-14 17:52
> For top-level classes, there will be no member other than the vals and vars declared explicitly in the code. So no there's no leak. Nested classes will have fields for captures, however.

OK. But we will leak Scala.js specific members on the prototype I assume. Is there a way we can make these invisible? I'm thinking of something like defining them statically in a block which is private to the class definition and then `call`ing them. This of course would come at the cost of having to do dynamic dispatch again when invoking a super call (now that I think of it, we might have to do this anyway for the semantics to be correct when invoking super).

Something like this:

```javascript
var myCtor = function() {
  this.a = 1;
  this.b = 2;
};

(function() {
  var foo__I = function() { return 1; };
  var foo__I__I = function(i) { return i * 2; };
  myCtor.prototype.foo = function(i) {
    if (i == (void 0)) return foo__I.call(this);
    else return foo__I__I.call(this, i);
  };
})();
```

About visibility:

- I think protected should be entirely disallowed. It does not make sense
- What is the relationship with companions? (matters how we implement private methods)

I think for private methods we have two choices:

**Make them pure helpers**
- Compile-time dispatch
- Companion cannot call them (!)

**Make them "normal"**
- Runtime dispatch
- Companion can call them

I prefer option one, since having private methods at all is IMO already a stretch (but a useful one). I think we should not give an illusion of private methods if we cannot actually implement it that way in JS (and with fully static dispatch we can, just define them in an enclosing scope, no one sees them).

**Comment by sjrd** [comment] 2015-07-14 18:13
> OK. But we will leak Scala.js specific members on the prototype I assume. Is there a way we can make these invisible?

Yes, I plan to move all the methods not visible to JS to static methods. They don't need to be shadowed with special JS syntax. They will just be static methods with identifier names (not strings), that are therefore protected by the giant anonymous function providing Scala.js' scope. The IR checker will verify that a Scala.js-defined JS class does not have non-exported member methods. The linking pipeline is already equipped to deal with static methods in arbitrary ClassKinds (even hijacked classes ^^).

> This of course would come at the cost of having to do dynamic dispatch again when invoking a super call (now that I think of it, we might have to do this anyway for the semantics to be correct when invoking super).

Yes, runtime overloading dispatch is necessary on every super call. We call the JS-visible method on the superclass every time. Super calls should not behave any differently based on whether the super class is a native JS class or a Scala.js-defined JS class, so there's no choice here.

> I think protected should be entirely disallowed. It does not make sense

I makes sense if you want to protect your Scala.js code from accidentally accessing those methods (and prevent them from showing up in auto-completion), but you still want to override them in subclasses.

> I think we should not give an illusion of private methods if we cannot actually implement it that way in JS

Technically, it *is* possible to implement completely private instance methods. They just have to have names generated at random at runtime (or, better, be unique symbols) and added on the prototype with a `defineProperty` that makes them non-enumerable. But this will hurt performance dramatically (anything that's not a stupid field on a prototype is bad).

> I think for private methods we have two choices:

Actually, my current preference is a third choice:

* Forbid overloading of private methods altogether (including wrt. non-private methods with the same name)
* This means compile-time or run-time dispatch is irrelevant
* This means they can be called from the companion object, which is nice (preventing it might make some patterns of code impractical to implement)

The restriction on overloading of private methods is easily worked around with more specific names. Since they are private, the workaround does not leak into the API of the object.

I don't really like using compile-time dispatch for private methods because that means they don't behave like non-private methods in the same class (gurg!). And I don't really like using run-time dispatch either, because they should be overhead-free to really be usable as helpers. So disabling dispatch altogether came to me as the solution to my dilemma ^^

**Comment by gzm0** [comment] 2015-07-14 19:46
I agree with all of this.

Protected: Allow, but no difference on JS side (consistent with semantics in `@JSExport`)

Private methods: Disallow overload, give companion access (w/o overhead). (Good luck to properly dispatch this in the backend :P, but we'll manage...)

**Comment by gzm0** [comment] 2015-07-14 19:48
About fields: Couldn't we restrict what you are allowed to put in fields (or change the initialization semantics) so that on the JS-side, we are able to emit a normal ctor?

**Comment by gzm0** [comment] 2015-07-14 19:49
(Btw. I leave it up to you, @sjrd, to update the description at the top as this discussion goes, it's probably bettern than both of us fiddling with it)

**Comment by sjrd** [comment] 2015-07-14 19:55
> About fields: Couldn't we restrict what you are allowed to put in fields (or change the initialization semantics) so that on the JS-side, we are able to emit a normal ctor?

The only thing that prevents us from emitting a normal JS constructor are overloaded constructors. If we disallow overloaded constructors, this becomes easy, and we even easily export the class for subclassing by JS.

**Comment by sjrd** [comment] 2015-07-14 19:59
Hum, no, that's not entirely true. You are right. The constructor a superclass could call a method overridden in a subclass, which tries to read a field of the subclass. At that time, the field would not exist yet. This would result in an `undefined` -> undefined behavior.

**Comment by gzm0** [comment] 2015-07-14 20:08
I think that is actually a very reasonable behavior: Think of it: In a JVM style class, the field will be `null` in the same case (except for early initializers which we should fully disallow). So it is very sensible, that the field is undefined in a JS class.

> The only thing that prevents us from emitting a normal JS constructor are overloaded constructors

I think it is very reasonable to say the primary ctor is what is getting exported and inherited from (even in Scala this is the case).

Secondary constructors **must** call the primary ctor in Scala, so doing the same in JS is easy (but one could not inherit from them). So maybe we should disallow exporting of secondary ctors or disallow secondary ctors alltogether and tell people to use factories instead.

**Comment by gzm0** [comment] 2015-07-14 20:09
By the way: The proposal does not state default parameter and vararg calling convention. I assume these are just like `@JSExport`.

**Comment by sjrd** [comment] 2015-07-14 20:21
> By the way: The proposal does not state default parameter and vararg calling convention. I assume these are just like `@JSExport`.

Indeed.

> I think it is very reasonable to say the primary ctor is what is getting exported and inherited from (even in Scala this is the case).

No, it's not the case in Scala: when extending a class with secondary constructors, your primary constructor can call any of the superclass' secondary constructors.

If the primary constructor becomes the JS constructor, and it happens to have at least one parameter, it is not possible to call correctly any secondary constructor (whether from `new` or from a subclass).

So even disallowing exporting secondary constructors is not a viable option, unfortunately.

**Comment by sjrd** [comment] 2015-07-14 20:33
Another solution that would solve those problems, instead of brutally disallowing any secondary constructors, is to allow them but use, again, run-time dispatch of the appropriate overload. This would also allow to extend from such a class from JS easily.

In cases where there is no secondary constructor, this behaves the same as the variant where we disallow secondary constructors.

In that case, either all or none of the constructors are exported. This might prevent to export any of the constructors if one of them is private, though ^^

**Comment by gzm0** [comment] 2015-07-14 20:39
I like the run-time dispatch for the ctors. It makes sense and is consistent with the rest.

I have only one very ugly solution to solve the private ctors (which we should have): Each class has a static field that says whether we are calling a private ctor... Based on that, the ctor behaves differently... Call-site emits switches to the method before calling ctor. Since field is private, private ctor cannot be called.

**Comment by sjrd** [comment] 2015-07-14 20:44
> I like the run-time dispatch for the ctors. It makes sense and is consistent with the rest.

Yes, the more I think about it, the more I like it as well.

> I have only one very ugly solution to solve the private ctors (which we should have)

Ouch ^^ Fortunately, that would only be needed if both a) there is at least one private constructor and b) the constructors are exported. With the appropriate IR node, the decision of how to encode the call site can be done at link time, I believe.

**Comment by sjrd** [comment] 2015-07-15 11:36
Updated the text of the proposal to include all comments until now.

**Comment by sjrd** [comment] 2015-07-15 15:41
Implementation notes.

So, it seems I cannot manage to implement this specification (the part about overriding and overloading methods declared in super native classes) in a backward binary compatible way. To be more precise, I would need, in raw JS classes (and traits), to generate "exporter methods" depending on `@JSName`, just like we do for exports. This is so that I can have refchecks and erasure check for inheritance and overloading problems at the js-name level in my class hierarchy.

So, it would not be possible to extend a facade class or trait that was compiled with an earlier version of the compiler. We can detect this in PrepJSInterop if we add an arbitrary bit of data (as an annotation on the class symbol or something like that) somewhere in the symbols of raw JS types compiled with the new version of the compiler: we can check that this bit is present on all the ancestors of a Scala.js-defined JS class, and otherwise we issue a compile error. To fix this compile error, the ancestors would need to be recompiled with a new version of the compiler to get the "exporter methods", and the witness bit.

By the fact that this is a compile error, we somehow restore backward binary compatibility, since we make it impossible to write a code that would not be backward binary compatible. Hence, binary compatibility is up to par with source compatibility, and all is well.

**Comment by sjrd** [comment] 2015-07-16 08:13
Well, that strategy is much worse: it's not even source compatible, as it won't let this facade compile:
```scala
trait JQuery extends js.Object {
  def `val`(): Any
  @JSName("val") def value(): Any
}
```
which is a pretty valid use of facades. So no go for that.

Back to figuring something out that does not involve modifying the binary output of facades.

**Comment by sjrd** [comment] 2015-07-19 20:06
Ongoing PR at #1809.

**Comment by sjrd** [comment] 2015-07-22 08:16
I realized that not really considering traits is a mistake, because then there is no sensible way one could even *implement* a JS interface. Consider:
```scala
trait Foo extends js.Object {
  val bar: Int = js.native
}
```
and the candidate "implementation" of that interface in Scala.js:
```scala
@ScalaJSDefined
class FooImpl extends Foo {
  override val bar: Int = 3
}
```
That would not work in any sensible way, if only because the constructor of `FooImpl` will try and call the trait initializer of `Foo`, which is not emitted. Hence linking error.

So at the very least, we should emit a compile error if we try to mixin an (implicitly native) JS trait in a Scala.js-defined JS class.

*But*, we could also allow Scala.js-defined JS traits. Let's first restrict them not to have any implementation (they are pure interfaces):
```scala
@ScalaJSDefined
trait Foo extends js.Object {
  val bar: Int
  def foobar(x: Int): Int
}
```
There would be no trait impl class for this pure interface, and therefore it would be OK to mix it in:
```scala
@ScalaJSDefined
class FooImpl extends Foo {
  val bar: Int = 3
  def foobar(x: Int): Int = x + 1
}
```
And the anonymous class version would work as well:
```scala
new Foo {
  val bar: Int = 3
  def foobar(x: Int): Int = x + 1
}
```
Now, what happens if we try to remove the restriction that it has to be a pure interface?
```scala
@ScalaJSDefined
trait Foo extends js.Object {
  val bar: Int = 3
  def foobar(x: Int): Int = x + 1
}
```
Now we have an implementation class like this:
```scala
object Foo$class {
  def $init$($this: Foo): Unit = {
    $this.bar_=(3)
  }
  def foobar($this: Foo, x: Int): Int = x + 1
}
```
and we can try and mix it in:
```scala
@ScalaJSDefined
class FooImpl extends Foo {
  def babar(): Int = foobar(bar)
}
```
which will become something like this after mixin:
```scala
@ScalaJSDefined
class FooImpl extends Foo {
  private[this] var _bar: Int = _

  def this() = {
    super();
    Foo$class.$init$(this)
  }

  def bar: Int = _bar
  def bar_=(v: Int): Unit = _bar = v

  def foobar(x: Int): Int = Foo$class.foobar(this, x)

  def babar(): Int = foobar(bar)
}
```
The funny thing is, in principle, there's nothing wrong with this class definition. It is just like any other Scala.js-defined JS class, and some of its methods call Scala methods in the trait impl (which really has nothing special, it's just like a trait impl for any other Scala class). So we could in theory completely support this.

One tricky part, though, is to remember/detect, somehow, that `_bar`, `bar`, `bar_=` and `foobar` are *exposed* in `FooImpl` (they are already exposed in `Foo`, which is good, and *not* exposed in `Foo$class`, which is good too), so that `this.foobar(this.bar)` in `babar()` translates correctly to `this["foobar"](this["bar"])` in the IR (for example).

**Comment by mysticfall** [comment] 2015-07-22 09:04
I've been developing a Web Components framework recently, and it seems this feature could really benefit my project, if mixin composition was also supported.

When defining a custom element, the Web Components API expects a prototype object which inherits from `HTMLElement`, which I believe to be easily achievable once this feature is completed.

But providing a common functionalities would be problematic, since a component can inherit from any arbitrary sub type of `Element` prototype, so we can't define them in its parent class.

Using a trait would be an ideal approach, but as I read it won't be supported, I was about to let users to define a proxy component instance and wire it up to the 'real' JS prototype using macros.

So, I'm glad it's been reconsidered, and very eager try it as soon as it's available if it'll indeed be supported in future.

**Comment by sjrd** [comment] 2015-07-22 11:56
I think I found an *awesome* solution to the private overloaded exported constructors :-D That does not involve the hack with a global var.

First, let's recap the issues: if one declares several overloaded constructors, at least one of them is private, and wants to *export* the public and protected ones. Something like this:
```scala
@ScalaJSDefined
class Foo private (x: Int, y: String) extends js.Object {
  @JSExport
  def this(x: Int) = this(x, "default")
  @JSExport
  def this(s: String) = this(0, s)
}
```
when translating to the IR, which can only have 1 constructor for the entire class, the constructor must run-time dispatch against the overloads. But then, the constructor, being exported to JS, cannot hide the private constructors to JS while at the same time allow Scala.js code (in the class or its companion) to call it.

Now, we could actually decide to forbid this situation in the first place, on the grounds that this is a private "method" overloaded to other "methods" (constructor methods, but still). And that's fine, because if you're in this situation, you're probably better off using factories anyway.
*Except* that this prevents a very important idiom, which is the single private primary constructor aggregating all the possible ways that secondary constructors can be used (just like above). That cannot be emulated by factories. The primary constructor restriction of Scala makes it very important to be able to do that as well, otherwise the API of the above class cannot be exposed.

But in that idiom, you only need the call the primary constructor (or another private secondary constructor) *from another constructor, in the same object*. Does that ring a bell? How do you restrict a method to be accessed only *from the same object*? With `private[this]`, of course!

But, uh, can you declare a `private[this]` *constructor*!? And can you actually call it from another constructor? Let's ask Scala:
```scala
$ scala 
Welcome to Scala version 2.10.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_39).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :paste
// Entering paste mode (ctrl-D to finish)

class Bar private[this] (val x: Int) {
  def this() = this(3)
}

// Exiting paste mode, now interpreting.

defined class Bar

scala> new Bar(3)
<console>:9: error: too many arguments for constructor Bar: ()Bar
              new Bar(3)
              ^

scala> new Bar()
res1: Bar = Bar@54bec43f
```
Yes! You can! And, hum, does it actually prevent you from calling it with `new` from a method in the class or in the companion?
```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

class Bar private[this] (val x: Int) {
  def this() = this(3)

  def foo(x: Int): Bar = new Bar(x)
}

object Bar {
  def apply(x: Int): Bar = new Bar(x)
}

// Exiting paste mode, now interpreting.

<console>:11: error: too many arguments for constructor Bar: ()Bar
         def foo(x: Int): Bar = new Bar(x)
                                ^
<console>:15: error: too many arguments for constructor Bar: ()Bar
         def apply(x: Int): Bar = new Bar(x)
                                  ^
```
Yes! It does!

So, what we can do about constructors is this:
* Private constructors cannot be overloaded, except if they are `private[this]`. (Or a variant: private constructors cannot be overloaded *with non-private constructors*, except if they are `private[this]`.)
* If you export a Scala.js-defined JS class, all public and protected constructors are exported, but not `private[this]` constructors.

It is then completely possible to *implement* the dispatch, because the code deciding which overload to select (see #1811) only takes into account public and protected signatures. Then the tree of ifs supports all constructors, including `private[this]` ones.

Isn't that beautiful?

**Comment by sjrd** [comment] 2015-07-22 15:01
Hum, Scala.js-defined JS traits with concrete members (i.e., that are not pure interfaces) actually have a lot of difficult implementation issues, even though they look good on paper.

I'll focus on the pure interface version in a first version. That will probably not cover @mysticfall's use case, but at least we'll be able to implement a JS interface.

**Comment by gzm0** [comment] 2015-07-22 16:56
I'm not sure if it is a good idea to force constructors to be `private[this]` it will essentially prevent mixing factories & secondary ctors. We must not forget that there is a fundamental difference between factories and secondary ctors w.r.t. to mixin. Even if we currently don't (fully) support it, we should not rule out the possibility.

Also, the proposal does not allow for immutable classes with copy methods that track some private state:

```scala
final class Avg private (private val sum: Int, private val count: Int) {
  def this() = this(0, 0) // ok
  def this(v: Int) = this(v, 1) // ok

  def acc(v: Int): Avg = new Avg(sum + v, count + v) // fails
  def avg(): Double = sum.toDouble / count
}
```

**Comment by sjrd** [comment] 2015-07-22 18:08
> We must not forget that there is a fundamental difference between factories and secondary ctors w.r.t. to mixin.

Hum, how so?

> Also, the proposal does not allow for immutable classes with copy methods that track some private state:

Aah, nope, indeed :-s

**Comment by gzm0** [comment] 2015-07-22 19:01
Ctors allow for mixin (and extension for that matter), factories don't 

```scala
new Foo with Bar // ok
Foo with Bar // not ok
```

**Comment by mysticfall** [comment] 2015-07-23 11:15
@sjrd Don't worry, I'm glad to see that the possibility is open for future improvements. Thanks!

**Comment by sjrd** [comment] 2015-07-27 08:13
So, back to this constructor thing ^^ Apparently it's impossible to get away without some means to call private constructors with a magic indicator.

There is still the problem of run-time vs compile-time overload dispatch.

* We definitely want run-time dispatch for the exported constructor (no choice, actually)
* Hence, we also want run-time dispatch for public and protected constructors
* We more or less *need* compile-time dispatch when *delegating* from one constructor to another (the `this()` call). That's fine, this is internal.

But what about dispatch when calling a private constructor? One thing to note is that, if we call a public or protected constructor, even though we want run-time dispatch, we definitely don't want that to dispatch at run-time to a private constructor.

When calling a private constructor, there are three viable choices:
* Compile-time dispatch
* Run-time dispatch where *all* constructors are possible targets
* Run-time dispatch where only *private* constructors are possible targets

The last one doesn't make any sense. The second one is super weird. It would actually make a lot of sense if we could generalize it as "when calling a ctor, run-time dispatch is used against all ctors that are *visible from where I'm calling*"; however that has virtually unbearable and unforeseen implementation consequences (yes, I can tell now that there will be consequences I cannot see now ^^).

After thinking a long time about this, I believe only the first time makes the least bit of sense, which gives:
* When calling a public or protected constructor, run-time dispatch is used against all public and protected constructors
* When calling a private constructor, compile-time dispatch is used

This means that all public and protected ctors live in the same "namespace", but each private constructor has its own bubble.

Now for exports, if we want to be a little bit consistent with non-ctor methods, I still believe that we should export all public and protected ctors or none. This is the only way we can give the same semantics to calling from JS or calling from another compilation unit in Scala.js, which is a property that is otherwise respected by the entire JS classes spec, and shared with facade types, so I think this is important.

Now but what if we call a private ctor from another compilation unit? That can happen for `private[pkg]` constructors. I would forbid this, or rather forbid the *declaration* of a `private[pkg]` ctor (`private[EnclosingClassOrObject]` is fine). This is also motivated by an implementation argument: with this restriction, from a different compilation unit (and hence under separate compilation), only public and protected constructors can be called, and hence only run-time dispatch is used, the same that JS would see -> can always emit a normal `JSNew`.

Summarizing the semantics:

* It is forbidden to declare a `private[pkg]` ctor, where `pkg` is a package
* When calling a public or protected constructor, run-time dispatch is used against all public and protected constructors
* When calling a private constructor, compile-time dispatch is used
* `@JSExport` exports all the public and private ctors. It is not possible to export a subset of those.

Implementation-wise, compile-time dispatch on private constructors is implemented with a magic flag. Note that the declaration *and* use of this flag is local to the compilation unit. We can also use a compilation-unit-local integer to identity the ctor to dispatch to.

Using a global variable is a nightmare to manipulate. Instead, I would use a normal parameter to the IR ctor. Or, to be precise, 2 params: one is a global object whose identity proves that you are allowed to call a private ctor (a `private[runtime] object PrivateCtorCall` will do), and the second is the integer identifier of the ctor to call. This implementation does not require any change to the IR, and hence no special knowledge from the linker, while still providing separate compilation :-)

**Comment by tannerezell** [comment] 2015-08-09 03:12
Will @ScalaJSDefined support monkey patching? I think that would be an excellent use case if it's feasible.

**Comment by sjrd** [comment] 2015-08-09 05:34
@tannerezll What do you mean exactly? Everything is in the above spec. 

In Scala.js we try to avoid monkey patching because we can use implicit classes instead, which are safer because they don't pollute the prototype on a global level.

**Comment by chandu0101** [comment] 2015-08-17 05:58
@sjrd 

I am getting linkage errors  when i add a new parm(callback) to a method(first jsSetState and setState)

```scala

@JSName("React.Component")
class ReactJSComponent[P, S] extends js.Object {

  @JSName("setState") 
  def jsSetState(newState: JSState[S],callback : UndefOr[() => _] = js.undefined): Unit = js.native

  @JSName("setState") 
  def jsSetState(func: js.Function2[JSState[S], JSProps[P], JSState[S]]): Unit = js.native

}

@ScalaJSDefined
abstract class ReactComponent[P, S] extends ReactJSComponent[P, S] {

  @JSName("sSetState")
  @inline
  def setState(newState: S,callback : UndefOr[() => _] = js.undefined): Unit = {
    jsSetState(JSState(newState),callback)
  }

  @JSName("sSetStateFunc")
  @inline
  def setState(func: js.Function2[S, P, S]): Unit = {
    jsSetState((s: JSState[S], p: JSProps[P]) => JSState[S](func(s.sstate, p.sprops)))
  }
}

```

Error : 

```
[error] Referring to non-existent method O.setState$default$2__Lchandu0101_scalajs_ReactComponent__sjs_js_UndefOr
[error]   called from Lchandu0101_scalajs_ReactComponent.sSetState
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   Lchandu0101_scalajs_ReactComponent
//repeat above infinite times
```

If i remove second param (callaback ) from 

```scala
def jsSetState(newState: JSState[S],callback : UndefOr[() => _] = js.undefined): Unit = js.native
def setState(newState: S,callback : UndefOr[() => _] = js.undefined): Unit 
         ||
def jsSetState(newState: JSState[S]): Unit = js.native
def setState(newState: S): Unit 
```

code compiles fine.

i tried to reproduce same in simple example , but no luck :(

**Comment by sjrd** [comment] 2015-08-17 06:27
Thanks for the report. Looks like an issue with default parameters.

**Comment by sjrd** [comment] 2015-08-17 09:44
@chandu0101 Should be fixed in the latest branch.

**Comment by chandu0101** [comment] 2015-08-17 10:06
working perfect , thank you :)

**Comment by japgolly** [comment] 2015-08-22 10:18
What's the story going to be with Scala.JS-generated ES6 classes and browser compatibility? Is the plan to just spit out ES6 JS and then we run it through a ES5 transpiler if we want broad browser compatibility?

**Comment by sjrd** [comment] 2015-08-22 10:47
Depends on your `scalaJSOuputMode`. By default it's `ECMAScript51Isolated`, so we generate compliant ECMAScript 5.1 code, even for Scala.js-defined JS classes. They have the same "shape" and almost the same semantics as ES 6 classes, in that case. (semantics difference are only apparent if you "break the type system" from JS code - ES 5 "classes" are a bit more permissive than ES 6 classes)

**Comment by japgolly** [comment] 2015-08-22 23:57
@sjrd That's super cool. Thanks.

**Closed** 2015-08-24 05:51 UTC
Labels: enhancement
