### ISSUE TITLE
Linking error for `Future.never` from Scala 2.13

### ISSUE THREAD

**Issue by ghik** [scala-js/scala-js#3818] opened 2019-10-24 11:10 UTC
`Future.never` doesn't work in ScalaJS because its implementation of `ready` method uses `java.util.concurrent.CountDownLatch` which is understandably not implemented for ScalaJS.
Note that the linking error happens even though `ready` method is not used. This is because in Scala 2.13 the `CountDownLatch` is instantiated in the constructor of `object never`: https://github.com/scala/scala/blob/2.13.x/src/library/scala/concurrent/Future.scala#L569

See https://travis-ci.org/UdashFramework/udash-core/jobs/602260811#L619

**Comment by ghik** [comment] 2019-10-25 08:41
https://github.com/scala/scala/pull/8502

**Comment by gzm0** [comment] 2019-10-25 09:35
Thank you for reporting and cross referencing.

**Comment by gzm0** [comment] 2020-03-06 09:18
This seems to be fixed upstream and targeted for 2.13.2.

**Comment by sjrd** [comment] 2020-03-06 09:55
That's true, but that means it will only be fixed in Scala.js once we use 2.13.2 to build our scalajs-library.jar. So fixing this will be a free by-product of internally upgrading to 2.13.2, but in the meantime I think we should leave this issue open.

WDYT?

**Comment by gzm0** [comment] 2020-03-06 10:15
Maybe. On one hand, the tracker is for us to have a list of things to do. On the other hand, it tracks defects and when they will be fixed.

For an issue that is clearly related to a version, this is easy:
- Add it to the milestone
- Fix it, once the code is in.

It is clear to everyone, that the fix will only be present in the version the issue is assigned to.

For things like this, it is less clear :S So either is fine with me, I guess.

**Comment by sjrd** [comment] 2020-03-06 10:19
Well there *will* be a version of Scala.js where this gets fixed. And there will even be a specific commit in Scala.js that fixes it.

**Comment by gzm0** [comment] 2020-03-06 10:30
Fair enough. It's just a bit unsettling that we have unactionable things in the tracker.

**Comment by sjrd** [comment] 2020-04-30 17:51
Fixed in e4aecce9f4690d2d4e0a8a12ed083969f3ecf6e9.

**Closed by sjrd** 2020-04-30 17:51 UTC
Labels: upstream
