### ISSUE TITLE
ScalaMeter Framework does not exist.

### ISSUE THREAD

**Issue by Josef-Vonasek** [scala-js/scala-js#3864] opened 2019-11-19 14:40 UTC
If I run `sbt project/test projectJs/test` on empty project I get the following error:

```
org.scalajs.testcommon.RPCCore$RPCException: scala.scalajs.js.JavaScriptException: TypeError: Access to host class org.scalameter.ScalaMeterFramework is not allowed or does not exist.
```

My build.sbt looks like this:
```scala
lazy val all = (project in file("."))
  .settings(version := "0.1")
  .aggregate(
    projectjvm,
    project.js
  )

lazy val project = crossProject(JVMPlatform, JSPlatform)
  .withoutSuffixFor(JVMPlatform)
  .crossType(CrossType.Pure)
  .in(file("project"))
  .jvmSettings(
    libraryDependencies += "com.storm-enroute" %% "scalameter" % "0.17" % "bench",
    testFrameworks := List(
      new TestFramework("org.scalameter.ScalaMeterFramework")
    ),
    bench := (test in Benchmark).tag(Exclusive).value,
  )
  .jsSettings(
    scalaJSUseMainModuleInitializer := true,
    testFrameworks := Nil
  )
  .enablePlugins(ScalaJSPlugin)
```

In other words, although `ScalaMeterFramework` should be only JVM specific, it still causes an error in the JS version of project.

**Comment by gzm0** [comment] 2019-11-19 15:22
You need to remove the `.enablePlugins(ScalaJSPlugin)` line. `crossProject` does this automatically. Like this both projects are Scala.js projects.

**Comment by gzm0** [comment] 2019-11-19 15:23
Duplicate of #3673 / #3861.

**Closed by gzm0** 2019-11-19 15:22 UTC

**Comment by sjrd** [comment] 2019-11-19 15:43
Also @Josef-Vonasek please take a while longer before concluding something is a bug, and ask [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js) before submitting GitHub issues. The GitHub Issues in this repo are for bug reports and feature requests only.

Thank you for your understanding.

**Comment by Josef-Vonasek** [comment] 2019-11-19 15:51
It seemed like a bug at first... And I gave up on asking specific questions on gitter, because usually nobody answers (when the questions is about any non-widely used library).

I highly appreciate your timely response!
