### ISSUE TITLE
Attempting to allocate an empty ByteBuffer throws jsException

### ISSUE THREAD

**Issue by easel** [scala-js/scala-js#2558] opened 2016-08-13 22:57 UTC
This code works under jvm and fails on scala.js:
```
ByteBuffer.allocateDirect(0)
```

Such a thing is pretty useless, but is currently being requested by RosHTTP for some reason or another.

**Comment by easel** [comment] 2016-08-13 23:24
For a moment I thought this was environment specific, since in chrome at least new IntArray8(0) succeeds, but the command is failing in the scala.js test suite as well.

**Comment by easel** [comment] 2016-08-13 23:33
Ok, so it turns out this is Rhino specific. Running the tests in node passes ok. Interestingly, running 'new Int8Array(0)' on the rhino shell in Rhino 1.7.6 works ok.

**Comment by easel** [comment] 2016-08-13 23:43
Ok so I swapped in the latest mozilla rhino, and it still fails. Also added a test to allocate a non-empty Int8Array, which also fails. Interestingly, the shell output from the command in node/chrome is different than in rhino, so at this point I'm thinking this has something to do with the rhino Int8Array() implementation in general.

Chrome:
```
new Int8Array(0)
[]
```

Rhino:
```
js> new Int8Array(0)
[object Int8Array]
```

At this point, I have a workaround for my local problem so I'll wait to pursue this further until I hear from somebody that knows more than I that it's worth doing so.

**Comment by easel** [comment] 2016-08-13 23:45
For reference, my tests and changes are at https://github.com/scala-js/scala-js/compare/master...easel:issue2558.

**Comment by sjrd** [comment] 2016-08-17 14:49
Rhino is not supposed to support typed arrays, and we do not make any attempt to make direct buffers work when typed arrays are not completely supported. So if this only fails on Rhino, it is not a bug of Scala.js.

**Comment by easel** [comment] 2016-08-17 16:48
Hmm. Interesting. They seem to support them in some capacity or another -- https://mozilla.github.io/rhino/javadoc/org/mozilla/javascript/typedarrays/NativeInt8Array.html for instance. 

 It's really too bad we don't have a truly usable JS implementation built-in to the JVM =/

**Comment by sjrd** [comment] 2016-08-18 11:18
"in some capacity or another" basically means they don't support it.

I'm going to close this, since we do not intend to work around Rhino bugs/shortcomings in our library implementation.

**Closed by sjrd** 2016-08-18 11:18 UTC
