### ISSUE TITLE
StackOverflow in Fast/FullOptJS due to aggressive use of @inline

### ISSUE THREAD

**Issue by robby-phd** [scala-js/scala-js#1766] opened 2015-06-26 00:13 UTC
When I aggressively use @inline on some non-trivial methods, Fast/FullOptJS gave me a NullPointerException (below is an example stack trace for FastOptJS). Interestingly, Fast/FullOptJS tried to run twice when this happens.

It works again after removing some @inline. 

```
[debug] Linker: Read info: 8148 us
[debug] Linker: Compute reachability: 53165 us
[debug] Linker: Assemble LinkedClasses: 344460 us
[debug] Linker: cache stats: reused: 3471 -- invalidated: 0 -- trees read: 0
[debug] Linker: 408896 us
[debug] Inc. optimizer: Batch mode: false
[debug] Inc. optimizer: Incremental part: 33562 us
[debug] Inc. optimizer: Optimizing 0 methods.
[debug] Inc. optimizer: Optimizer part: 159 us
java.lang.NullPointerException
	at org.scalajs.core.tools.optimizer.LinkedClass$$anonfun$2.apply(LinkedClass.scala:69)
	at org.scalajs.core.tools.optimizer.LinkedClass$$anonfun$2.apply(LinkedClass.scala:69)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.scalajs.core.tools.optimizer.LinkedClass.toInfo(LinkedClass.scala:69)
	at org.scalajs.core.tools.optimizer.LinkingUnit$$anonfun$2.apply(LinkingUnit.scala:25)
	at org.scalajs.core.tools.optimizer.LinkingUnit$$anonfun$2.apply(LinkingUnit.scala:25)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.scalajs.core.tools.optimizer.LinkingUnit.updated(LinkingUnit.scala:25)
	at org.scalajs.core.tools.optimizer.GenIncOptimizer$$anonfun$update$2.apply(GenIncOptimizer.scala:117)
	at org.scalajs.core.tools.optimizer.GenIncOptimizer$$anonfun$update$2.apply(GenIncOptimizer.scala:92)
	at org.scalajs.core.tools.optimizer.GenIncOptimizer.withLogger(GenIncOptimizer.scala:84)
	at org.scalajs.core.tools.optimizer.GenIncOptimizer.update(GenIncOptimizer.scala:92)
	at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$2.apply(ScalaJSOptimizer.scala:167)
	at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$2.apply(ScalaJSOptimizer.scala:167)
	at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
	at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:166)
	at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:112)
	at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$optimizeCP$1.apply$mcV$sp(ScalaJSOptimizer.scala:74)
	at org.scalajs.core.tools.io.CacheUtils$.cached(CacheUtils.scala:41)
	at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeCP(ScalaJSOptimizer.scala:72)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$13.apply(ScalaJSPluginInternal.scala:170)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$13.apply(ScalaJSPluginInternal.scala:154)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sjrd** [comment] 2015-06-26 03:18
Do you have a (minimized) reproduction? It's going to be very difficult to debug without one.

**Comment by robby-phd** [comment] 2015-06-26 14:33
I shared a bitbucket repo with you containing the somewhat minimized codebase to reproduce this issue.

**Comment by sjrd** [comment] 2015-06-26 14:34
Thanks. I will have a look at it on Tuesday. I will be abroad until then.

**Comment by robby-phd** [comment] 2015-06-26 14:43
No problem. It's not a high priority as I stumbled upon it unintentionally due to copy and paste some method definition with @inline.

**Comment by sjrd** [comment] 2015-06-26 14:47
To me it's a quite high priority. Anything that crashes the compiler or the optimizer for valid code is a blocker.

**Comment by robby-phd** [comment] 2015-06-26 14:53
Sure. I meant to say that it's not a high priority for *me* to have it fixed soon as removing some @inline would workaround the issue.

**Comment by sjrd** [comment] 2015-07-01 13:01
So the NPE is actually a consequence of #1781. The original issue is a `StackOverflowError`.

**Comment by sjrd** [comment] 2015-07-01 15:44
It seems `print(e: Exp)` is the main culprit. Just removing `@inline` from that one "fixes" the issue.
Now, I see that you're really (ab)using `@inline` here. It might even *detrimental* to the performance of your code. Functions that are too long will not be optimized by the underlying JS VM.

`@inline` should be used with parsimony, when the return-on-investment of inlining the method is worth it, for example in terms of better knowledge at call site which enables more optimizations. Here, you're just inlining many big methods within each other, with no return-on-investment. This is just bad even for performance, at the end of the day.

I suspect the StackOverflow is just a consequence of how much work the optimizer has to do in a single method, period. It may be an actual bug like an infinite loop of inlining that is not detected (and prevented), but at this point I doubt it, given that cutting at one strategic point fixes the problem. So I'll remove this from the 0.6.4 milestone.

**Comment by robby-phd** [comment] 2015-07-01 16:19
I understand the good/bad implications of using code inlining; I mentioned the @inline was unintentional due to copy-and-paste method header but then I stumbled upon this compiler crash. So I thought I would file a bug report because, as you mentioned (which I agree), a compiler should not crash for valid inputs regardless of "hints" for the compiler (i.e., similar to the scala compiler that ignores @inline in certain situations and can give warnings when it give up inlining).

**Comment by sjrd** [comment] 2016-01-30 20:37
Further investigation showed that this really was exponentially blowing up the stack used by the optimizer, due to an exponential number of inlining. So it's not *infinite*, but just so big that it's virtually infinite.

Preemptively detecting this is impossible given the architecture of the optimizer, so I'm afraid I have to close this as Won't Fix.

**Closed by sjrd** 2016-01-30 20:37 UTC
Labels: bug, wontfix
