### ISSUE TITLE
scalaJSUseMainModuleInitializer not taken into account with it:test

### ISSUE THREAD

**Issue by ebruchez** [scala-js/scala-js#3091] opened 2017-08-11 17:00 UTC
I have both:

```scala
scalaJSUseMainModuleInitializer in Test            := false,
scalaJSUseMainModuleInitializer in IntegrationTest := false
```

While the first one works, when I run `it:test`, my `JSApp` runs. Looking at `ScalaJSPluginInternal.scala` I am not sure why this would be the case.

Using Scala.js 0.6.19.

**Comment by sjrd** [comment] 2017-08-11 17:59
What setup do you have to configure `it` with Scala.js to begin with? By default, sbt-scalajs does not configure the `it` configuration at all.

**Comment by ebruchez** [comment] 2017-08-11 18:15
Same thing as for the other bug, it's the setup documented at https://www.scala-js.org/doc/project/testing.html.

**Comment by sjrd** [comment] 2017-08-16 14:11
This is surprising. Could you provide a reproduction repo? You could also diagnose what's going wrong with

    > inspect tree it:fastOptJS

to see whether it uses the value of `scalaJSUseMainModuleInitializer in IntegrationTest` or not (it should).

**Comment by sjrd** [comment] 2017-08-19 15:54
Closing as "can't reproduce" for now. Feel free to reopen with a reproduction.

**Closed by sjrd** 2017-08-19 15:54 UTC
Labels: can't reproduce
