### ISSUE TITLE
numerous Boxed and memory errors

### ISSUE THREAD

**Issue by antonkulaga** [scala-js/scala-js#1565] opened 2015-03-24 10:30 UTC
After switching to 0.6.x (in all 0.6.0 -0.6.2) I started to get numerous memory related errors in different project although I already increased sbt xmx to 3G 
Depending on the project I get either Boxed Error or Not enough space or GC error.
A good example of such erorr is https://github.com/w3c/banana-rdf/issues/250

**Comment by sjrd** [comment] 2015-03-24 10:33
Duplicate of #1525?

**Comment by antonkulaga** [comment] 2015-03-24 10:42
This errors occured even though I had dependencyOverrides += "org.scala-js" %% "scalajs-sbt-test-adapter" % "0.6.0"

**Comment by gzm0** [comment] 2015-04-14 19:50
@antonkulaga can we close this? Do you still see these issues?

**Closed** 2015-04-25 08:05 UTC
Labels: duplicate

**Comment by antonkulaga** [comment] 2015-04-25 10:29
I do have those issues but I would prefer to wait for 0.6.3 to see if they will dissapear
