### ISSUE TITLE
Pseudo-Union Types do not work with FunctionN[...,R]'s

### ISSUE THREAD

**Issue by ryan-richt** [scala-js/scala-js#2389] opened 2016-05-12 19:43 UTC
Awesome Scala.js Developers,

I would expect the following to compile (I could be off-base here):

```scala
implicitly[Evidence[Function1[Int, Int], Function1[Int, Int | Double]]]
```
So that for instance, the following would compile:

```scala
    import scala.scalajs.js.|._
    type DoubleOrString = Double | String
    val foo: Function1[Int, DoubleOrString] = (x: Int) => 4.2 // doesnt compile
```

I noticed this in trying to use a facade type for a poorly typed JS library where many of their methods accept union types even if not all subtypes are valid (such as for a Rectangle width). So in my facade wrapper, I only want to take a `FunctionN[..., Double]` instead of a `FunctionN[...,Double | Int | String]`

Thank you!

**Comment by sjrd** [comment] 2016-05-13 02:09
Unfortunately, there is a reason we call it a *pseudo* union type. This use case is not and cannot be supported.

So I'll close this at won't fix.

**Closed by sjrd** 2016-05-13 02:09 UTC

**Comment by gzm0** [comment] 2016-05-13 07:36
Maybe some background: The problem is that we cannot create a new subtyping relationship in Scala. So instead we provide implicit conversions.

However, the compiler doesn't (and cannot) know how to apply implicit conversions for generics. A value with the type parameter's might not even ever exist at runtime.

What you can do is the following:

```scala

def theirFacade(x: js.Function1[Int, Int | Double]) = ???

def myFacade(f: js.Function[Int, Int]) = {
  theirFacade((x: Int) => f(x): Int | Double)
}
```
