### ISSUE TITLE
NullPointerException on 0.6.6

### ISSUE THREAD

**Issue by Enalmada** [scala-js/scala-js#2219] opened 2016-02-02 08:42 UTC
When I update repo https://github.com/ochrons/scalajs-spa-tutorial to 0.6.6, I get this error running "activator clean test".  Strangely enough "activator test" seems to work after that.  It does not happen on 0.6.5 so I am hoping the stack trace helps identify what might be going on.

```
java.lang.NullPointerException
        at org.scalajs.core.tools.linker.LinkedClass$$anonfun$2.apply(LinkedClass.scala:69)
        at org.scalajs.core.tools.linker.LinkedClass$$anonfun$2.apply(LinkedClass.scala:69)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.scalajs.core.tools.linker.LinkedClass.toInfo(LinkedClass.scala:69)
        at org.scalajs.core.tools.linker.LinkingUnit$$anonfun$2.apply(LinkingUnit.scala:31)
        at org.scalajs.core.tools.linker.LinkingUnit$$anonfun$2.apply(LinkingUnit.scala:31)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.scalajs.core.tools.linker.LinkingUnit.updated(LinkingUnit.scala:31)
        at org.scalajs.core.tools.linker.frontend.optimizer.GenIncOptimizer$$anonfun$update$2.apply(GenIncOptimizer.scala:137)
        at org.scalajs.core.tools.linker.frontend.optimizer.GenIncOptimizer$$anonfun$update$2.apply(GenIncOptimizer.scala:107)
        at org.scalajs.core.tools.linker.frontend.optimizer.GenIncOptimizer.withLogger(GenIncOptimizer.scala:99)
        at org.scalajs.core.tools.linker.frontend.optimizer.GenIncOptimizer.update(GenIncOptimizer.scala:107)
        at org.scalajs.core.tools.linker.frontend.LinkerFrontend$$anonfun$5.apply(LinkerFrontend.scala:71)
        at org.scalajs.core.tools.linker.frontend.LinkerFrontend$$anonfun$5.apply(LinkerFrontend.scala:71)
        at org.scalajs.core.tools.logging.Logger$class.time(Logger.scala:28)
        at org.scalajs.sbtplugin.Implicits$SbtLoggerWrapper.time(Implicits.scala:9)
        at org.scalajs.core.tools.linker.frontend.LinkerFrontend.org$scalajs$core$tools$linker$frontend$LinkerFrontend$$optimize(LinkerFrontend.scala:70)
        at org.scalajs.core.tools.linker.frontend.LinkerFrontend$$anonfun$link$2.apply(LinkerFrontend.scala:60)
        at org.scalajs.core.tools.linker.frontend.LinkerFrontend$$anonfun$link$2.apply(LinkerFrontend.scala:58)
        at scala.Option.fold(Option.scala:157)
        at org.scalajs.core.tools.linker.frontend.LinkerFrontend.link(LinkerFrontend.scala:58)
        at org.scalajs.core.tools.linker.Linker$$anonfun$linkUnit$1.apply(Linker.scala:40)
        at org.scalajs.core.tools.linker.Linker$$anonfun$linkUnit$1.apply(Linker.scala:40)
        at org.scalajs.core.tools.linker.Linker.guard(Linker.scala:58)
        at org.scalajs.core.tools.linker.Linker.linkUnit(Linker.scala:40)
        at org.scalajs.core.tools.linker.ClearableLinker$$anonfun$linkUnit$1.apply(ClearableLinker.scala:46)
        at org.scalajs.core.tools.linker.ClearableLinker$$anonfun$linkUnit$1.apply(ClearableLinker.scala:46)
        at org.scalajs.core.tools.linker.ClearableLinker.linkerOp(ClearableLinker.scala:62)
        at org.scalajs.core.tools.linker.ClearableLinker.linkUnit(ClearableLinker.scala:46)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$46$$anonfun$apply$30.apply(ScalaJSPluginInternal.scala:557)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$46$$anonfun$apply$30.apply(ScalaJSPluginInternal.scala:554)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (client/test:loadedJSEnv) java.lang.NullPointerException
[error] Total time: 55 s, completed Feb 2, 2016 8:16:47 AM
```

**Comment by gzm0** [comment] 2016-02-02 08:47
Potentially a duplicate of ##2202, but needs investigation.

**Comment by sjrd** [comment] 2016-02-06 19:24
Yep, this is indeed a duplicate of #2202.
I can reproduce with 0.6.6 (and if I play enough I even get the same `AssertionError` as in #2202) and not with `master`.

**Closed by sjrd** 2016-02-06 19:24 UTC
