### ISSUE TITLE
crossProject's shared/ subfolder does not follow scala-2.11/scala-2.10 cross-building convention

### ISSUE THREAD

**Issue by lihaoyi** [scala-js/scala-js#2188] opened 2016-01-20 08:02 UTC
Files in a `crossProject`'s `myproj/shared/src/main/scala-2.11/` do not get picked up for compilation by SBT, but files in `myproj/jvm/src/main/scala-2.11/` or `myproj/shared/src/main/scala/` do. 

Presumably there's no reason why `myproj/shared/src/main/scala-2.11/` should be left out and it should get picked up just like the others.

Repro:
```scala
haoyi-mbp:scala-js-example-app haoyi$ tree
.
├── build.sbt
├── myproj
│   └── shared
│       └── src
│           └── main
│               └── scala-2.11
│                   └── myproj
│                       └── ScalaJSExample.scala
└── project
    ├── build.properties
    └── build.sbt

7 directories, 4 files


haoyi-mbp:scala-js-example-app haoyi$ cat build.sbt
// Turn this project into a Scala.js project by importing these settings
val myproj = crossProject.in(file("myproj"))
val js = myproj.js
val jvm = myproj.jvm


haoyi-mbp:scala-js-example-app haoyi$ cat project/build.properties
sbt.version=0.13.9


haoyi-mbp:scala-js-example-app haoyi$ cat project/build.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.5")
```

Trying to run it using `++2.11.4` has it fail to pick up the source files in the `myproj/shared/src/main/scala-2.11/` folder :

```scala
haoyi-mbp:scala-js-example-app haoyi$ sbt ++2.11.4 myprojJVM/run
<snip>
java.lang.RuntimeException: No main class detected.
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last myprojJVM/compile:run for the full output.
[error] (myprojJVM/compile:run) No main class detected.
[error] Total time: 0 s, completed Jan 19, 2016 11:54:00 PM
```

But when I move them into `myproj/jvm/src/main/scala-2.11/`, they get picked up correctly

```scala
haoyi-mbp:scala-js-example-app haoyi$ rm -rf myproj/jvm/


haoyi-mbp:scala-js-example-app haoyi$ mv myproj/shared myproj/jvm


haoyi-mbp:scala-js-example-app haoyi$ sbt ++2.11.4 myprojJVM/run
<snip>
[info] Compiling 1 Scala source to /Users/haoyi/Dropbox (Personal)/Workspace/scala-js-example-app/myproj/jvm/target/scala-2.11/classes...
[info] Running example.ScalaJSExample
Hello! 3.0
[success] Total time: 2 s, completed Jan 19, 2016 11:54:35 PM
```

And similarly, if I move it into `myproj/shared/src/main/scala/`, it gets picked up correctly:
```scala
haoyi-mbp:scala-js-example-app haoyi$ rm -rf myproj/shared/


haoyi-mbp:scala-js-example-app haoyi$ mv myproj/jvm myproj/shared


haoyi-mbp:scala-js-example-app haoyi$ mv myproj/shared/src/main/scala-2.11/ myproj/shared/src/main/scala


haoyi-mbp:scala-js-example-app haoyi$ sbt ++2.11.4 myprojJVM/run
<snip>
[info] Compiling 1 Scala source to /Users/haoyi/Dropbox (Personal)/Workspace/scala-js-example-app/myproj/jvm/target/scala-2.11/classes...
[info] Running example.ScalaJSExample
Hello! 3.0
[success] Total time: 3 s, completed Jan 19, 2016 11:59:46 PM
````

**Comment by sjrd** [comment] 2016-01-20 08:31
Duplicate of #2005.

**Closed by sjrd** 2016-01-20 08:31 UTC

**Comment by lihaoyi** [comment] 2016-01-20 08:40
Ah didn't find that, sorry
