### ISSUE TITLE
Scala Stubs is missing scala.scalajs.js package object

### ISSUE THREAD

**Issue by cipacda** [scala-js/scala-js#2564] opened 2016-08-23 09:50 UTC
Using js.native, js. Any, js. Object etc. is not implemented in scalajs-stubs which affects defining defining a trait that implements js.Any in a shared folder forcing code duplication.

**Comment by gzm0** [comment] 2016-08-23 09:51
Hum... How is it reasonable to define a trait that implements `js.Any` in a shared folder? Such a trait will have JS calling conventions (e.g. runtime overloading dispatch), which is not (and IMO should not) be implemented on the JVM.

Could you give us more info about your use case?

**Comment by cipacda** [comment] 2016-08-23 10:04
It would be very useful to have only one definition of the models used in the requests to the API as these are used both in Scala.JS and in JVM. 

If we are not allowed to used js.native in a shared folder, then these have to be defined twice, which is not ideal.

On the other hand I also understand your worry, but if it's only a stub it should not have any of the JS calling conventions, it will practically be ignored, right?

**Comment by gzm0** [comment] 2016-08-23 11:13
> On the other hand I also understand your worry, but if it's only a stub it should not have any of the JS calling conventions, it will practically be ignored, right?

No, unfortunately not. A type extending `js.Any` having JS calling conventions is one of the fundamental cornerstones in Scala.js interoperability design (if you are interested, have a look at the talks about [internals][1]).

The problem is that the Scala.js compiler uses subtyping to check how to call a method. For example:

```scala
trait FooJVM {
  def foo(x: Int)
}

trait FooJS {
  def foo(x: Int) 
}

def useFooJVM(foo: FooJVM): Int = foo.foo(1)
def useFooJS(foo: FooJS): Int = foo.foo(1)
```

Although the two definitions of the `useFoo` variants look very different, they will compile to very different code (simplified):

```javascript
function useFooJVM(foo) {
  return foo.foo__I__I(1);
}

function useFooJS(foo) {
  return foo.foo(1);
}
```

As you can see, the method names are not the same. This is because of the calling convention distinction. If we would allow Scala style classes to extend JS types, that call would lead to an error at runtime, since the method is not defined.

If you want to augment your Scala types with JS calling conventions however, you can do that:

```scala
// Shared.
trait Foo {
  @JSExport // The export will propagate to subtypes implementing this.
  def foo(x: Int): Int
}

// In JS land only.
trait FooJS {
  def foo(x: Int): Int
}

// In some method
def jsMethodUsingFoo(x: FooJS): Int = js.native

def useFoo(x: Foo): Int = jsMethodUsingFoo(js.use(x).as[FooJS])
```

[1]: http://www.scala-js.org/community/presentations.html

**Comment by sjrd** [comment] 2016-08-23 11:29
I added two `extends js.Object` that were missing in @gzm0's code snippets.

**Comment by gzm0** [comment] 2016-08-23 11:31
I'm actually wondering if that pattern above is sufficiently common so that we should add support for it... Seems not doable without macro-paradise in user space :S

OTOH it would be doable as another, independent compiler plugin :-/

**Comment by sjrd** [comment] 2016-08-23 11:33
@gzm0 I think what @cipacda wants is to have a stupid simple stub like this:
```scala
package scala.scalajs.js

trait Any
class Object extends Any
```
Which I assume he would use to define shared model data types such as
```scala
class Foo(val x: Int) extends js.Object
```
On the JVM, that would just be a normal JVM-style class, which happens to extend a no-op class (`js.Object`).

It is easy to think there is no harm in doing something like that. But then the semantics of the same code would be different on JVM than on JS, and I really do not like that.

**Comment by gzm0** [comment] 2016-08-23 11:35
Yes, I understand that and I absolutely agree that we should not do this. But I can see how there is value in having a simple way to express the following: "I want a simple Scala trait I can use on the server and client. I also want to pass that trait to JS methods".

My snippet emulates exactly that but contains a lot of boilerplate...

**Comment by cipacda** [comment] 2016-08-23 11:41
I agree that this will not be ideal to have different semantics on JVM than on JS, but would really be great to be able to use simple traits on both the server and the client, this being one of the main reasons we chose to use Scala.js and to avoid boilerplate. 

The snippet you have provided would work, but is not ideal as will add a lot of duplicate (ish) code when a project grows.

**Comment by sjrd** [comment] 2016-08-23 11:44
> I agree that this will not be ideal to have different semantics on JVM than on JS

It would be worse than not ideal. The reason you are able to write cross-compiling code to begin with, is that Scala.js preserves the semantics of Scala/JVM to a very high degree. Most compile-to-JS languages do not have that property.

Every compromise on that property *weakens* the ability to cross-compile code, instead of improving it.

**Comment by gzm0** [comment] 2016-08-23 14:13
What I do not understand is why you need a trait that extends `js.Any`. If you just want to have the same objects on both ends, make them normal (non-Scala.js) classes and you are done.

Please let us know more about your use case.

**Comment by cipacda** [comment] 2016-08-23 14:52
Because I need to cast from a Javascript object I get when completing a form (via Angular) to the Scala.js object and use that. That only work if I use a facade. 

I had them as normal objects initially and had trouble casting them...

**Comment by gzm0** [comment] 2016-08-25 06:38
Related to: http://stackoverflow.com/questions/39095278/scala-js-with-angular-type-casting

**Comment by sjrd** [comment] 2016-08-26 13:56
I'm going to close this as as-designed.

I understand there can be use cases where one wants some data structure that is a facade on JS but still exists in some form on the JVM. However, I believe this should not be part of the core language nor tooling, as it definitely has semantic issues. In general, I would recommend to use a shared normal case class, and user-defined implicit conversions to/from a facade trait.

**Closed by sjrd** 2016-08-26 13:56 UTC
