### ISSUE TITLE
Intermittent IllegalStateException: Unknown opcode 5 while running tests

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3201] opened 2017-11-26 10:54 UTC
See #3175. The hanging part was solved in #3194, but there are still occasional errors with

    java.lang.IllegalStateException: Unknown opcode: 5

which seem to come from the JavaScript side, which means it corresponds to [`JSEndpoints.msgSlave`](https://github.com/scala-js/scala-js/blob/e9cc89c4fe483aa45d2d193c3a8d3772d1292a17/test-common/src/main/scala/org/scalajs/testcommon/JSEndpoints.scala#L15-L16), which is supposed to be attached [`here`](https://github.com/scala-js/scala-js/blob/e952f9ce520372600a00f5dc3b64062fd6bded2c/test-interface/src/main/scala/org/scalajs/testinterface/internal/Bridge.scala#L61).

**Comment by gzm0** [comment] 2017-11-26 12:16
Do we see these as well in our CI or does it just happen on PhantomJS?

**Comment by sjrd** [comment] 2017-11-26 12:18
I haven't seen them on our CI. But it could be that I missed them because we systematically try every command twice automatically...

**Comment by olafurpg** [comment] 2017-12-26 19:29
I'm seeing this error in the utest Travis CI after upgrading to M2 while tearing down a custom test framework https://travis-ci.org/lihaoyi/utest/jobs/321877307#L1604 I'm unable to reproduce the error locally running `SCALAJS_VERSION="1.0.0-M2" sbt "very test"`

**Comment by sjrd** [comment] 2017-12-26 19:46
The uTest job was restarted and succeeded on the second attempt. So it seems it's intermittent there as well. However, it definitely show that the problem can happen with Node.js, not just with PhantomJS.

**Comment by gzm0** [comment] 2017-12-27 09:30
I see. So this is most likely a race somewhere in the test adapter. I'll investigate.

**Comment by japgolly** [comment] 2018-06-26 02:00
FYI this is occurring with 0.6.23:

```
/home/travis/build/japgolly/clear-config/core/js/target/scala-2.12/core-test-fastopt.js:7864
        throw new $c_jl_IllegalStateException().init___T(("Unknown opcode: " + opCode))
        ^
Error
    at $c_jl_IllegalStateException.$c_jl_Throwable.fillInStackTrace__jl_Throwable (/home/travis/build/japgolly/clear-config/core/js/target/scala-2.12/core-test-fastopt.js:23682:14)
    at $c_jl_IllegalStateException.$c_jl_Throwable.init___T__jl_Throwable (/home/travis/build/japgolly/clear-config/core/js/target/scala-2.12/core-test-fastopt.js:23714:8)
    at $c_jl_IllegalStateException.init___T (/home/travis/build/japgolly/clear-config/core/js/target/scala-2.12/core-test-fastopt.js:45795:52)
    at $c_Lorg_scalajs_testinterface_internal_JSRPC$.$c_Lorg_scalajs_testcommon_RPCCore.handleMessage__T__V (/home/travis/build/japgolly/clear-config/core/js/target/scala-2.12/core-test-fastopt.js:7864:49)
    at /home/travis/build/japgolly/clear-config/core/js/target/scala-2.12/core-test-fastopt.js:20528:53
    at tryReadMsg ([stdin]:66:7)
    at Socket.onData ([stdin]:50:5)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

(Source: https://travis-ci.org/japgolly/clear-config/builds/396202547#L746)

**Comment by gzm0** [comment] 2018-06-26 14:36
Yes, sorry this is taking so long. I have tried to narrow this down a bunch of times, but haven't figured out the exact issue yet. My best guess is that something is happening "more async" than expected and as a result the endpoint (and hence the opcode) is already detached. However, I couldn't figure out an execution schedule in which this happens yet.

**Comment by japgolly** [comment] 2018-06-27 07:54
No worries at all! :)
This recent occurrence looks different than I remember so I thought it'd be
good to pass the info on. (Also there's values in confirming that's it's
still present on 0.6.23.)

**Comment by japgolly** [comment] 2018-09-01 06:40
Hi I know this isn't fixed yet. I experienced it again testing 0.6.25 and I wanted to leave more helpful diagnostic info than I had before.

The error occurs on line 78 of the following snippet:

```js
  var bytes = $makeNativeArrayWrapper($d_B.getArrayOf(), elems$2);
  var $in = new $c_Ljava_io_DataInputStream().init___Ljava_io_InputStream(new $c_Ljava_io_ByteArrayInputStream().init___AB(bytes));
  try {
    var opCode = $in.readByte__B();
    if (($m_Lorg_scalajs_testcommon_RPCCore$().org$scalajs$testcommon$RPCCore$$ReplyOK$1 === opCode)) {
      var this$19 = this.getPending$1__p1__Ljava_io_DataInputStream__s_Option($in);
      if ((!this$19.isEmpty__Z())) {
        var arg1 = this$19.get__O();
        var p = $as_Lorg_scalajs_testcommon_RPCCore$PendingCall(arg1);
        var this$22 = p.promise__s_concurrent_Promise();
        try {
          var s = p.serializer__Lorg_scalajs_testcommon_Serializer();
          var result = new $c_s_util_Success().init___O(s.deserialize__Ljava_io_DataInputStream__O($in))
        } catch (e) {
          var e$2 = $m_sjsr_package$().wrapJavaScriptException__O__jl_Throwable(e);
          if ((e$2 !== null)) {
            matchEnd8: {
              var result;
              var o11 = $m_s_util_control_NonFatal$().unapply__jl_Throwable__s_Option(e$2);
              if ((!o11.isEmpty__Z())) {
                var e$3 = $as_jl_Throwable(o11.get__O());
                var result = new $c_s_util_Failure().init___jl_Throwable(e$3);
                break matchEnd8
              };
              throw $m_sjsr_package$().unwrapJavaScriptException__jl_Throwable__O(e$2)
            }
          } else {
            var result;
            throw e
          }
        };
        $f_s_concurrent_Promise__complete__s_util_Try__s_concurrent_Promise(this$22, result)
      }
    } else if (($m_Lorg_scalajs_testcommon_RPCCore$().org$scalajs$testcommon$RPCCore$$ReplyErr$1 === opCode)) {
      var this$23 = this.getPending$1__p1__Ljava_io_DataInputStream__s_Option($in);
      if ((!this$23.isEmpty__Z())) {
        var arg1$1 = this$23.get__O();
        var p$3 = $as_Lorg_scalajs_testcommon_RPCCore$PendingCall(arg1$1);
        try {
          var s$1 = $m_Lorg_scalajs_testcommon_Serializer$ThrowableSerializer$();
          var x1$1 = new $c_s_util_Success().init___O(s$1.deserialize__Ljava_io_DataInputStream__jl_Throwable($in))
        } catch (e$1) {
          var e$2$1 = $m_sjsr_package$().wrapJavaScriptException__O__jl_Throwable(e$1);
          if ((e$2$1 !== null)) {
            matchEnd8$1: {
              var x1$1;
              var o11$1 = $m_s_util_control_NonFatal$().unapply__jl_Throwable__s_Option(e$2$1);
              if ((!o11$1.isEmpty__Z())) {
                var e$3$1 = $as_jl_Throwable(o11$1.get__O());
                var x1$1 = new $c_s_util_Failure().init___jl_Throwable(e$3$1);
                break matchEnd8$1
              };
              throw $m_sjsr_package$().unwrapJavaScriptException__jl_Throwable__O(e$2$1)
            }
          } else {
            var x1$1;
            throw e$1
          }
        };
        if ($is_s_util_Success(x1$1)) {
          var x2 = $as_s_util_Success(x1$1);
          var t$1 = $as_jl_Throwable(x2.value$2);
          var throwable = new $c_Lorg_scalajs_testcommon_RPCCore$RPCException().init___jl_Throwable(t$1)
        } else {
          if ((!$is_s_util_Failure(x1$1))) {
            throw new $c_s_MatchError().init___O(x1$1)
          };
          var x3 = $as_s_util_Failure(x1$1);
          var t$2 = x3.exception$2;
          var throwable = t$2
        };
        var this$26 = p$3.promise__s_concurrent_Promise();
        $f_s_concurrent_Promise__failure__jl_Throwable__s_concurrent_Promise(this$26, throwable)
      }
    } else {
      var x1$2 = $as_Lorg_scalajs_testcommon_RPCCore$BoundEndpoint(this.endpoints$1.get__O__O(opCode));
      if ((x1$2 === null)) {
        throw new $c_jl_IllegalStateException().init___T(("Unknown opcode: " + opCode))
      };
      if ($is_Lorg_scalajs_testcommon_RPCCore$BoundMsgEndpoint(x1$2)) {
        var x3$1 = $as_Lorg_scalajs_testcommon_RPCCore$BoundMsgEndpoint(x1$2);
        var ep = x3$1.endpoint$1;
        var jsx$2 = x3$1.exec$1;
        var s$2 = ep.msgSerializer$1;
        $asUnit(jsx$2.apply__O__O(s$2.deserialize__Ljava_io_DataInputStream__O($in)))
      } else {
        if ((!$is_Lorg_scalajs_testcommon_RPCCore$BoundRPCEndpoint(x1$2))) {
          throw new $c_s_MatchError().init___O(x1$2)
        };
        var x4 = $as_Lorg_scalajs_testcommon_RPCCore$BoundRPCEndpoint(x1$2);
        var t$3 = $in.readLong__J();
        var lo = t$3.lo$2;
        var hi = t$3.hi$2;
        var ep$2 = x4.endpoint$1;
        var jsx$4 = $m_Lorg_scalajs_testcommon_FutureUtil$();
        try {
          var s$3 = ep$2.reqSerializer$1;
          var jsx$3 = new $c_s_util_Success().init___O(s$3.deserialize__Ljava_io_DataInputStream__O($in))
        } catch (e$4) {
          var e$2$2 = $m_sjsr_package$().wrapJavaScriptException__O__jl_Throwable(e$4);
          if ((e$2$2 !== null)) {
            matchEnd8$2: {
              var jsx$3;
              var o11$2 = $m_s_util_control_NonFatal$().unapply__jl_Throwable__s_Option(e$2$2);
              if ((!o11$2.isEmpty__Z())) {
                var e$3$2 = $as_jl_Throwable(o11$2.get__O());
                var jsx$3 = new $c_s_util_Failure().init___jl_Throwable(e$3$2);
                break matchEnd8$2
              };
              throw $m_sjsr_package$().unwrapJavaScriptException__jl_Throwable__O(e$2$2)
            }
          } else {
            var jsx$3;
            throw e$4
          }
        };
        jsx$4.futureFromTry__s_util_Try__s_concurrent_Future(jsx$3).flatMap__F1__s_concurrent_ExecutionContext__s_concurrent_Future(x4.exec$1, this.ex$1).onComplete__F1__s_concurrent_ExecutionContext__V(new $c_sjsr_AnonFunction1().init___sjs_js_Function1((function(this$4$1, callID, ep$2$1) {
          return (function(repl$2) {
            var repl = $as_s_util_Try(repl$2);
            this$4$1.send__T__V(this$4$1.makeReply__p1__J__s_util_Try__Lorg_scalajs_testcommon_Serializer__T(callID, repl, ep$2$1.respSerializer$1))
          })
        })(this, new $c_sjsr_RuntimeLong().init___I__I(lo, hi), ep$2)), this.ex$1)
      }
    }
  } finally {
    $in.in$2.close__V()
  }
```

**Comment by sjrd** [comment] 2018-09-01 11:08
Yeah it's this line in the original code:
https://github.com/scala-js/scala-js/blob/991bda9d147ff7030dd4bb69cd30b3e62a73dad2/test-common/src/main/scala/org/scalajs/testcommon/RPCCore.scala#L79

We kind of knew that, because it's literally the only place in the entire codebase that throws an "Unknown opcode". ;)

**Comment by gzm0** [comment] 2018-09-02 09:10
I believe the problem is [this line][1]: Each time an executing task reports something back about a test (failure, success, etc.), the master will send back a message. However, this message is ignored on the slave. While ignoring the message is OK, not waiting for it (until the completion continuation is called) is not OK: The framework has no way of knowing how many messages are still pending and hence calls done on the slave, making it detach the message handler.

There are two ways to deal with this situation:
- Force testing frameworks to handle their messaging state (current state).
- Ignore unknown messages. I do not like this option as it is prone to letting bugs slip.

[1]: https://github.com/lihaoyi/utest/blob/4333545a41de28a5d209dc057c75ce857b75bb27/utest/shared/src/main/scala/utest/runner/MasterRunner.scala#L97

@sjrd WDYT? If you think that reasoning is OK, we should close this as as-designed and probably submit a fix to utest.

**Comment by gzm0** [comment] 2018-09-02 09:14
Note a third option is to keep the current state but improve ID accounting so that we can distinguish the following cases:

- A slave is not present anymore.
- A slave has never existed.
- An endpoint is currently not present.

Notes:
- This will force us to leak memory (retain all slave IDs that have ever existed).
- Endpoint accounting could be improved if we bind attachment to an execution ID or something.
- It seems this is kind of a lot just to improve errors.

**Comment by sjrd** [comment] 2018-09-02 10:41
Ah! Waw, that's some deep analysis! From what I understand, it seems like a very plausible explanation. It also explains why we wouldn't have noticed it ourselves, since it's uTest-specific.

I agree that

> Force testing frameworks to handle their messaging state (current state).

is the best course of action (hence closing as as-designed). Maybe we could improve the diagnostic experience by special-casing `JSEndPoints.msgSlave` (and maybe `msgMaster` as well) so that if they are not found, we throw an exception with a helping message, e.g.,

> Unknown opcode: 5. The test adapter could not send a message to a slave, which probably happens because the slave terminated early, without waiting for the reply to a call to `send()`. This is probably a bug in the testing framework you are using. See also https://github.com/scala-js/scala-js/issues/3201.

**Comment by japgolly** [comment] 2018-09-08 01:17
> we should close this as as-designed and probably submit a fix to utest.

That seems reasonable and providing a fix to utest would be much appreciated. I could review, many any additional changes, and merge it in on the utest side.

**Comment by sjrd** [comment] 2018-09-11 15:15
PR to uTest at https://github.com/lihaoyi/utest/pull/177

**Closed** 2018-10-16 19:32 UTC
Labels: bug, has-pr

**Comment by japgolly** [comment] 2018-10-17 08:55
:+1: :+1:
