### ISSUE TITLE
Tests are hanging if node crash.

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js#3288] opened 2018-02-24 10:36 UTC
I'll try to narrow it down during the next days, but givent this: https://travis-ci.org/akka-js/akka.js

Basically we have two issues (I guess):
 - we are probably produce code that crash node (any version)
 - tests hangs indefinitely when node has crashed

this happen also in my local machine with different node versions.

**Comment by gzm0** [comment] 2018-02-24 13:11
Duplicate of #3175? akka.js is still using 0.6.21 that suffers from this.

**Closed** 2018-02-26 09:12 UTC
Labels: duplicate

**Comment by andreaTP** [comment] 2018-02-26 11:05
updated to 0.6.22 and still happening (both crash and hang)
https://travis-ci.org/akka-js/akka.js/builds/346203746?utm_source=email&utm_medium=notification

**Comment by gzm0** [comment] 2018-02-26 15:30
Ah, that's indeed not a duplicate of #3175. The problem is that nothing catches this error:

```
java.lang.InstantiationError: JSDynamicAccess akka.serialization.JavaSerializer is not js instantiable class
  at $c_jl_InstantiationError.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/home/travis/build/akka-js/akka.js/akka-js-actor-tests/js/target/scala-2.11/akkaactortest-test-fastopt.js:53069:14)
  at $c_jl_InstantiationError.$c_jl_Throwable.init___T__jl_Throwable(/home/travis/build/akka-js/akka.js/akka-js-actor-tests/js/target/scala-2.11/akkaactortest-test-fastopt.js:53104:8)
  at java.lang.InstantiationError.<init>(/home/travis/build/akka-js/akka.js/akka-js-actor-tests/js/target/scala-2.11/akkaactortest-test-fastopt.js:122612:52)
  at $c_Lakka_actor_ReflectiveDynamicAccess.$c_Lakka_actor_JSDynamicAccess.getRuntimeClass__T__sjs_reflect_InstantiatableClass(/home/travis/build/akka-js/akka.js/akka-js-actor-tests/js/target/scala-2.11/akkaactortest-test-fastopt.js:39404:42)
  at akka.serialization.Serialization.serializerOf(/home/travis/build/akka-js/akka.js/akka-js-actor-tests/js/target/scala-2.11/akkaactortest-test-fastopt.js:43711:22)
  at {anonymous}()(/home/travis/build/akka-js/akka.js/akka-js-actor-tests/js/target/scala-2.11/akkaactortest-test-fastopt.js:43468:31)
  at scala.scalajs.runtime.AnonFunction1.apply(/home/travis/build/akka-js/akka.js/akka-js-actor-tests/js/target/scala-2.11/akkaactortest-test-fastopt.js:70310:23)
  at {anonymous}()(/home/travis/build/akka-js/akka.js/akka-js-actor-tests/js/target/scala-2.11/akkaactortest-test-fastopt.js:54492:83)
  at scala.scalajs.runtime.AnonFunction1.apply(/home/travis/build/akka-js/akka.js/akka-js-actor-tests/js/target/scala-2.11/akkaactortest-test-fastopt.js:70310:23)
  at scala.collection.immutable.Map$Map2.foreach(/home/travis/build/akka-js/akka.js/akka-js-actor-tests/js/target/scala-2.11/akkaactortest-test-fastopt.js:170356:5)
```

I assume this is because of some `ExecutionContext` that is not properly prepared to propagate errors to the testing framework. As a result, the test does not terminate (and the test runner hangs).

**Comment by andreaTP** [comment] 2018-03-02 15:24
it took me really a lot to answer sorry @gzm0 but:
> I assume this is because of some ExecutionContext that is not properly prepared to propagate errors to the testing framework. As a result, the test does not terminate (and the test runner hangs).

I'm using a custom `ExecutionContext` of course and I do not know how should I propagate the errors from it ... could you point me out to some documentation?

I'm still facing problems e.g. akka Testkit tests are executed but the report is with 0 tests executed in scala.js 0.6.21 and in 0.6.22, while it is correct in 0.6.20.

**Comment by gzm0** [comment] 2018-03-05 06:29
You can propagate errors like this:

```scala
implicit val ex = ExecutionContext.fromExecutor(ExecutionContext.global, t => handleError(t))
```

`handleError` is of course specific to your testing framework / application logic. Incidentally, the TestAdapter has an example of this [TestAdapter](https://github.com/scala-js/scala-js/blob/fbe0421aca6e1303912252c95b54ee3359b34a3d/test-adapter/src/main/scala/org/scalajs/sbttestadapter/TestAdapter.scala#L42).

Could you give me the outputs of:

```
sbt> show loadedTestFrameworks
sbt> show definedTests
```

and execution traces for the exact same codebase with 0.6.20, 0.6.21 and 0.6.22?

**Comment by andreaTP** [comment] 2018-03-05 10:44
This is indeed quite strange indeed, why the testing environment should be aware of this? I'm just overriding the `ExecutionContext` I'm not writing my own testing framework ...

I'll provide all the rest of traces next days! (and possibly a minimal repro)

**Comment by gzm0** [comment] 2018-03-06 10:47
The problem is the following:

```scala
def myMethod(x: Int)(implicit ex: ExecutionContext): Future[Int] = {
  val result = Promise[Int]()
 
  Future {
    doSomething(x)
    result.success(1)
  }

  result.future
}

def test() {
  val res = myMethod(-1) // will make doSomething() throw
  Await.result(res, Duration.Inf) // will block forever since the exception gets lost.
}
```

Note that this is a contrived example that would of course better be written as:

```scala
def myMethod(x: Int)(implicit ex: ExecutionContext): Future[Int] = {
  Future {
    doSomething(x)
    success(1)
  }
}
```

which does **not** suffer from the aforementioned problem (`Future.apply` contains an implicit `try { ... } catch { ... }` that propagates any exceptions. Therefore, `Await.result(...)` in the test would not block indefinitely, but throw the exception.
