### ISSUE TITLE
JsEnv timeouts start too early

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2226] opened 2016-02-03 11:31 UTC
My travis builds often fail because  PhantomJSEnv timeouts halfway through the tests. The fix for this was to change my `.travis.yml` from
```yml
script:
- sbt ++$TRAVIS_SCALA_VERSION test
```
to
```yml
script:
- sbt ++$TRAVIS_SCALA_VERSION test:fastOptJS
- sbt ++$TRAVIS_SCALA_VERSION test
```

This, coupled with the fact that I never get timeouts locally in long-running SBT sessions, implies that whatever timeout is in-place (*I know we've discussed this before but I never come away with a proper understanding - sorry*) begin when the batch of commands are issued. This should ideally be changed to begin when tests truly commence.

That being said, the workaround is trivial so if a fix isn't worth the effort, that's cool - feel free to close.

**Comment by sjrd** [comment] 2016-02-03 12:56
Oh that's ... interesting. The workaround is actually very informative. We should be able to fix this.

**Comment by gzm0** [comment] 2016-02-03 12:57
What is the error message you get when it times out?

**Comment by japgolly** [comment] 2016-02-03 13:21
It just says
```
org.scalajs.jsenv.ComJSEnv$ComClosedException: Phantom.js isn't connected
```

Here's a sample full log: https://travis-ci.org/japgolly/scalajs-react/builds/106686299

**Comment by nicolasstucki** [comment] 2016-02-08 15:01
Inspecting the log I can see that this is in fact not a time out. There are 2 possibilities: (i) the Jetty websocket was closed or (ii) the async VM run has finished. I do not have enough information to know which one it was and why it closed/finished. 

@japgolly, if this issue is reproducible could you retest it on travis with the debug output:
```yml
script:
- sbt debug ++$TRAVIS_SCALA_VERSION test
```

**Comment by japgolly** [comment] 2016-02-08 21:48
@nicolasstucki Sure, here you go: https://travis-ci.org/japgolly/scalajs-react/builds/107872634

I've also created a branch https://github.com/japgolly/scalajs-react/tree/tmp/timeout if you want to toy with the Travis config.

**Comment by nicolasstucki** [comment] 2016-02-10 11:02
I've tried almost every combination of configurations imaginable to try to reproduce this on my machine, but was not able. 

From the debug logs I was able to find that it is the jetty websocket connection that closes unexpectedly for no apparent reason. In that scenario, Phantom does not seem to have crashed, it is just a lost in the connection.

I do believe that it must be an issue with the version of Phantomjs that is used by travis, a custom build of  phantom 2.0.0. I would wait until travis supports 2.1.1 to see if this issue is maybe fixed by it. Meanwhile we should use the simple work around stated in the first comment.

**Comment by japgolly** [comment] 2016-02-10 21:02
> I've tried almost every combination of configurations imaginable to try to reproduce this on my machine, but was not able.

@nicolasstucki I feel your pain. :) When you tested on your machine, did you change the tests to make them take a long enough time? I mean, if you checked out that branch I linked and just run locally it will pass because *(←assumption)* our machines are much faster than Travis so it won't timeout.

*...off too the console and back...*

Ok I can reproduce it locally (with PhantomJS 2.1.1) by adding a long-running test:
```scala
package omg

import utest._

object OMG extends TestSuite {
  override def tests = TestSuite {'x{
    var i = 0
    for {
      _ <- 0 to 1000000
      _ <- 0 to 1000000
    } i += i
    i
  }}
}
```
then running
```
sbt debug clean test | tee debug.txt
```
the output of which is here: [debug.txt](https://github.com/scala-js/scala-js/files/125488/debug.txt)

**Comment by nicolasstucki** [comment] 2016-02-10 22:06
Well, I tried testing that same branch while overloading my CPU with juck processes. It executed 10 slover than in Travis but still did not get any problem. I will try the code that you just gave me, maybe it will finally fail and I'll be happy (because Ill have a way to find the issue).

**Comment by japgolly** [comment] 2016-02-10 22:29
It could also be an environmental issue. If there's any more info I could provide that would be helpful, please let me know.

**Comment by nicolasstucki** [comment] 2016-02-11 13:30
I've been able to reproduce the failure. There is a timeout of 5 minutes on a WebSocket that we open using Jetty. I will add an option to set a new larger timeout on a `PhanthomJSEnv`.

**Comment by gzm0** [comment] 2016-02-11 13:36
@nicolasstucki who does set the 5 minute timeout? I think in this case it might actually be justifiable to drop the timeout entirely or make it **very** large (hours, days).

Timeouts are usually a good thing in (long running) systems. But in this case there should be higher-level tools that catch these or you have a developer actually observing the build. So it seems that here, timeouts are more counter-productive.

**Comment by nicolasstucki** [comment] 2016-02-11 13:47
@gzm0 It is Jetty that sets it. It is a timeout on the time that the socket stays idle.
It is the only thing that will stop a tests with an infinite loop. As there has only been one case where this was an issue, I would argue that we should keep this limit for now and give to possibility of changing it.

**Comment by gzm0** [comment] 2016-02-11 13:59
> It is the only thing that will stop a tests with an infinite loop.

Tests with infinite loops are not to be stopped. They are to loop infinitely. (Do you know a test framework that has a timeout per default for synchronous tests? I don't.)

Also, this is at a lower level than the test framework itself. I am OK with adding a timeout option to the `ComJSRunner`, but then it has to be generalized, because it is not something which should be specific to a single `ComJSRunner`, but all of them should behave the same, which IMO is no timeout.

**Comment by sjrd** [comment] 2016-02-11 14:50
I think @gzm0 has a point, that other JS envs do not have any timeout. So Phantom should also have no timeout, period.

**Closed** 2016-02-13 18:59 UTC
Labels: bug

**Comment by japgolly** [comment] 2016-02-13 21:34
This fix is tiny but I know a lot of time went in to tracking it down. Thank you. :bow:
