### ISSUE TITLE
Fatal errors in tests cause freeze

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2305] opened 2016-03-22 10:04 UTC
Put this in a test and run it:
```scala
0.asInstanceOf[String]
```

The SBT `test` task never completes and there is no output.

**Comment by sjrd** [comment] 2016-03-22 10:27
It might be related to the testing framework. I cannot reproduce with JUnit nor with our internal Jasmine framework, neither on Rhino, Node.js nor PhantomJS.

**Comment by japgolly** [comment] 2016-03-22 10:41
Ew. Ok let me investigate further. Although it'll take a while as I'm going out of town tomorrow; I'll look into it in a week or two.

(FYI I can reproduce it with μtest 0.3 using Node.JS, Phantom.JS and Firefox.)

**Comment by lihaoyi** [comment] 2016-03-22 10:55
Quite possibly uTest is not doing the right thing in this case. If it's still happening in 0.4.3 (which includes a reasonably large rewrite of the internals) then it should be an easy fix

**Comment by japgolly** [comment] 2016-04-13 00:49
FWIW, just like `Try`, `Future` doesn't catch UBIs as `Failure` either because UBIs are fatal.
https://github.com/scala/scala/blob/2.11.x/src/library/scala/concurrent/impl/Future.scala#L24

I'd say most if not all Scala-based test frameworks will have this problem as most would wrap tests in `Try` or `Future` expecting sensible error catching.

**Comment by sjrd** [comment] 2016-07-14 20:07
Closing as invalid until there is some evidence that Scala.js core is to blame on this one.

**Closed by sjrd** 2016-07-14 20:07 UTC

**Comment by japgolly** [comment] 2016-07-16 01:43
Well it is to blame due to the way it treats UB, but it will be fixed in utest when @lihaoyi merges https://github.com/lihaoyi/utest/pull/92.
