### ISSUE TITLE
sbt plugin: incremental compilation issue

### ISSUE THREAD

**Issue by allanrenucci** [scala-js/scala-js#3419] opened 2018-07-31 12:21 UTC
In a file `A.scala`:
```scala
class A(val x: Int)
```
In a file `Test.scala`
```scala
class Test {
  def test1(x: A) = 1
  def test2 = test1(null)
}
```
```shell
> sbt compile
[info] Compiling 2 Scala sources to target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 1 s, completed Jul 31, 2018 1:57:29 PM

> shasum target/scala-2.12/classes/*
0aada2bc8ba6e2f3cebdf42f7e911931bc774419  target/scala-2.12/classes/A.class
94aded7b8d5330832a7a701fd9ad55e6cb323ef7  target/scala-2.12/classes/A.sjsir
faedd18f93e31fd6e069bf57d7e0cb5945659689  target/scala-2.12/classes/Test.class
84e558abcc97540db40a66cacbd72928e817dd08  target/scala-2.12/classes/Test.sjsir
```
Now I modify `A.scala` as follows:
```scala
class A(val x: Int) extends AnyVal
```

```shell
> sbt compile
[info] Compiling 1 Scala source to target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to target/scala-2.12/classes ...
[error] src/main/scala/Test.scala:3:21: type mismatch;
[error]  found   : Null(null)
[error]  required: A
[error]   def test2 = test1(null)
[error]                     ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Jul 31, 2018 2:00:13 PM

> shasum target/scala-2.12/classes/*
a19fa4fa7e206eabe387f73d9e0221a445da3647  target/scala-2.12/classes/A$.sjsir
0aada2bc8ba6e2f3cebdf42f7e911931bc774419  target/scala-2.12/classes/A.class
cb0fe0d549ef5256100190b9ac9e3031c52f0299  target/scala-2.12/classes/A.sjsir
faedd18f93e31fd6e069bf57d7e0cb5945659689  target/scala-2.12/classes/Test.class
84e558abcc97540db40a66cacbd72928e817dd08  target/scala-2.12/classes/Test.sjsir
```

When we compile the second time, `A.scala` is recompiled successfully which triggers recompilation of `Test.scala`. The compilation of `Test.scala` fails as expected. `sbt` (aka Zinc) reverts the class files produced during compilation of `A.scala`. It should as well revert the generation of the `.sjsir` files. We are in a state where the class file for `A.scala` are not in sync with the `.sjsir` files. The class files come from the first compilation of `A.scala` and the `.sjsir` files come from the second compilation of `A.scala`.

The issue is that the second compilation of `A.scala` overwrites the class files and `.sjsir` files generated during the first compilation. However Zinc saves the class files in a temporary directory and then restore them when the compilation of `Test.scala` fails. `.sjsir` files are not restored. [Here](https://github.com/sbt/zinc/blob/16e53c2f3933cd9c57f7aee0c5f557ecc34a1592/internal/zinc-core/src/main/scala/sbt/internal/inc/ClassFileManager.scala#L82-L109) is the logic in Zinc that deals with the class files.

This issues manifested itself recently in Dotty lampepfl/dotty#4857. Our logic that deals with TASTY files is [copy-pasted](https://github.com/scala-js/scala-js/blob/53a0d61421e73beaef89e73e19b6a552bd519415/sbt-plugin/src/main/scala-sbt-1.0/org/scalajs/sbtplugin/SBTCompat.scala#L25-L58) from the Scala.js sbt plugin.

**Comment by sjrd** [comment] 2018-07-31 14:27
I'll look into it when I'm back from vacation.

**Comment by allanrenucci** [comment] 2018-08-06 08:16
This was fixed in Dotty by doing [manual aggregation](https://github.com/lampepfl/dotty/blob/f39943db4d75d81917dc055d819ef6b41292fe67/sbt-dotty/src/dotty/tools/sbtplugin/DottyPlugin.scala#L117-L128) of the class file manager to workaround sbt/zinc#562 and having a custom [class file manager](https://github.com/lampepfl/dotty/blob/master/sbt-dotty/src/dotty/tools/sbtplugin/TastyFileManager.scala) for the TASTY files. The custom class file manager cannot delegate to the inherited one. The `complete` callback has to restore deleted files in some cases (e.g. incremental compilation failures). But the `complete` callback deletes the temporary directory where the backed up file are stored, so when the callback is called from the custom class file manager the `.sjsir` (or `.tasty`) files cannot be restored.

**Comment by sjrd** [comment] 2018-08-08 13:46
https://github.com/sbt/zinc/pull/562/files is a PR. Did it break our code, or does it fix a bug that causes our code to be broken before? If the PR fixes a bug, it seems I should just wait for a new version of sbt with the fixed zinc. If it breaks our code, it's a breaking change in zinc which should be fixed on zinc's side ... unless it fixes another latent bug and it was a conscious decision that the previous behavior was buggy and needed to be fixed. But it's not clear to me.

**Comment by allanrenucci** [comment] 2018-08-08 13:53
sbt/zinc#562 fixes a bug. However working around the bug in Zinc is not enough to fix this issue. As described above, you probably need to fix your custom class file manager as well.

**Comment by smarter** [comment] 2018-08-13 14:31
@allanrenucci Can we upstream a more generic version of https://github.com/lampepfl/dotty/blob/master/sbt-dotty/src/dotty/tools/sbtplugin/TastyFileManager.scala to Zinc so that scala-js and other can reuse it instead of reimplementing it?

**Comment by smarter** [comment] 2018-08-13 14:36
As an example, bloop has its own classfilemanager for Dotty: https://github.com/scalacenter/bloop/blob/master/backend/src/main/scala/bloop/internal/Ecosystem.scala (it doesn't have one for Scala.js but it should too), mill doesn't have any custom classfilemanager but it should get one for both Scala.js and Dotty at some point.

**Comment by allanrenucci** [comment] 2018-08-17 07:58
> Can we upstream a more generic version of https://github.com/lampepfl/dotty/blob/master/sbt-dotty/src/dotty/tools/sbtplugin/TastyFileManager.scala to Zinc so that scala-js and others can reuse it instead of reimplementing it?

I could do that. @jvican What's your take on this? Should this be part of this Zinc? How should we expose this to Zinc's users

**Comment by jvican** [comment] 2018-08-17 08:11
Sounds good to me. I would probably upstream a generic version of the class file manager, something like `class AuxiliaryClassFileManager(f: (p: Path) => Boolean) extends ClassFileManager` or even taking a regex as a parameter.

**Comment by sjrd** [comment] 2018-08-17 08:26
> he fix in the zinc side should properly run the class file manager here now. I don't know when a new version will be cut (feel free to ask in the zinc-contrib Gitter channel), so if you want to work around this [...]

If a future version of zinc will solve the issue, I'm not going to work around it now. It's just going to be broken until then. There is always the workaround of `clean`ing.

**Comment by jvican** [comment] 2018-08-17 08:31
> It's not really a (p: Path) => Boolean that we want.
  
The generic version will not only be useful for you, Dotty and Scala Native, but for other users like pants, bloop and other build tools that are also creating their own managers; hence a more generic function is a safe bet.
  
We can work out the details of the API in the zinc issue tracker. I have no strong opinion here, whatever fits you better works for me.

**Comment by sjrd** [comment] 2018-08-17 08:37
`(p: Path) => Boolean` is *not* more generic than what I need. It's *different*. I cannot implement what I need on top of just that. I you ask me: "should I delete `f.sjsir`?", I don't have enough information to answer. I need to know whether you were going to delete `f.class` in order to answer that question.

**Comment by jvican** [comment] 2018-08-17 08:45
Would `(p: Path) => Array[Path]` work for you?

**Comment by jvican** [comment] 2018-08-17 08:48
Alright, I see you proposed the same in the sbt/zinc ticket.

**Comment by gzm0** [comment] 2019-05-22 08:59
From what I understand this is an upstream issue. @sjrd can we close this?

**Comment by sjrd** [comment] 2019-05-22 09:11
Yes, let's close this one and refer to https://github.com/sbt/zinc/issues/579 for follow up.

**Comment by sjrd** [comment] 2019-08-30 09:49
The reproduction of #3596 actually highlights the problem that was raised in this issue, despite the partial fix upstream of https://github.com/sbt/zinc/pull/562.

So I'm reopening.

**Comment by sjrd** [comment] 2019-09-02 20:54
Fixed in 78682118e626ec729836ecffa19f55f6e07ed369.

**Closed by sjrd** 2019-09-02 20:54 UTC
Labels: bug

**Comment by smarter** [comment] 2019-09-02 21:06
Anything we could port back to the tastyfilemanager or is your solution equivalent?

**Comment by sjrd** [comment] 2019-09-02 21:10
It's equivalent. The only changes are at https://github.com/scala-js/scala-js/compare/57540680aa272bed9abfc09aad48c42078eb4c50..46f3646850ad062171f4a8b6fce3e1d3c327bbeb
